import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  codexSidebar: [
    'index',
    'architecture',
    'directory-structure',
    {
      type: 'category',
      label: 'Interfaces and storage',
      items: [
        'api-reference',
        'websocket-events',
        'database-schema',
        'rules-registry',
        'architecture-icd',
      ],
    },
    {
      type: 'category',
      label: 'Development and operations',
      items: [
        'development-setup',
        'configuration',
        'deployment',
        'operations/nexuscodex-homelab',
      ],
    },
    {
      type: 'category',
      label: 'Plans and decision records',
      collapsed: true,
      items: [
        'upgrade-plan',
        'codex-task-runner',
        { type: 'autogenerated', dirName: 'adr' },
      ],
    },
  ],
};

export default sidebars;
