import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  platformSidebar: [
    'index',
    'dependency-policy',
    {
      type: 'category',
      label: 'Architecture and operations',
      items: [
        'private-admin-control-plane',
        'control-api-adr',
        'control-plane-runbook',
        'observability-runbook',
        'object-models-and-data-flow',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/forge-vtt-object-integration-plan',
        'integrations/NEXUSCODEX_INTEGRATION',
        'integrations/INTEGRATED_SETUP',
      ],
    },
    {
      type: 'category',
      label: 'Monorepo migration history',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
  ],
};

export default sidebars;
