import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  vttSidebar: [
    'index',
    {
      type: 'category',
      label: 'Start here',
      items: ['getting-started', 'installation', 'first-game'],
    },
    {
      type: 'category',
      label: 'Tabletop features',
      items: [
        'features/grid-and-coordinates',
        'features/scenes-and-maps',
        'features/tokens',
        'features/fog-of-war',
        'features/drawing-and-ink',
        'features/props',
        'features/initiative-and-combat',
        'features/dice',
      ],
    },
    {
      type: 'category',
      label: 'Architecture and realtime',
      items: [
        'architecture',
        'frontend',
        'backend',
        'network-and-sessions',
        'routing-architecture',
        'internals/layer-stack',
        'realtime/websocket-protocol',
        'ordered-event-delivery',
        'delta-sync-rollout',
      ],
    },
    {
      type: 'category',
      label: 'Assets',
      items: [
        'ASSETS-GUIDE',
        'ASSET_SETUP',
        'DEFAULT_ASSETS_INTEGRATION',
        'assets/processing',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'developer/development',
        'developer/testing',
        'SECURITY_SCANNING',
        'reference-index',
      ],
    },
    {
      type: 'category',
      label: 'Deployment and operations',
      items: [
        'HOMELAB_DEPLOYMENT',
        'DEPLOYMENT_QUICKREF',
        'NPM_CONFIGURATION',
        'operations/multiplayer-observability',
        {
          type: 'category',
          label: 'Cloud deployment',
          items: [{ type: 'autogenerated', dirName: 'cloud' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Decisions and project history',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'adr' },
        { type: 'autogenerated', dirName: 'roadmap' },
      ],
    },
  ],
};

export default sidebars;
