import type { CampaignClue } from '../ashes-of-veyra/types';
import { CROWN_CAMPAIGN_ID, crownSessionId } from './campaign';

export const crownClues: CampaignClue[] = [
  {
    id: 'clue-heirs-contradictions',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Three Contradictory Rumors',
    priority: 'high',
    status: 'unresolved',
    meaning:
      'Each heir is accused of a different secret; only Ysolde’s unpaid war loan links to someone who wanted the coronation disrupted.',
    sourceHandoutIds: [
      'handout-coronation-program',
      'handout-crown-voice-transcript',
    ],
    relatedQuestIds: ['quest-who-wears-the-crown'],
    locationIds: ['location-hall-of-nine-banners'],
    sessionIds: [crownSessionId(1), crownSessionId(3)],
  },
  {
    id: 'clue-flame-signal',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Lamp-Flame Signal',
    priority: 'high',
    status: 'unresolved',
    meaning:
      'The assassins lit their curtains with a Soot Hands guild signal, but the sequence is a decade out of date; someone copied an old code.',
    sourceHandoutIds: ['handout-flame-signal-sketch'],
    relatedQuestIds: ['quest-trace-the-cinder-assassins'],
    locationIds: ['location-guttered-candle', 'location-ashwater-quay'],
    sessionIds: [crownSessionId(1), crownSessionId(2)],
  },
  {
    id: 'clue-unquenched-brand',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Brand of the Unquenched',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'A three-flame brand under the wights’ collarbones matches a symbol scratched inside the Ember Cloister archive.',
    sourceHandoutIds: ['lore-unquenched-creed'],
    relatedQuestIds: [
      'quest-trace-the-cinder-assassins',
      'quest-who-wears-the-crown',
      'quest-crown-remembers',
    ],
    locationIds: ['location-hall-of-nine-banners', 'location-ashen-catacombs'],
    sessionIds: [crownSessionId(1), crownSessionId(5)],
  },
  {
    id: 'clue-dead-prince-seal',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Seal of Prince Aurel',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'The genealogy carries a royal seal ring that was buried with Prince Aurel; either the grave was opened or the seal was never buried.',
    sourceHandoutIds: ['handout-sealed-genealogy'],
    relatedQuestIds: ['quest-dead-princes-genealogy'],
    locationIds: ['location-ashwater-quay', 'location-gilded-exchange'],
    sessionIds: [crownSessionId(1), crownSessionId(3)],
  },
  {
    id: 'clue-burn-list',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Crown’s Burn List',
    priority: 'low',
    status: 'unresolved',
    meaning:
      'The crown recites names in its sleep; nine rulers in nine generations, and the Wardens’ founders are among the accomplices.',
    sourceHandoutIds: ['lore-burned-rulers-roll'],
    relatedQuestIds: ['quest-crown-remembers'],
    locationIds: ['location-crown-vault'],
    sessionIds: [crownSessionId(4)],
  },
  {
    id: 'clue-queens-last-night',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Two Hours of Death',
    priority: 'high',
    status: 'unresolved',
    meaning:
      'The physician’s report puts the queen’s death at the second bell; the Wardens’ door log has a visitor admitted at the third. Someone spoke with her after she was supposedly gone, or the log was altered to hide a visit.',
    sourceHandoutIds: ['handout-physicians-report'],
    relatedQuestIds: ['quest-queens-last-night'],
    locationIds: ['location-queens-chambers'],
    sessionIds: [crownSessionId(3)],
  },
  {
    id: 'clue-pells-marginalia',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Pell’s Marginal Initials',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'A torn ledger page shows advances to all three heirs and a fourth payment marked only “C.A.”, dated the week the genealogy was commissioned. Pell paid someone he does not want the heirs to know about.',
    sourceHandoutIds: ['handout-pell-ledger-excerpt'],
    relatedQuestIds: [
      'quest-who-wears-the-crown',
      'quest-ink-without-blood',
      'quest-border-lords-ultimatum',
    ],
    locationIds: ['location-gilded-exchange'],
    sessionIds: [crownSessionId(3)],
  },
  {
    id: 'clue-forgers-ink',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Ink That Burns Blue',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'The genealogy was written decades ago, but the ink was refreshed within the month with an iron-gall recipe unique to Inkwell Court. The document may be genuine and merely restored, which is more dangerous than a forgery.',
    sourceHandoutIds: ['handout-forgers-receipt', 'handout-sealed-genealogy'],
    relatedQuestIds: [
      'quest-ink-without-blood',
      'quest-dead-princes-genealogy',
    ],
    locationIds: ['location-inkwell-court'],
    sessionIds: [crownSessionId(3)],
  },
  {
    id: 'clue-corvin-war-writ',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Border War Writ',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'Corvin’s signature on a writ promising the Marcher Lords a council seat and the northern tolls. It was signed before the queen died, which suggests he expected the succession to be contested.',
    sourceHandoutIds: ['handout-marchwarden-writ'],
    relatedQuestIds: [
      'quest-border-lords-ultimatum',
      'quest-who-wears-the-crown',
    ],
    locationIds: ['location-marchwarden-house'],
    sessionIds: [crownSessionId(3)],
  },
  {
    id: 'clue-empty-coffin',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Infant’s Coffin Is Empty',
    priority: 'high',
    status: 'unresolved',
    meaning:
      'Prince Aurel’s tiny sarcophagus holds ash and a carved wooden horse, no remains. The mausoleum register records a Warden escort on the night of the burial. Someone knew the grave was empty long before the genealogy surfaced.',
    sourceHandoutIds: ['handout-mausoleum-register'],
    relatedQuestIds: ['quest-dead-princes-genealogy'],
    locationIds: ['location-royal-mausoleum'],
    sessionIds: [crownSessionId(4)],
  },
  {
    id: 'clue-cloister-ash-mismatch',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Cloister Ash on the Wights',
    priority: 'low',
    status: 'unresolved',
    meaning:
      'The ash caked on the fallen cinder wights is not wild volcanic glass but the fine grey ash of the Cloister’s consecrated braziers. Someone with the Wardens’ trust is feeding the Unquenched.',
    sourceHandoutIds: ['lore-warden-founding-oath'],
    relatedQuestIds: ['quest-trace-the-cinder-assassins'],
    locationIds: ['location-ember-cloister', 'location-hall-of-nine-banners'],
    sessionIds: [crownSessionId(2), crownSessionId(5)],
  },
];
