import type { CampaignHandout } from '../ashes-of-veyra/types';
import { CROWN_CAMPAIGN_ID, crownSessionId } from './campaign';

export const crownHandouts: CampaignHandout[] = [
  {
    id: 'handout-coronation-program',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Coronation Program',
    kind: 'handout',
    summary:
      'A printed order of ceremony listing the three heirs, their sponsors, and the moment the crown is to be presented.',
    content: [
      'The Investiture of the Crown of Cinders. Order of ceremony: the Calling of the Banners, the Oath of the Wardens, the Presentation of the Crown, the Blessing of Ash.',
      'Beneath each heir’s name is a sponsor and a line of neat pencilled gossip in an unknown hand. Corvin: "owes the border lords." Ysolde: "owes the Ledger." Tamsin: "was not at the funeral."',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(1)],
    clueIds: ['clue-heirs-contradictions'],
    questIds: ['quest-who-wears-the-crown'],
    locationIds: ['location-hall-of-nine-banners'],
    factionIds: ['faction-house-vell'],
  },
  {
    id: 'handout-crown-voice-transcript',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Crown Speaks (transcript)',
    kind: 'handout',
    summary:
      'A player-facing transcript of the crown’s first words. Audio recording still to be made.',
    content: [
      'Three come to wear me. Three have lied to me. Only one lie has blood on it.',
      'Do not ask which. Ask what each of them was doing when the old queen stopped breathing.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(1)],
    clueIds: ['clue-heirs-contradictions'],
    questIds: ['quest-who-wears-the-crown'],
    locationIds: ['location-hall-of-nine-banners'],
    factionIds: ['faction-house-vell'],
  },
  {
    id: 'handout-sealed-genealogy',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Sealed Genealogy',
    kind: 'handout',
    summary:
      'A folded genealogy sealed with a royal ring, naming Prince Aurel Vell as the queen’s firstborn.',
    content: [
      'A single sheet stained with soot. Beneath the queen’s name is a line to a first son, Aurel, born before Corvin and declared dead in infancy.',
      'The seal impression is a royal ring pattern. The wax is fresh, and the ink is not.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(1), crownSessionId(3)],
    clueIds: ['clue-dead-prince-seal'],
    questIds: ['quest-dead-princes-genealogy'],
    locationIds: ['location-ashwater-quay', 'location-gilded-exchange'],
    factionIds: ['faction-house-vell', 'faction-gilded-ledger'],
  },
  {
    id: 'handout-heir-relationship-cards',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Heir Relationship Cards',
    kind: 'handout',
    summary:
      'DM reference cards for each heir: what they want, what they hide, how they treat each player character.',
    content: [
      'Corvin: wants the party’s swords, hides a war debt to the border lords, respects Bryn’s oath.',
      'Ysolde: wants the party’s discretion, hides an unpaid loan from the Ledger, admires Sable’s speechwriting.',
      'Tamsin: wants the party’s trust, hides that she has already spoken with the crown in private, recognises Ivo from the cloister kitchens.',
    ],
    visibility: 'dm-only',
    sessionIds: [crownSessionId(1)],
    clueIds: ['clue-heirs-contradictions'],
    questIds: ['quest-who-wears-the-crown'],
    locationIds: ['location-hall-of-nine-banners'],
    factionIds: ['faction-house-vell'],
  },
  {
    id: 'handout-flame-signal-sketch',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Flame Signal Sketch',
    kind: 'handout',
    summary:
      'A hasty sketch of the three-long, one-short lamp flame pattern used by the assassins.',
    content: [
      'A sketch of a guttering lamp with a pattern of marks beneath it: three long strokes, one short, a pause.',
      'Ivo will know the guild meaning immediately. Anyone else will need to ask around at the Guttered Candle.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(2)],
    clueIds: ['clue-flame-signal'],
    questIds: ['quest-trace-the-cinder-assassins'],
    locationIds: ['location-guttered-candle', 'location-ashwater-quay'],
    factionIds: ['faction-soot-hands'],
  },
  {
    id: 'lore-burned-rulers-roll',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Roll of the Burned Rulers',
    kind: 'lore',
    summary:
      'The crown’s private memory: nine names, nine deaths, and who stood beside each ruler at the end.',
    content: [
      'The crown recalls each bearer’s name and the last lie told to it. Seven died of fire; two were pulled from the flames by Warden hands.',
      'The roll is the campaign’s late-game reveal. Do not surface it before session 4.',
    ],
    visibility: 'dm-only',
    sessionIds: [crownSessionId(4)],
    clueIds: ['clue-burn-list'],
    questIds: ['quest-crown-remembers'],
    locationIds: ['location-crown-vault'],
    factionIds: ['faction-ember-wardens'],
  },
  {
    id: 'lore-unquenched-creed',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Creed of the Unquenched',
    kind: 'lore',
    summary:
      'A cult catechism explaining why the Unquenched want the crown’s judgement burned out of the realm.',
    content: [
      'We are the fire the crown cannot weigh. No ruler may sit in judgement of the flame that made them.',
      'Recruits are branded beneath the collarbone with three flames. The brand does not scar until the rite is complete.',
    ],
    visibility: 'dm-only',
    sessionIds: [crownSessionId(1), crownSessionId(5)],
    clueIds: ['clue-unquenched-brand'],
    questIds: ['quest-trace-the-cinder-assassins'],
    locationIds: ['location-ashen-catacombs'],
    factionIds: ['faction-unquenched'],
  },
  {
    id: 'lore-succession-law',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Law of Succession',
    kind: 'lore',
    summary:
      'The old law that lets the crown itself name the bearer when a monarch dies without naming an heir.',
    content: [
      'When no heir is named, the crown chooses. The bearer is confirmed by three witnesses of the hall who are not of the blood.',
      'Nobody has invoked the witness clause in three hundred years, which is why the party matters.',
    ],
    visibility: 'dm-only',
    sessionIds: [crownSessionId(1), crownSessionId(6)],
    clueIds: [],
    questIds: ['quest-who-wears-the-crown'],
    locationIds: ['location-hall-of-nine-banners'],
    factionIds: ['faction-house-vell'],
  },
  {
    id: 'handout-proclamation-of-mourning',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Proclamation of Mourning',
    kind: 'handout',
    summary:
      'The royal crier’s printed proclamation announcing the queen’s death, the forty days of ash, and the investiture date.',
    content: [
      'BY ORDER OF THE HOUSE OF VELL, in the forty-first year of the reign. Queen Maren, Keeper of the Nine Banners, has gone into the ash. Let every hearth in Ashgate be banked for forty days, and every lamplighter wear black on the left sleeve.',
      'On the fortieth night the Crown of Cinders shall be presented in the Hall of Nine Banners, that the realm may see it placed. No heir was named in the queen’s will. The Crown, by the Law of Succession, shall choose.',
      'Let no steel be drawn within the palace walls. Let no debt be called within the city. Let no one say the queen died of anything but age. So proclaimed, and so sealed by the Lord Marshal.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(1)],
    clueIds: [],
    questIds: ['quest-who-wears-the-crown'],
    locationIds: ['location-ashgate', 'location-hall-of-nine-banners'],
    factionIds: ['faction-house-vell'],
  },
  {
    id: 'handout-ysolde-letter',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Letter from Princess Ysolde',
    kind: 'handout',
    summary:
      'A perfumed, carefully worded letter from Ysolde offering the party patronage and asking for one discreet favor.',
    content: [
      'To the one who writes so well in other people’s names: the speeches were excellent, and I am sorry I did not know sooner that three of them were yours. Come to the Gilded Exchange tomorrow at the noon bell. Ask for the gallery. Do not ask for me.',
      'I will not insult you by pretending I need nothing. A scrivener in Inkwell Court has done a piece of work I need understood before it is used against me. You will be paid in coin and in debts forgiven, which in this city are the same thing.',
      'My brother thinks loyalty is a sword. My sister thinks it is a question. I think it is a contract. You may judge which of us is the most honest. I would only ask that you judge after you have met all three. Y.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(1), crownSessionId(2)],
    clueIds: [],
    questIds: ['quest-ink-without-blood', 'quest-who-wears-the-crown'],
    locationIds: ['location-gilded-exchange'],
    factionIds: ['faction-house-vell', 'faction-gilded-ledger'],
  },
  {
    id: 'handout-corvin-dispatch',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Corvin’s Field Dispatch',
    kind: 'handout',
    summary:
      'A terse military note from the Lord Marshal asking the party to bring a sealed packet to the Marchers before the coronation.',
    content: [
      'You saw what happened in that hall, and you did not run. I am not a man for speeches, so here is the plain of it: the frontier lords will take the dead queen’s silence for weakness. A packet is enclosed for Marchwarden Rook at the House in the Row of Banners.',
      'Do not open it. If she asks what it says, tell her it says I am coming myself. That will be true by the fifth day. The border will not be left without a hand on the hilt, whoever sits the throne. C.V.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(1), crownSessionId(3)],
    clueIds: ['clue-corvin-war-writ'],
    questIds: ['quest-border-lords-ultimatum', 'quest-who-wears-the-crown'],
    locationIds: ['location-marchwarden-house', 'location-hall-of-nine-banners'],
    factionIds: ['faction-house-vell', 'faction-border-lords'],
  },
  {
    id: 'handout-tamsin-note',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Tamsin’s Note on Cloister Paper',
    kind: 'handout',
    summary:
      'A hurried note on Cloister vellum asking the party to meet her where the braziers never go out.',
    content: [
      'Please do not tell Marshal Brack I sent this. I have asked the crown a question every night for a week and it has answered only twice, but both times with a name. I will not write the name here.',
      'The Cloister has a room the novices are told is a linen store. It is warm, and the lock is new. Come at dusk, by the kitchen door; the cook knows you, I think. I am not asking you to choose me. I am asking you to let me be wrong in front of someone who will tell me. T.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(1), crownSessionId(4)],
    clueIds: [],
    questIds: ['quest-crown-remembers'],
    locationIds: ['location-ember-cloister'],
    factionIds: ['faction-ember-wardens', 'faction-house-vell'],
  },
  {
    id: 'handout-physicians-report',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Physician’s Report',
    kind: 'handout',
    summary:
      'The royal physician’s formal certificate of death, with a time that does not match the Wardens’ door log.',
    content: [
      'I, Aldous Venn, physician to the house, attest that Her Majesty Queen Maren Vell expired in her bed at the second bell after midnight, of a stoppage of the heart brought on by age and grief. No violence was done. The body was cold when I arrived.',
      'Appended in a smaller hand: the lamp on the nightstand was found lit and its oil half spent. A silver cup, scorched at the rim, was removed by the Warden on watch at my request. I ask that the cup be returned to the house.',
      'A pencilled note in a different hand has been scratched out in the margin; the words “third bell” are still legible beneath the scratch.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(3)],
    clueIds: ['clue-queens-last-night'],
    questIds: ['quest-queens-last-night'],
    locationIds: ['location-queens-chambers'],
    factionIds: ['faction-house-vell', 'faction-ember-wardens'],
  },
  {
    id: 'handout-pell-ledger-excerpt',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Torn Page of Pell’s Ledger',
    kind: 'handout',
    summary:
      'A single page torn from the Gilded Ledger’s private books showing advances to the three heirs and a fourth, unexplained payment.',
    content: [
      'Corvin V.: 4,000 crowns, secured on the northern tolls. Ysolde V.: 6,500 crowns, secured on the Exchange’s own mortgage. Tamsin V.: 300 crowns, “for books,” no security required.',
      'Beneath the heirs, a fourth line in a different ink: “C.A. - 2,000 crowns, paid in full in advance, fifteen days before the queen’s final illness. Do not minute.” The initials have been traced over twice, as if to make them harder to read.',
      'The page is dated three weeks before the proclamation. The tear is clean along the binding, and the missing pages were cut, not ripped.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(3)],
    clueIds: ['clue-pells-marginalia'],
    questIds: [
      'quest-who-wears-the-crown',
      'quest-ink-without-blood',
      'quest-border-lords-ultimatum',
    ],
    locationIds: ['location-gilded-exchange'],
    factionIds: ['faction-gilded-ledger'],
  },
  {
    id: 'handout-forgers-receipt',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Inkwell Court Receipt',
    kind: 'handout',
    summary:
      'A scrap receipt from Ferrant Inkwell’s workshop for ink restoration, signed with a client mark and no name.',
    content: [
      'Received this day, one sheet, of the old pattern, for restoration of fading iron-gall ink. Work done by the unnamed hand of the house; recipe held in confidence. Paid: 90 crowns, in coin, before the work began.',
      'The client mark is a tiny three-pointed crown pressed into the wax, not a name. A second hand has noted in the margin: “Client collected personally. Wore gloves. Smelled of the Cloister.”',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(3)],
    clueIds: ['clue-forgers-ink'],
    questIds: ['quest-ink-without-blood', 'quest-dead-princes-genealogy'],
    locationIds: ['location-inkwell-court'],
    factionIds: ['faction-gilded-ledger', 'faction-soot-hands'],
  },
  {
    id: 'handout-marchwarden-writ',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Marcher Writ',
    kind: 'handout',
    summary:
      'A copy of the war writ promising the Marcher Lords a council seat and the northern tolls in exchange for their muster.',
    content: [
      'Know all by this writ that the Lord Marshal, in the name of the throne, binds the realm to give the Marcher Lords: one seat upon the Grand Council, in perpetuity; the whole of the northern tolls for ten years; and the right to garrison their own passes.',
      'In return the Marchers shall muster in full upon the Lord Marshal’s word, against any foe of the throne, within or without the realm. Signed at Greywatch, in the year before the queen’s last winter. C. Vell. D. Rook, witness.',
      'The writ is dated eleven months before the queen died. Nobody in the capital has seen it; the Treasury has no record of the tolls being pledged.',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(3)],
    clueIds: ['clue-corvin-war-writ'],
    questIds: ['quest-border-lords-ultimatum'],
    locationIds: ['location-marchwarden-house'],
    factionIds: ['faction-border-lords', 'faction-house-vell'],
  },
  {
    id: 'handout-mausoleum-register',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Vellgrave Burial Register',
    kind: 'handout',
    summary:
      'The mausoleum keeper’s register with an entry for an infant prince and a Warden escort on the night of his burial.',
    content: [
      'Entered in the keeper’s hand: “Aurel Vell, firstborn of Queen Maren, aged eleven days. Interred under the east arch. Sealed by order of the Warden-Marshal. Attended: Marshal Brack’s predecessor, one midwife, no family.”',
      'The next page has been torn out. A pressed flower falls from the binding: a white ash-lily, which does not grow within a day’s ride of Ashgate.',
      'The keeper has added in a shaky margin: “The coffin was lighter than it should have been. I said nothing, as I was asked.”',
    ],
    visibility: 'shared',
    sessionIds: [crownSessionId(4)],
    clueIds: ['clue-empty-coffin'],
    questIds: ['quest-dead-princes-genealogy'],
    locationIds: ['location-royal-mausoleum'],
    factionIds: ['faction-house-vell', 'faction-ember-wardens'],
  },
  {
    id: 'lore-warden-founding-oath',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Warden’s Founding Oath',
    kind: 'lore',
    summary:
      'The oath every Ember Warden swears, and the founders’ original version that the order no longer speaks aloud.',
    content: [
      'The public oath: “I keep the flame that keeps the crown. I serve the one who bears it, and I judge not the bearer.” Every novice learns it by heart, and every novice is taught that the last clause is a mercy.',
      'The original oath, recorded in the Cloister archive: “I keep the flame that keeps the crown. I serve the one who bears it, and I shall not speak what it burns.” The founders knew the crown consumed its bearers and swore silence in exchange for the Cloister’s patronage.',
      'DM note: the Wardens’ consecrated brazier ash is a fine grey powder blessed with a pinch of crown-iron. Anyone who has seen it will recognize it on the cinder wights. Only a Warden, or someone who stole from the Cloister, could have supplied it to the Unquenched.',
    ],
    visibility: 'dm-only',
    sessionIds: [crownSessionId(5)],
    clueIds: ['clue-cloister-ash-mismatch'],
    questIds: ['quest-trace-the-cinder-assassins', 'quest-crown-remembers'],
    locationIds: ['location-ember-cloister'],
    factionIds: ['faction-ember-wardens'],
  },
  {
    id: 'lore-crowns-verses',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Crown’s Whispered Verses',
    kind: 'lore',
    summary:
      'Nine short verses the crown murmurs to whoever touches it. Use one per session as a prompt for its voice.',
    content: [
      'First, to a new bearer: “You are warmer than the last. They are always warm at first.” Second, when a lie is told in its presence: “That was a small one. I keep the small ones.” Third, when it is asked who it prefers: “I do not prefer. I remember.”',
      'Fourth, near fire: “I was made of what the fire left behind. Do not call it cruelty. Call it weight.” Fifth, to Tamsin alone: “You ask me why. No one has asked me why in a hundred years.” Sixth, to Bryn: “You swore to me, not to the head I rest on. That is rare. I will remember it.”',
      'Seventh, in the vault: “Nine have worn me. Seven burned. Two were taken from the flames, and the hands that took them remain here, unwashed.” Eighth, if it is placed on the wrong head: “I will bear it. I will not forgive it.” Ninth, spoken only at the end: “Name the one who lied to me last, and I will tell you why.”',
    ],
    visibility: 'dm-only',
    sessionIds: [
      crownSessionId(1),
      crownSessionId(4),
      crownSessionId(6),
    ],
    clueIds: ['clue-burn-list'],
    questIds: ['quest-who-wears-the-crown', 'quest-queens-last-night'],
    locationIds: ['location-hall-of-nine-banners', 'location-crown-vault'],
    factionIds: [],
  },
  {
    id: 'lore-court-gossip',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Court Gossip of Ashgate',
    kind: 'lore',
    summary:
      'A table of rumors the party can overhear in the palace, the guild districts and the exchange, most half-true.',
    content: [
      'Palace corridors: “Corvin has been practising his acceptance speech in the stables for a month.” “Ysolde’s gloves are lined with Ledger silk.” “Tamsin has not slept in her own bed since the funeral.” “The old queen asked for the crown a night before she died, and it was brought to her.”',
      'The guild districts: “The lamp code was sold, not stolen.” “The Watch will not patrol the Row after dark this week. Somebody paid.” “There is a man at the quay who says he is the dead prince, and he has the queen’s mole on his left shoulder.”',
      'The Exchange: “Pell has lent to all three heirs and sleeps like a baby.” “The Marchers have moved a banner company within three days’ ride.” “Ink is going up in Inkwell Court, and nobody knows why.” Roll d12 for each scene, or choose by what the party already knows.',
    ],
    visibility: 'dm-only',
    sessionIds: [crownSessionId(1), crownSessionId(3)],
    clueIds: ['clue-heirs-contradictions'],
    questIds: ['quest-who-wears-the-crown', 'quest-keep-ashgate-from-burning'],
    locationIds: ['location-ashgate', 'location-palace-hill'],
    factionIds: ['faction-house-vell', 'faction-gilded-ledger'],
  },
  {
    id: 'lore-history-of-the-crown',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'History of the Crown of Cinders',
    kind: 'lore',
    summary:
      'How the crown was forged from the volcano’s first cooled glass, why it judges, and why nine generations have burned for it.',
    content: [
      'The Founding Queen, Ilsabet the Smith, forged the crown from the first glass cooled after the Ashgate mountain woke. She meant it as a seal on a bargain with the fire-spirits that had burned the old kingdom: rule well, and the mountain sleeps. Break the bargain, and the crown remembers.',
      'The crown was never meant to speak. A century after the forging, a queen lied to it in her last hour, and it spoke back for the first time. Every bearer since has been tested the same way. Some died of the flames the crown calls; some were saved by others, and the crown remembers both with equal weight.',
      'The Wardens began as the crown’s caretakers and became its jailers. They hid that the crown judges, because a realm that knows its crown can burn kings does not crown kings. The Unquenched grew in the space between: people who believe the bargain was a cage and the mountain should wake.',
    ],
    visibility: 'dm-only',
    sessionIds: [crownSessionId(4), crownSessionId(6)],
    clueIds: ['clue-burn-list'],
    questIds: ['quest-crown-remembers'],
    locationIds: ['location-crown-vault'],
    factionIds: ['faction-ember-wardens', 'faction-unquenched'],
  },
];
