import type { FolderRecord, LibraryObject } from '../ashes-of-veyra/types';
import { CROWN_CAMPAIGN_ID } from './campaign';

const ACT_1 = `${CROWN_CAMPAIGN_ID}-act-1`;
const ACT_2 = `${CROWN_CAMPAIGN_ID}-act-2`;
const ACT_3 = `${CROWN_CAMPAIGN_ID}-act-3`;

export const crownLibraryObjects: LibraryObject[] = [
  {
    id: 'scene-hall-of-nine-banners',
    title: 'The Hall of Nine Banners',
    kind: 'scene',
    folderActId: ACT_1,
    updatedLabel: '20 minutes ago',
  },
  {
    id: 'scene-guttered-candle-cellar',
    title: 'The Guttered Candle Cellar',
    kind: 'scene',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'scene-crown-vault-template',
    title: 'Crown Vault (template)',
    kind: 'scene',
    folderActId: ACT_2,
    updatedLabel: '3 days ago',
  },
  {
    id: 'npc-corvin-vell',
    title: 'Prince Corvin Vell',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: '1 hour ago',
  },
  {
    id: 'npc-the-crown',
    title: 'The Crown of Cinders',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-cinder-wights-dais',
    title: 'Cinder Wights at the Dais',
    kind: 'encounter',
    folderActId: ACT_1,
    updatedLabel: '20 minutes ago',
  },
  {
    id: 'handout-crown-voice-transcript',
    title: 'The Crown Speaks (transcript)',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-sealed-genealogy',
    title: 'The Sealed Genealogy',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: '2 days ago',
  },
  {
    id: 'lore-burned-rulers-roll',
    title: 'Roll of the Burned Rulers',
    kind: 'lore',
    folderActId: ACT_2,
    updatedLabel: '3 days ago',
  },
  {
    id: 'faction-ember-wardens',
    title: 'The Ember Wardens',
    kind: 'faction',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'quest-who-wears-the-crown',
    title: 'Who Wears the Crown',
    kind: 'quest',
    folderActId: ACT_1,
    updatedLabel: 'Today',
  },
  {
    id: 'npc-ysolde-vell',
    title: 'Princess Ysolde Vell',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-tamsin-vell',
    title: 'Tamsin Vell',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-halden-brack',
    title: 'Marshal Halden Brack',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: '2 days ago',
  },
  {
    id: 'npc-courier-wren',
    title: 'Wren Ashdown',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: '2 days ago',
  },
  {
    id: 'npc-nell-soot',
    title: 'Nell Soot',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: '3 days ago',
  },
  {
    id: 'npc-sera-lampwright',
    title: 'Sera Lampwright',
    kind: 'npc',
    folderActId: ACT_1,
    updatedLabel: '2 days ago',
  },
  {
    id: 'encounter-heirs-audience',
    title: 'Audience with the Heirs',
    kind: 'encounter',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-guttered-candle-brawl',
    title: 'Brawl at the Guttered Candle',
    kind: 'encounter',
    folderActId: ACT_1,
    updatedLabel: '3 days ago',
  },
  {
    id: 'encounter-ashwater-chase',
    title: 'Chase Across the Ash Barges',
    kind: 'encounter',
    folderActId: ACT_1,
    updatedLabel: '2 days ago',
  },
  {
    id: 'handout-coronation-program',
    title: 'Coronation Program',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-proclamation-of-mourning',
    title: 'Proclamation of Mourning',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-ysolde-letter',
    title: 'Letter from Princess Ysolde',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: 'Today',
  },
  {
    id: 'handout-corvin-dispatch',
    title: 'Corvin’s Field Dispatch',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: 'Today',
  },
  {
    id: 'handout-tamsin-note',
    title: 'Tamsin’s Note on Cloister Paper',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: 'Today',
  },
  {
    id: 'handout-flame-signal-sketch',
    title: 'Flame Signal Sketch',
    kind: 'handout',
    folderActId: ACT_1,
    updatedLabel: '3 days ago',
  },
  {
    id: 'lore-crowns-verses',
    title: 'The Crown’s Whispered Verses',
    kind: 'lore',
    folderActId: ACT_1,
    updatedLabel: 'Today',
  },
  {
    id: 'faction-soot-hands',
    title: 'The Soot Hands',
    kind: 'faction',
    folderActId: ACT_1,
    updatedLabel: '3 days ago',
  },
  {
    id: 'faction-house-vell',
    title: 'House Vell',
    kind: 'faction',
    folderActId: ACT_1,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'quest-trace-the-cinder-assassins',
    title: 'Trace the Cinder Assassins',
    kind: 'quest',
    folderActId: ACT_1,
    updatedLabel: '2 days ago',
  },
  {
    id: 'npc-oswin-pell',
    title: 'Lord Treasurer Oswin Pell',
    kind: 'npc',
    folderActId: ACT_2,
    updatedLabel: '4 days ago',
  },
  {
    id: 'npc-dagna-rook',
    title: 'Marchwarden Dagna Rook',
    kind: 'npc',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'npc-ferrant-inkwell',
    title: 'Ferrant Inkwell',
    kind: 'npc',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'npc-vessa-thornscale',
    title: 'Captain Vessa Thornscale',
    kind: 'npc',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'npc-quillon-thrum',
    title: 'Brother Quillon Thrum',
    kind: 'npc',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'npc-maren-vell',
    title: 'Queen Maren Vell (deceased)',
    kind: 'npc',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-border-lords-parley',
    title: 'Parley at Marchwarden House',
    kind: 'encounter',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'encounter-forgers-den',
    title: 'The Forger’s Den',
    kind: 'encounter',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'encounter-queens-chambers-inquest',
    title: 'Inquest in the Queen’s Chambers',
    kind: 'encounter',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-vault-guardians',
    title: 'Guardians of the Crown Vault',
    kind: 'encounter',
    folderActId: ACT_2,
    updatedLabel: '4 days ago',
  },
  {
    id: 'encounter-mausoleum-vigil',
    title: 'Vigil in the Vellgrave Mausoleum',
    kind: 'encounter',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-physicians-report',
    title: 'The Physician’s Report',
    kind: 'handout',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-pell-ledger-excerpt',
    title: 'Torn Page of Pell’s Ledger',
    kind: 'handout',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-forgers-receipt',
    title: 'Inkwell Court Receipt',
    kind: 'handout',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'handout-marchwarden-writ',
    title: 'The Marcher Writ',
    kind: 'handout',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'handout-mausoleum-register',
    title: 'Vellgrave Burial Register',
    kind: 'handout',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'lore-court-gossip',
    title: 'Court Gossip of Ashgate',
    kind: 'lore',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'lore-history-of-the-crown',
    title: 'History of the Crown of Cinders',
    kind: 'lore',
    folderActId: ACT_2,
    updatedLabel: '3 days ago',
  },
  {
    id: 'faction-gilded-ledger',
    title: 'The Gilded Ledger',
    kind: 'faction',
    folderActId: ACT_2,
    updatedLabel: '4 days ago',
  },
  {
    id: 'faction-border-lords',
    title: 'The Marcher Lords',
    kind: 'faction',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'faction-ashgate-watch',
    title: 'The Ashgate Watch',
    kind: 'faction',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'quest-queens-last-night',
    title: 'The Queen’s Last Night',
    kind: 'quest',
    folderActId: ACT_2,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'quest-border-lords-ultimatum',
    title: 'The Marchers’ Ultimatum',
    kind: 'quest',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'quest-ink-without-blood',
    title: 'Ink Without Blood',
    kind: 'quest',
    folderActId: ACT_2,
    updatedLabel: 'Today',
  },
  {
    id: 'quest-keep-ashgate-from-burning',
    title: 'Keep Ashgate From Burning',
    kind: 'quest',
    folderActId: ACT_2,
    updatedLabel: '2 days ago',
  },
  {
    id: 'quest-dead-princes-genealogy',
    title: 'The Dead Prince’s Genealogy',
    kind: 'quest',
    folderActId: ACT_2,
    updatedLabel: '3 days ago',
  },
  {
    id: 'npc-mother-cinder',
    title: 'Mother Cinder',
    kind: 'npc',
    folderActId: ACT_3,
    updatedLabel: '4 days ago',
  },
  {
    id: 'npc-aurel-claimant',
    title: 'The Man Who Calls Himself Aurel',
    kind: 'npc',
    folderActId: ACT_3,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-catacomb-ashbound',
    title: 'The Ashbound in the Catacombs',
    kind: 'encounter',
    folderActId: ACT_3,
    updatedLabel: '4 days ago',
  },
  {
    id: 'encounter-witness-clause',
    title: 'The Witness Clause',
    kind: 'encounter',
    folderActId: ACT_3,
    updatedLabel: 'Today',
  },
  {
    id: 'lore-unquenched-creed',
    title: 'Creed of the Unquenched',
    kind: 'lore',
    folderActId: ACT_3,
    updatedLabel: '4 days ago',
  },
  {
    id: 'lore-warden-founding-oath',
    title: 'The Warden’s Founding Oath',
    kind: 'lore',
    folderActId: ACT_3,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'lore-succession-law',
    title: 'The Law of Succession',
    kind: 'lore',
    folderActId: ACT_3,
    updatedLabel: '5 days ago',
  },
  {
    id: 'faction-unquenched',
    title: 'The Unquenched',
    kind: 'faction',
    folderActId: ACT_3,
    updatedLabel: '4 days ago',
  },
  {
    id: 'quest-crown-remembers',
    title: 'What the Crown Remembers',
    kind: 'quest',
    folderActId: ACT_3,
    updatedLabel: '3 days ago',
  },
];

const objectIdsForAct = (actId: string): string[] =>
  crownLibraryObjects
    .filter((object) => object.folderActId === actId)
    .map((object) => object.id);

const childCounts = (actId: string): FolderRecord['children'] => {
  const objects = crownLibraryObjects.filter(
    (object) => object.folderActId === actId,
  );
  const count = (kinds: LibraryObject['kind'][]): number =>
    objects.filter((object) => kinds.includes(object.kind)).length;
  return [
    { kind: 'scene', count: count(['scene']) },
    { kind: 'npc', count: count(['npc']) },
    { kind: 'encounter', count: count(['encounter']) },
    { kind: 'handout', count: count(['handout', 'lore']) },
  ];
};

export const crownFolders: FolderRecord[] = [
  {
    id: 'folder-crown-act-one',
    title: 'Act I - The Investiture',
    actId: ACT_1,
    objectIds: objectIdsForAct(ACT_1),
    children: childCounts(ACT_1),
  },
  {
    id: 'folder-crown-act-two',
    title: 'Act II - A Court of Knives',
    actId: ACT_2,
    objectIds: objectIdsForAct(ACT_2),
    children: childCounts(ACT_2),
  },
  {
    id: 'folder-crown-act-three',
    title: 'Act III - The Crown Remembers',
    actId: ACT_3,
    objectIds: objectIdsForAct(ACT_3),
    children: childCounts(ACT_3),
  },
];
