import type { CampaignLocation } from '../ashes-of-veyra/types';
import { CROWN_CAMPAIGN_ID } from './campaign';

const MAP = 'map-ashgate-royal-quarter';

export const crownLocations: CampaignLocation[] = [
  {
    id: 'location-ashgate',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'Ashgate',
    type: 'district',
    shortDescription:
      'The soot-dark capital of the realm, built around a hill of cooled volcanic glass.',
    description: [
      'Chimneys in every colour of smoke crowd the skyline. Lamplighters race the dusk from street to street.',
      'The royal quarter sits on the hill; the guild districts sprawl below, each with its own smell and its own arrangements.',
      'During the forty days of ash every hearth is banked and every lamplighter wears black. The city is quiet in the way a held breath is quiet: the Watch doubles its patrols, the guilds close their doors early, and everyone is waiting to learn who the crown will choose.',
    ],
    tags: ['City', 'Capital', 'Court'],
    mapId: MAP,
    pinId: 'pin-hall-of-nine-banners',
    npcIds: ['npc-oswin-pell', 'npc-corvin-vell', 'npc-vessa-thornscale'],
    factionIds: [
      'faction-house-vell',
      'faction-gilded-ledger',
      'faction-soot-hands',
      'faction-ashgate-watch',
      'faction-border-lords',
    ],
    encounterIds: [],
    questIds: [
      'quest-who-wears-the-crown',
      'quest-keep-ashgate-from-burning',
    ],
    handoutIds: [
      'lore-succession-law',
      'handout-proclamation-of-mourning',
      'lore-court-gossip',
    ],
    notes:
      'The city selector region; use district records for specific scenes and encounters. Roll on the court gossip table when the party crosses the city between scenes.',
  },
  {
    id: 'location-palace-hill',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'Palace Hill',
    type: 'district',
    shortDescription:
      'The glassy rise at the centre of Ashgate where the palace, the Cloister and the crown’s vault share a single wall.',
    description: [
      'The hill is a single slab of black volcanic glass, polished by centuries of boots and weather. At dusk the whole slope catches the lamplight and the palace seems to float.',
      'Three gates lead up: the Marshal’s Gate for soldiers and Wardens, the Banner Gate for guests and ceremony, and the Servants’ Stair, which every guard knows is the way things really move in and out.',
      'The Watch keeps a checkpoint at every gate during the mourning. Captain Thornscale posts her most trusted sergeants at the Banner Gate and her least trusted at the stair, a choice that turns out to matter.',
    ],
    tags: ['Palace', 'Gate checkpoints', 'Court'],
    parentLocationId: 'location-ashgate',
    mapId: MAP,
    npcIds: ['npc-vessa-thornscale', 'npc-corvin-vell'],
    factionIds: [
      'faction-house-vell',
      'faction-ashgate-watch',
      'faction-ember-wardens',
    ],
    encounterIds: [],
    questIds: ['quest-keep-ashgate-from-burning'],
    handoutIds: ['lore-court-gossip'],
    notes:
      'A connective location rather than a scene. Use it for travel, checkpoint banter and overheard conversations between the larger set pieces.',
  },
  {
    id: 'location-hall-of-nine-banners',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'Hall of Nine Banners',
    type: 'government',
    shortDescription:
      'The vaulted throne hall where the coronation is held, hung with one banner for each ruler the crown has burned.',
    description: [
      'Nine banners, eight of them faded. The ninth is the queen’s, and it is still bright.',
      'The dais stands at the north end, with braziers of ceremonial ash on either side.',
      'The ceiling is a shallow dome of black glass that reflects the braziers as a field of small fires. During the ceremony the nave is packed with a hundred guests, and the only exits are the Banner Gate doors behind them and the vestry at the dais, which the Wardens keep locked.',
    ],
    tags: ['Throne hall', 'Session 1', 'Session 6', 'Fire hazard'],
    parentLocationId: 'location-palace-hill',
    mapId: MAP,
    pinId: 'pin-hall-of-nine-banners',
    npcIds: [
      'npc-corvin-vell',
      'npc-ysolde-vell',
      'npc-tamsin-vell',
      'npc-the-crown',
      'npc-courier-wren',
      'npc-halden-brack',
      'npc-dagna-rook',
    ],
    factionIds: [
      'faction-house-vell',
      'faction-ember-wardens',
      'faction-border-lords',
      'faction-unquenched',
    ],
    encounterIds: [
      'encounter-cinder-wights-dais',
      'encounter-heirs-audience',
      'encounter-witness-clause',
    ],
    questIds: [
      'quest-who-wears-the-crown',
      'quest-trace-the-cinder-assassins',
      'quest-border-lords-ultimatum',
    ],
    handoutIds: [
      'handout-coronation-program',
      'handout-crown-voice-transcript',
      'handout-heir-relationship-cards',
      'handout-proclamation-of-mourning',
      'lore-crowns-verses',
    ],
    sceneTemplateId: 'scene-hall-of-nine-banners',
    notes:
      'Session 1 primary setting and the session 6 finale; keep the map so the burn scars from session 1 can reappear. Ballroom hazard map reviewed; the banners double as a three-round fire clock.',
  },
  {
    id: 'location-queens-chambers',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'The Queen’s Chambers',
    type: 'landmark',
    shortDescription:
      'The sealed apartments where Queen Maren died, kept exactly as she left them.',
    description: [
      'A tall bedchamber with a window facing the mountain. The bed has been stripped but the curtains still smell of lavender and woodsmoke. The queen’s embroidery frame stands by the hearth, half-finished: a banner with a tenth flame she never stitched.',
      'Everything here has been touched by someone. A Warden stands outside the door, the Watch has posted a second guard, and a servant is paid to sweep the room each morning and report who has asked about it.',
      'A scorched silver cup sits on the nightstand where the physician asked for it to be removed. It is back, and nobody will say who returned it.',
    ],
    tags: ['Mystery', 'Session 3', 'Sealed room'],
    parentLocationId: 'location-palace-hill',
    mapId: MAP,
    npcIds: ['npc-maren-vell', 'npc-tamsin-vell'],
    factionIds: ['faction-house-vell', 'faction-ember-wardens'],
    encounterIds: ['encounter-queens-chambers-inquest'],
    questIds: ['quest-queens-last-night'],
    handoutIds: ['handout-physicians-report'],
    notes:
      'Unrun. Without Tamsin’s help the party must bluff or bribe past two guards who each report to a different heir.',
  },
  {
    id: 'location-crown-vault',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'The Crown Vault',
    type: 'landmark',
    shortDescription:
      'A sealed chamber under the palace where the crown rests between coronations.',
    description: [
      'A round room lined with obsidian mirrors. The crown’s pedestal is scorched in a ring, nine layers deep.',
      'A stair on the far side leads down to an archive the Wardens have never admitted to opening.',
      'The mirrors do not show the party. They show the rulers the crown has burned, each standing exactly where the viewer stands. The effect is unsettling rather than dangerous, but anyone who speaks a name aloud makes the nearest mirror answer.',
    ],
    tags: ['Vault', 'Session 4', 'Archive'],
    parentLocationId: 'location-palace-hill',
    mapId: MAP,
    pinId: 'pin-crown-vault',
    npcIds: ['npc-the-crown', 'npc-tamsin-vell', 'npc-quillon-thrum'],
    factionIds: ['faction-ember-wardens', 'faction-house-vell'],
    encounterIds: ['encounter-vault-guardians'],
    questIds: ['quest-crown-remembers', 'quest-queens-last-night'],
    handoutIds: [
      'lore-burned-rulers-roll',
      'lore-crowns-verses',
      'lore-history-of-the-crown',
    ],
    sceneTemplateId: 'scene-crown-vault-template',
    notes:
      'Unrun. The guardians can be disarmed if the crown is asked the right question.',
  },
  {
    id: 'location-ember-cloister',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'The Ember Cloister',
    type: 'landmark',
    shortDescription:
      'The Wardens’ stone fortress-monastery on the palace hill.',
    description: [
      'Sworn brothers and sisters tend perpetual braziers in the cloister court. Novices sweep the same ash every dawn.',
      'The lower levels connect to older cellars nobody explains.',
      'The kitchens, warm and noisy, are the Cloister’s one honest room. Cooks and novices gossip freely there, and Ivo’s old crew once stole bread from this exact door. Marshal Brack’s study sits two floors above, overlooking the court, and the archive stairs begin behind a linen store whose lock is suspiciously new.',
    ],
    tags: ['Warden order', 'Fortress', 'Archive'],
    parentLocationId: 'location-palace-hill',
    mapId: MAP,
    pinId: 'pin-ember-cloister',
    npcIds: [
      'npc-halden-brack',
      'npc-tamsin-vell',
      'npc-corvin-vell',
      'npc-quillon-thrum',
    ],
    factionIds: ['faction-ember-wardens', 'faction-unquenched'],
    encounterIds: [],
    questIds: ['quest-crown-remembers', 'quest-who-wears-the-crown'],
    handoutIds: ['handout-tamsin-note', 'lore-warden-founding-oath'],
    notes:
      'Unrun. The archive contains a scratched three-flame mark that matches the Unquenched brand.',
  },
  {
    id: 'location-royal-mausoleum',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'The Vellgrave Mausoleum',
    type: 'landmark',
    shortDescription:
      'The royal crypt at the foot of the hill, where an infant prince is supposedly buried.',
    description: [
      'A long hall of black stone arches, each sheltering a sarcophagus carved with its occupant’s banner. The newest, the queen’s, still smells of fresh lime and incense.',
      'Under the east arch is a tiny sarcophagus: Aurel, firstborn, eleven days old. The stone is as clean as the day it was laid, and none of the keeper’s moss has been permitted to grow on it.',
      'Ash seeps up through the floor in thin streams. The keeper claims it is a settling crack; the Wardens say it is blessed. It is neither.',
    ],
    tags: ['Crypt', 'Session 4', 'Undead', 'Reveal'],
    parentLocationId: 'location-ashgate',
    mapId: MAP,
    npcIds: ['npc-aurel-claimant', 'npc-maren-vell'],
    factionIds: ['faction-house-vell', 'faction-ember-wardens'],
    encounterIds: ['encounter-mausoleum-vigil'],
    questIds: ['quest-dead-princes-genealogy'],
    handoutIds: ['handout-mausoleum-register'],
    notes:
      'Unrun. This is where the genealogy’s seal story turns: the coffin is empty. Hold back the claimant until the party has seen the evidence.',
  },
  {
    id: 'location-gilded-exchange',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'The Gilded Exchange',
    type: 'market',
    shortDescription:
      'The counting-house market where the realm’s debts are traded.',
    description: [
      'Brass-railed floors, chalkboards of rates, and clerks who never look up.',
      'A private gallery above the floor is where Oswin Pell does his real business.',
      'The Exchange keeps the realm’s memory in numbers. Every promise to every heir, every loan against every banner, every tax farmed out in the last forty years is written on a slate somewhere in the building, and at least one clerk will sell the key to the wrong slate for the right price.',
    ],
    tags: ['Market', 'Finance', 'Session 3'],
    parentLocationId: 'location-ashgate',
    mapId: MAP,
    pinId: 'pin-gilded-exchange',
    npcIds: ['npc-oswin-pell', 'npc-ysolde-vell'],
    factionIds: ['faction-gilded-ledger'],
    encounterIds: [],
    questIds: [
      'quest-who-wears-the-crown',
      'quest-dead-princes-genealogy',
      'quest-border-lords-ultimatum',
      'quest-ink-without-blood',
    ],
    handoutIds: [
      'handout-sealed-genealogy',
      'handout-pell-ledger-excerpt',
      'handout-ysolde-letter',
    ],
    notes: 'Unrun. Pell offers a contract for each faction the party visits.',
  },
  {
    id: 'location-marchwarden-house',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'Marchwarden House',
    type: 'government',
    shortDescription:
      'The frontier lords’ embassy in the capital, a squat stone lodge that looks more like a fort than a house.',
    description: [
      'Built a hundred years ago as a symbol of the border’s loyalty, Marchwarden House has grown into its opposite: a garrison of tough veterans who drink in the capital’s taverns and say little about what they are guarding.',
      'The great hall is bare by court standards: long tables, a war map nailed to the wall, and a hearth nobody lets go out. Marchwarden Rook holds court at the head table with her back to the map.',
      'A banner of the Marcher Lords hangs by the door, a plain brown field with a single iron spike. It is the only banner in Ashgate not draped in black.',
    ],
    tags: ['Embassy', 'Session 3', 'Border lords'],
    parentLocationId: 'location-ashgate',
    mapId: MAP,
    npcIds: ['npc-dagna-rook'],
    factionIds: ['faction-border-lords', 'faction-house-vell'],
    encounterIds: ['encounter-border-lords-parley'],
    questIds: ['quest-border-lords-ultimatum'],
    handoutIds: ['handout-marchwarden-writ', 'handout-corvin-dispatch'],
    notes:
      'Unrun. Treat the House as a pressure gauge: each day the party delays, more veterans are quartered in the capital.',
  },
  {
    id: 'location-lamplighters-row',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'Lamplighters’ Row',
    type: 'street',
    shortDescription:
      'A crooked lane of soot-stained workshops where the Soot Hands keep their code, their ladders and their grudges.',
    description: [
      'Every house on the Row has a lamp bracket by the door, and every bracket holds a lamp. In the evening they are lit in sequence, and anyone who knows the code can read the street’s news in the flicker.',
      'During the mourning the lamps burn black-glassed, dim and unreadable. The Row is suspiciously quiet. Windows are shuttered, children kept indoors, and there is a Watch checkpoint at the corner that nobody on the Row will speak to.',
      'The guild’s apprentices sleep in the roofspaces and watch the street. They saw who tapped out the old code on the night before the coronation, but they will tell only Ivo, and only if he asks as one of their own.',
    ],
    tags: ['Street', 'Soot Hands', 'Session 2', 'Witnesses'],
    parentLocationId: 'location-ashgate',
    mapId: MAP,
    npcIds: ['npc-sera-lampwright', 'npc-vessa-thornscale'],
    factionIds: ['faction-soot-hands', 'faction-ashgate-watch'],
    encounterIds: [],
    questIds: [
      'quest-trace-the-cinder-assassins',
      'quest-keep-ashgate-from-burning',
    ],
    handoutIds: ['handout-flame-signal-sketch'],
    notes:
      'Unrun. A good connective scene between the Candle and the quay; Sera is the party’s way into the guild without paying Nell’s price.',
  },
  {
    id: 'location-guttered-candle',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'The Guttered Candle',
    type: 'tavern',
    shortDescription:
      'A smoky cellar tavern favoured by lamplighters and thieves.',
    description: [
      'The signboard is a candle with the flame snuffed. Every table has a lamp, and every lamp is a code.',
      'The cellar below is where the Soot Hands trade favours.',
      'The landlord pours with one hand and signals with the other. Regulars know that a lamp turned down on a table means a private conversation, and a lamp turned fully out means leave now. The cellar is reached by a stair behind the bar that creaks on the fourth step, a fact the guild has been using for years.',
    ],
    tags: ['Tavern', 'Soot Hands', 'Session 2'],
    parentLocationId: 'location-lamplighters-row',
    mapId: MAP,
    pinId: 'pin-guttered-candle',
    npcIds: ['npc-nell-soot', 'npc-sera-lampwright'],
    factionIds: ['faction-soot-hands'],
    encounterIds: ['encounter-guttered-candle-brawl'],
    questIds: ['quest-trace-the-cinder-assassins'],
    handoutIds: ['handout-flame-signal-sketch'],
    sceneTemplateId: 'scene-guttered-candle-cellar',
    notes:
      'Session 2 anchor. Ivo’s history with the crew makes this a soft entry.',
  },
  {
    id: 'location-ashwater-quay',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'Ashwater Quay',
    type: 'pier',
    shortDescription:
      'A grey-water pier where ferries carry ash barges out to the tidal flats.',
    description: [
      'The barges leave at dusk, low with cooled cinders. Ferrymen speak in murmurs.',
      'The genealogy courier was last seen boarding here.',
      'The tide leaves the flats a grey paste that looks solid and is not. Smugglers know three safe lines across it, and the Soot Hands know a fourth. A fisherman near the end of the pier claims to have seen a man arrive by barge on the night before the coronation, wearing a Warden’s cloak with the badge torn off.',
    ],
    tags: ['Pier', 'Barges', 'Smuggling'],
    parentLocationId: 'location-ashgate',
    mapId: MAP,
    pinId: 'pin-ashwater-quay',
    npcIds: [
      'npc-nell-soot',
      'npc-courier-wren',
      'npc-aurel-claimant',
    ],
    factionIds: ['faction-soot-hands'],
    encounterIds: ['encounter-ashwater-chase'],
    questIds: [
      'quest-trace-the-cinder-assassins',
      'quest-dead-princes-genealogy',
      'quest-ink-without-blood',
    ],
    handoutIds: ['handout-flame-signal-sketch'],
    notes: 'Unrun. Good location for a chase if session 2 goes quickly.',
  },
  {
    id: 'location-inkwell-court',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'Inkwell Court',
    type: 'district',
    shortDescription:
      'A cramped courtyard of scriveners, binders and forgers where documents are made, mended and made to lie.',
    description: [
      'The Court is a shared yard with six workshops and one well. Each workshop hangs a different coloured ribbon over its door, and the colours are the only advertising the trade needs.',
      'The air smells of oak-gall, gum arabic and burnt wax. Ferrant Inkwell’s shop is the one with the blue ribbon, a narrow door and a rafter full of watchful ravens.',
      'Every apprentice here knows which documents the Watch has asked about this month, and for the right coin they will say who else came asking.',
    ],
    tags: ['Forgers', 'Session 3', 'Documents'],
    parentLocationId: 'location-ashgate',
    mapId: MAP,
    npcIds: ['npc-ferrant-inkwell'],
    factionIds: ['faction-soot-hands', 'faction-gilded-ledger'],
    encounterIds: ['encounter-forgers-den'],
    questIds: ['quest-ink-without-blood', 'quest-dead-princes-genealogy'],
    handoutIds: ['handout-forgers-receipt'],
    notes:
      'Unrun. Ferrant folds quickly under pressure from the Watch and slowly under pressure from the party; make the party work for the commission book.',
  },
  {
    id: 'location-ashen-catacombs',
    campaignId: CROWN_CAMPAIGN_ID,
    name: 'The Ashen Catacombs',
    type: 'landmark',
    shortDescription:
      'Cooled lava tubes beneath the Cloister where the Unquenched hold their rites.',
    description: [
      'The walls glitter with black glass. The air tastes of struck flint.',
      'A rite pit glows at the centre of the largest chamber, ringed with branded cultists.',
      'The tubes connect the Cloister cellars to the sea caves under Ashwater Quay, which is how the Unquenched have moved people and fuel unseen for years. A side passage, partly collapsed, leads to the old Warden ossuary.',
    ],
    tags: ['Dungeon', 'Unquenched', 'Session 5'],
    parentLocationId: 'location-ember-cloister',
    mapId: MAP,
    pinId: 'pin-ashen-catacombs',
    npcIds: ['npc-mother-cinder'],
    factionIds: ['faction-unquenched'],
    encounterIds: ['encounter-catacomb-ashbound'],
    questIds: ['quest-trace-the-cinder-assassins'],
    handoutIds: ['lore-unquenched-creed'],
    notes:
      'Unrun. The party should reach it only after the paymaster trail has been followed.',
  },
];
