import type { CampaignQuest, QuestObjective } from '../ashes-of-veyra/types';
import { CROWN_CAMPAIGN_ID, crownSessionId } from './campaign';

export const crownQuests: CampaignQuest[] = [
  {
    id: 'quest-who-wears-the-crown',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Who Wears the Crown',
    status: 'not-started',
    priority: 'high',
    summary:
      'Weigh the three heirs’ claims, learn which of their lies touches the assassination, and decide who receives the crown.',
    giverNpcId: 'npc-the-crown',
    factionIds: [
      'faction-house-vell',
      'faction-gilded-ledger',
      'faction-ember-wardens',
    ],
    sessionIds: [crownSessionId(1), crownSessionId(3), crownSessionId(6)],
    locationIds: [
      'location-hall-of-nine-banners',
      'location-gilded-exchange',
      'location-ember-cloister',
    ],
    objectiveIds: [
      'objective-hear-the-heirs',
      'objective-find-the-lie',
      'objective-name-the-bearer',
    ],
  },
  {
    id: 'quest-trace-the-cinder-assassins',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Trace the Cinder Assassins',
    status: 'not-started',
    priority: 'high',
    summary:
      'Follow the brand on the cinder wights and the stolen guild flame signal to whoever paid for the attack.',
    giverNpcId: 'npc-halden-brack',
    factionIds: [
      'faction-ember-wardens',
      'faction-soot-hands',
      'faction-unquenched',
    ],
    sessionIds: [crownSessionId(1), crownSessionId(2), crownSessionId(5)],
    locationIds: [
      'location-hall-of-nine-banners',
      'location-guttered-candle',
      'location-ashen-catacombs',
    ],
    objectiveIds: [
      'objective-read-the-brand',
      'objective-follow-the-flame',
      'objective-find-the-paymaster',
    ],
  },
  {
    id: 'quest-dead-princes-genealogy',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Dead Prince’s Genealogy',
    status: 'not-started',
    priority: 'medium',
    summary:
      'Authenticate the sealed genealogy naming a dead prince and learn whether a fourth claimant can exist.',
    giverNpcId: 'npc-courier-wren',
    factionIds: ['faction-house-vell', 'faction-gilded-ledger'],
    sessionIds: [crownSessionId(1), crownSessionId(3), crownSessionId(4)],
    locationIds: ['location-ashwater-quay', 'location-gilded-exchange'],
    objectiveIds: [
      'objective-authenticate-genealogy',
      'objective-find-aurels-grave',
    ],
  },
  {
    id: 'quest-crown-remembers',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'What the Crown Remembers',
    status: 'not-started',
    priority: 'low',
    summary:
      'Learn the names of the rulers the crown has burned and why the Wardens sealed the record.',
    giverNpcId: 'npc-tamsin-vell',
    factionIds: ['faction-ember-wardens', 'faction-unquenched'],
    sessionIds: [crownSessionId(4), crownSessionId(5), crownSessionId(6)],
    locationIds: ['location-crown-vault', 'location-ember-cloister'],
    objectiveIds: [
      'objective-learn-the-burned-names',
      'objective-open-the-vault-archive',
    ],
  },
];

export const crownObjectives: QuestObjective[] = [
  {
    id: 'objective-hear-the-heirs',
    questId: 'quest-who-wears-the-crown',
    order: 1,
    title: 'Hear each heir’s claim before the ceremony ends',
    status: 'pending',
    clueIds: ['clue-heirs-contradictions'],
    locationIds: ['location-hall-of-nine-banners'],
  },
  {
    id: 'objective-find-the-lie',
    questId: 'quest-who-wears-the-crown',
    order: 2,
    title: 'Learn which heir’s lie concerns the assassination',
    status: 'pending',
    clueIds: ['clue-heirs-contradictions', 'clue-unquenched-brand'],
    locationIds: ['location-gilded-exchange', 'location-ember-cloister'],
  },
  {
    id: 'objective-name-the-bearer',
    questId: 'quest-who-wears-the-crown',
    order: 3,
    title: 'Decide who receives the crown',
    status: 'blocked',
    clueIds: [],
    locationIds: ['location-hall-of-nine-banners'],
  },
  {
    id: 'objective-read-the-brand',
    questId: 'quest-trace-the-cinder-assassins',
    order: 1,
    title: 'Examine the brand on the fallen cinder wights',
    status: 'pending',
    clueIds: ['clue-unquenched-brand'],
    locationIds: ['location-hall-of-nine-banners'],
  },
  {
    id: 'objective-follow-the-flame',
    questId: 'quest-trace-the-cinder-assassins',
    order: 2,
    title: 'Follow the guild flame signal into the Ashgate underworld',
    status: 'pending',
    clueIds: ['clue-flame-signal'],
    locationIds: ['location-guttered-candle', 'location-ashwater-quay'],
  },
  {
    id: 'objective-find-the-paymaster',
    questId: 'quest-trace-the-cinder-assassins',
    order: 3,
    title: 'Find who paid the Unquenched to strike at the investiture',
    status: 'blocked',
    clueIds: ['clue-unquenched-brand'],
    locationIds: ['location-ashen-catacombs'],
  },
  {
    id: 'objective-authenticate-genealogy',
    questId: 'quest-dead-princes-genealogy',
    order: 1,
    title: 'Authenticate the seal on the sealed genealogy',
    status: 'pending',
    clueIds: ['clue-dead-prince-seal'],
    locationIds: ['location-gilded-exchange'],
  },
  {
    id: 'objective-find-aurels-grave',
    questId: 'quest-dead-princes-genealogy',
    order: 2,
    title: 'Find where Prince Aurel was actually buried',
    status: 'blocked',
    clueIds: ['clue-dead-prince-seal'],
    locationIds: ['location-ashwater-quay', 'location-ember-cloister'],
  },
  {
    id: 'objective-learn-the-burned-names',
    questId: 'quest-crown-remembers',
    order: 1,
    title: 'Learn the names on the crown’s burn list',
    status: 'pending',
    clueIds: ['clue-burn-list'],
    locationIds: ['location-crown-vault'],
  },
  {
    id: 'objective-open-the-vault-archive',
    questId: 'quest-crown-remembers',
    order: 2,
    title: 'Open the sealed archive beneath the Crown Vault',
    status: 'blocked',
    clueIds: ['clue-burn-list', 'clue-unquenched-brand'],
    locationIds: ['location-crown-vault', 'location-ember-cloister'],
  },
];
