import type { CampaignQuest, QuestObjective } from '../ashes-of-veyra/types';
import { CROWN_CAMPAIGN_ID, crownSessionId } from './campaign';

export const crownQuests: CampaignQuest[] = [
  {
    id: 'quest-who-wears-the-crown',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Who Wears the Crown',
    status: 'not-started',
    priority: 'high',
    summary:
      'Weigh the three heirs’ claims, learn which of their lies touches the assassination, and decide who receives the crown.',
    giverNpcId: 'npc-the-crown',
    factionIds: [
      'faction-house-vell',
      'faction-gilded-ledger',
      'faction-ember-wardens',
    ],
    sessionIds: [crownSessionId(1), crownSessionId(3), crownSessionId(6)],
    locationIds: [
      'location-hall-of-nine-banners',
      'location-gilded-exchange',
      'location-ember-cloister',
    ],
    objectiveIds: [
      'objective-hear-the-heirs',
      'objective-find-the-lie',
      'objective-name-the-bearer',
    ],
  },
  {
    id: 'quest-trace-the-cinder-assassins',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Trace the Cinder Assassins',
    status: 'not-started',
    priority: 'high',
    summary:
      'Follow the brand on the cinder wights and the stolen guild flame signal to whoever paid for the attack.',
    giverNpcId: 'npc-halden-brack',
    factionIds: [
      'faction-ember-wardens',
      'faction-soot-hands',
      'faction-unquenched',
    ],
    sessionIds: [crownSessionId(1), crownSessionId(2), crownSessionId(5)],
    locationIds: [
      'location-hall-of-nine-banners',
      'location-guttered-candle',
      'location-ashen-catacombs',
    ],
    objectiveIds: [
      'objective-read-the-brand',
      'objective-follow-the-flame',
      'objective-find-the-paymaster',
    ],
  },
  {
    id: 'quest-dead-princes-genealogy',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Dead Prince’s Genealogy',
    status: 'not-started',
    priority: 'medium',
    summary:
      'Authenticate the sealed genealogy naming a dead prince and learn whether a fourth claimant can exist.',
    giverNpcId: 'npc-courier-wren',
    factionIds: ['faction-house-vell', 'faction-gilded-ledger'],
    sessionIds: [crownSessionId(1), crownSessionId(3), crownSessionId(4)],
    locationIds: [
      'location-ashwater-quay',
      'location-gilded-exchange',
      'location-royal-mausoleum',
    ],
    objectiveIds: [
      'objective-authenticate-genealogy',
      'objective-find-aurels-grave',
    ],
  },
  {
    id: 'quest-crown-remembers',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'What the Crown Remembers',
    status: 'not-started',
    priority: 'low',
    summary:
      'Learn the names of the rulers the crown has burned and why the Wardens sealed the record.',
    giverNpcId: 'npc-tamsin-vell',
    factionIds: ['faction-ember-wardens', 'faction-unquenched'],
    sessionIds: [crownSessionId(4), crownSessionId(5), crownSessionId(6)],
    locationIds: ['location-crown-vault', 'location-ember-cloister'],
    objectiveIds: [
      'objective-learn-the-burned-names',
      'objective-open-the-vault-archive',
    ],
  },
  {
    id: 'quest-queens-last-night',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Queen’s Last Night',
    status: 'not-started',
    priority: 'high',
    summary:
      'Reconstruct the final hours of Queen Maren: who visited, what she told the crown, and why the physician’s report and the Wardens’ door log disagree about when she died.',
    giverNpcId: 'npc-the-crown',
    factionIds: ['faction-house-vell', 'faction-ember-wardens'],
    sessionIds: [crownSessionId(3), crownSessionId(4), crownSessionId(6)],
    locationIds: [
      'location-queens-chambers',
      'location-hall-of-nine-banners',
      'location-crown-vault',
    ],
    objectiveIds: [
      'objective-collect-the-testimonies',
      'objective-reconstruct-the-last-hour',
      'objective-ask-the-crown-the-right-question',
    ],
  },
  {
    id: 'quest-border-lords-ultimatum',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'The Marchers’ Ultimatum',
    status: 'not-started',
    priority: 'medium',
    summary:
      'Marchwarden Rook wants Corvin’s war debt honored before the crown is placed. Audit what is actually owed, and decide whether to carry her answer.',
    giverNpcId: 'npc-dagna-rook',
    factionIds: ['faction-border-lords', 'faction-house-vell'],
    sessionIds: [crownSessionId(3), crownSessionId(6)],
    locationIds: [
      'location-marchwarden-house',
      'location-gilded-exchange',
      'location-hall-of-nine-banners',
    ],
    objectiveIds: [
      'objective-meet-the-marchwarden',
      'objective-audit-corvins-debt',
      'objective-answer-the-ultimatum',
    ],
  },
  {
    id: 'quest-ink-without-blood',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Ink Without Blood',
    status: 'not-started',
    priority: 'medium',
    summary:
      'Ysolde wants the genealogy proved a forgery before a rival does the same to her. Find the scrivener who aged the ink and learn who commissioned it.',
    giverNpcId: 'npc-ysolde-vell',
    factionIds: [
      'faction-gilded-ledger',
      'faction-soot-hands',
      'faction-house-vell',
    ],
    sessionIds: [crownSessionId(2), crownSessionId(3)],
    locationIds: ['location-inkwell-court', 'location-ashwater-quay'],
    objectiveIds: [
      'objective-find-the-scriveners',
      'objective-compare-the-hands',
      'objective-name-the-commissioner',
    ],
  },
  {
    id: 'quest-keep-ashgate-from-burning',
    campaignId: CROWN_CAMPAIGN_ID,
    title: 'Keep Ashgate From Burning',
    status: 'not-started',
    priority: 'low',
    summary:
      'Captain Thornscale asks the party to cool the guild districts before rumor of the assassination becomes a riot, and to find which of her sergeants are selling the Watch’s patrol routes.',
    giverNpcId: 'npc-vessa-thornscale',
    factionIds: ['faction-ashgate-watch', 'faction-soot-hands'],
    sessionIds: [crownSessionId(2), crownSessionId(3), crownSessionId(5)],
    locationIds: ['location-lamplighters-row', 'location-palace-hill'],
    objectiveIds: [
      'objective-calm-the-rows',
      'objective-find-the-bought-sergeants',
      'objective-hold-the-curfew',
    ],
  },
];

export const crownObjectives: QuestObjective[] = [
  {
    id: 'objective-hear-the-heirs',
    questId: 'quest-who-wears-the-crown',
    order: 1,
    title: 'Hear each heir’s claim before the ceremony ends',
    status: 'pending',
    clueIds: ['clue-heirs-contradictions'],
    locationIds: ['location-hall-of-nine-banners'],
  },
  {
    id: 'objective-find-the-lie',
    questId: 'quest-who-wears-the-crown',
    order: 2,
    title: 'Learn which heir’s lie concerns the assassination',
    status: 'pending',
    clueIds: ['clue-heirs-contradictions', 'clue-unquenched-brand'],
    locationIds: ['location-gilded-exchange', 'location-ember-cloister'],
  },
  {
    id: 'objective-name-the-bearer',
    questId: 'quest-who-wears-the-crown',
    order: 3,
    title: 'Decide who receives the crown',
    status: 'blocked',
    clueIds: [],
    locationIds: ['location-hall-of-nine-banners'],
  },
  {
    id: 'objective-read-the-brand',
    questId: 'quest-trace-the-cinder-assassins',
    order: 1,
    title: 'Examine the brand on the fallen cinder wights',
    status: 'pending',
    clueIds: ['clue-unquenched-brand'],
    locationIds: ['location-hall-of-nine-banners'],
  },
  {
    id: 'objective-follow-the-flame',
    questId: 'quest-trace-the-cinder-assassins',
    order: 2,
    title: 'Follow the guild flame signal into the Ashgate underworld',
    status: 'pending',
    clueIds: ['clue-flame-signal'],
    locationIds: ['location-guttered-candle', 'location-ashwater-quay'],
  },
  {
    id: 'objective-find-the-paymaster',
    questId: 'quest-trace-the-cinder-assassins',
    order: 3,
    title: 'Find who paid the Unquenched to strike at the investiture',
    status: 'blocked',
    clueIds: ['clue-unquenched-brand'],
    locationIds: ['location-ashen-catacombs'],
  },
  {
    id: 'objective-authenticate-genealogy',
    questId: 'quest-dead-princes-genealogy',
    order: 1,
    title: 'Authenticate the seal on the sealed genealogy',
    status: 'pending',
    clueIds: ['clue-dead-prince-seal'],
    locationIds: ['location-gilded-exchange'],
  },
  {
    id: 'objective-find-aurels-grave',
    questId: 'quest-dead-princes-genealogy',
    order: 2,
    title: 'Find where Prince Aurel was actually buried',
    status: 'blocked',
    clueIds: ['clue-dead-prince-seal', 'clue-empty-coffin'],
    locationIds: [
      'location-ashwater-quay',
      'location-ember-cloister',
      'location-royal-mausoleum',
    ],
  },
  {
    id: 'objective-learn-the-burned-names',
    questId: 'quest-crown-remembers',
    order: 1,
    title: 'Learn the names on the crown’s burn list',
    status: 'pending',
    clueIds: ['clue-burn-list'],
    locationIds: ['location-crown-vault'],
  },
  {
    id: 'objective-open-the-vault-archive',
    questId: 'quest-crown-remembers',
    order: 2,
    title: 'Open the sealed archive beneath the Crown Vault',
    status: 'blocked',
    clueIds: ['clue-burn-list', 'clue-unquenched-brand'],
    locationIds: ['location-crown-vault', 'location-ember-cloister'],
  },
  {
    id: 'objective-collect-the-testimonies',
    questId: 'quest-queens-last-night',
    order: 1,
    title: 'Collect testimony from the physician, chambermaids and door-guard',
    status: 'pending',
    clueIds: ['clue-queens-last-night'],
    locationIds: ['location-queens-chambers'],
  },
  {
    id: 'objective-reconstruct-the-last-hour',
    questId: 'quest-queens-last-night',
    order: 2,
    title: 'Reconcile the physician’s report with the Wardens’ door log',
    status: 'pending',
    clueIds: ['clue-queens-last-night', 'clue-heirs-contradictions'],
    locationIds: ['location-queens-chambers', 'location-ember-cloister'],
  },
  {
    id: 'objective-ask-the-crown-the-right-question',
    questId: 'quest-queens-last-night',
    order: 3,
    title: 'Ask the crown what the queen told it before she died',
    status: 'blocked',
    clueIds: ['clue-burn-list'],
    locationIds: ['location-crown-vault', 'location-hall-of-nine-banners'],
  },
  {
    id: 'objective-meet-the-marchwarden',
    questId: 'quest-border-lords-ultimatum',
    order: 1,
    title: 'Hear Marchwarden Rook’s terms at Marchwarden House',
    status: 'pending',
    clueIds: ['clue-corvin-war-writ'],
    locationIds: ['location-marchwarden-house'],
  },
  {
    id: 'objective-audit-corvins-debt',
    questId: 'quest-border-lords-ultimatum',
    order: 2,
    title: 'Audit what Corvin actually owes, and to whom',
    status: 'pending',
    clueIds: ['clue-corvin-war-writ', 'clue-pells-marginalia'],
    locationIds: ['location-gilded-exchange'],
  },
  {
    id: 'objective-answer-the-ultimatum',
    questId: 'quest-border-lords-ultimatum',
    order: 3,
    title: 'Carry an answer back before the Presentation of the Crown',
    status: 'blocked',
    clueIds: [],
    locationIds: ['location-hall-of-nine-banners'],
  },
  {
    id: 'objective-find-the-scriveners',
    questId: 'quest-ink-without-blood',
    order: 1,
    title: 'Find which Inkwell Court scrivener aged the genealogy’s ink',
    status: 'pending',
    clueIds: ['clue-forgers-ink'],
    locationIds: ['location-inkwell-court'],
  },
  {
    id: 'objective-compare-the-hands',
    questId: 'quest-ink-without-blood',
    order: 2,
    title: 'Compare the genealogy’s handwriting to the queen’s letters',
    status: 'pending',
    clueIds: ['clue-forgers-ink', 'clue-dead-prince-seal'],
    locationIds: ['location-inkwell-court', 'location-ashwater-quay'],
  },
  {
    id: 'objective-name-the-commissioner',
    questId: 'quest-ink-without-blood',
    order: 3,
    title: 'Learn who commissioned the work and paid in advance',
    status: 'blocked',
    clueIds: ['clue-pells-marginalia'],
    locationIds: ['location-gilded-exchange'],
  },
  {
    id: 'objective-calm-the-rows',
    questId: 'quest-keep-ashgate-from-burning',
    order: 1,
    title: 'Calm the lamplighters before the Row marches on the palace',
    status: 'pending',
    clueIds: ['clue-flame-signal'],
    locationIds: ['location-lamplighters-row'],
  },
  {
    id: 'objective-find-the-bought-sergeants',
    questId: 'quest-keep-ashgate-from-burning',
    order: 2,
    title: 'Identify the Watch sergeants selling patrol routes',
    status: 'pending',
    clueIds: ['clue-pells-marginalia'],
    locationIds: ['location-palace-hill', 'location-lamplighters-row'],
  },
  {
    id: 'objective-hold-the-curfew',
    questId: 'quest-keep-ashgate-from-burning',
    order: 3,
    title: 'Hold the coronation-week curfew without a massacre',
    status: 'blocked',
    clueIds: [],
    locationIds: ['location-palace-hill'],
  },
];
