import type {
  CampaignSession,
  SessionPlan,
  SessionPlanStep,
} from '../ashes-of-veyra/types';
import { CROWN_CAMPAIGN_ID, crownSessionId } from './campaign';

const ACT_1 = `${CROWN_CAMPAIGN_ID}-act-1`;
const ACT_2 = `${CROWN_CAMPAIGN_ID}-act-2`;
const ACT_3 = `${CROWN_CAMPAIGN_ID}-act-3`;

const PLAN_PREFIX = `${CROWN_CAMPAIGN_ID}-session-1`;

// Steps 1-4 keep the ids, titles and bodies from the catalog entry
// (campaign-catalog/catalog.ts). Steps 5+ are added parallel threads.
const session1StepInputs: Omit<SessionPlanStep, 'id' | 'order'>[] = [
  {
    kind: 'scene',
    track: 'main',
    title: 'The Hall of Nine Banners',
    durationMinutes: 25,
    visibility: 'shared',
    objectId: 'scene-hall-of-nine-banners',
    body: 'Let each character meet an heir and hear one contradictory rumor before the ceremony begins.',
  },
  {
    kind: 'encounter',
    track: 'main',
    title: 'Cinder wights breach the dais',
    durationMinutes: 55,
    visibility: 'dm-only',
    objectId: 'encounter-cinder-wights-dais',
    body: 'Wights ignite curtains to split the room; rescuing guests matters more than defeating every attacker.',
  },
  {
    kind: 'choice',
    track: 'main',
    title: 'Choose which heir receives the crown',
    durationMinutes: 30,
    visibility: 'shared',
    body: 'The crown whispers that all three heirs are lying, but only one lie concerns the assassination.',
  },
  {
    kind: 'closing',
    track: 'main',
    title: 'A fourth claimant arrives',
    durationMinutes: 10,
    visibility: 'shared',
    objectId: 'handout-sealed-genealogy',
    body: 'End as an ash-streaked courier presents a sealed genealogy naming a dead prince.',
  },
  {
    kind: 'note',
    track: 'parallel',
    title: 'Note: The three heirs',
    durationMinutes: 0,
    visibility: 'dm-only',
    objectId: 'handout-heir-relationship-cards',
    body: 'Keep the three heirs sympathetic. Corvin wants swords, Ysolde wants discretion, Tamsin wants trust. Reveal lies only when the party asks the right question.',
  },
  {
    kind: 'encounter',
    track: 'parallel',
    title: 'Optional: Audience with the Heirs',
    durationMinutes: 15,
    visibility: 'dm-only',
    objectId: 'encounter-heirs-audience',
    body: 'Use if the party wants a private word with an heir before the wights arrive. Skip if pacing is tight.',
  },
  {
    kind: 'handout',
    track: 'parallel',
    title: 'Share handout: Coronation Program',
    durationMinutes: 3,
    visibility: 'shared',
    objectId: 'handout-coronation-program',
    body: 'Hand it out as the ceremony begins. The pencilled gossip seeds the three contradictory rumors.',
  },
  {
    kind: 'handout',
    track: 'parallel',
    title: 'Share handout: The Crown Speaks',
    durationMinutes: 2,
    visibility: 'shared',
    objectId: 'handout-crown-voice-transcript',
    body: 'Read it aloud in the recorded crown voice once the recording is ready; otherwise read in a low, dry whisper.',
  },
  {
    kind: 'note',
    track: 'parallel',
    title: 'Quest: Trace the Cinder Assassins',
    durationMinutes: 0,
    visibility: 'dm-only',
    body: 'Seed the flame signal only if Ivo’s player asks about it. The brand under the wights’ collarbones is the physical clue.',
  },
  {
    kind: 'handout',
    track: 'parallel',
    title: 'Share handout: Proclamation of Mourning',
    durationMinutes: 2,
    visibility: 'shared',
    objectId: 'handout-proclamation-of-mourning',
    body: 'Pin it to the table before the first scene so the forty days of ash, the lamplighters in black and the Law of Succession are common knowledge.',
  },
  {
    kind: 'handout',
    track: 'parallel',
    title: 'After the fire: heir letters',
    durationMinutes: 5,
    visibility: 'shared',
    objectId: 'handout-ysolde-letter',
    body: 'Hand each player the letter from the heir who spoke with their character: Ysolde’s perfumed offer, Corvin’s field dispatch, Tamsin’s note on Cloister vellum. Each letter makes a different ask and none lies about what it wants.',
  },
  {
    kind: 'note',
    track: 'parallel',
    title: 'Note: The crown’s voice',
    durationMinutes: 0,
    visibility: 'dm-only',
    objectId: 'lore-crowns-verses',
    body: 'Use the first three verses only. The crown is warm, curious and unforgiving; it never says which heir’s lie matters and it never lies itself.',
  },
  {
    kind: 'note',
    track: 'parallel',
    title: 'Note: Court gossip table',
    durationMinutes: 0,
    visibility: 'dm-only',
    objectId: 'lore-court-gossip',
    body: 'Roll for a rumor whenever the party asks around. Half of the table is true; mark which ones you have used so they reappear in session 3 with consequences.',
  },
];

export const crownSession1Plan: SessionPlan = {
  revision: 1,
  lastEdited: '20 minutes ago',
  estimatedMinutes: session1StepInputs.reduce(
    (total, step) => total + step.durationMinutes,
    0,
  ),
  readiness: [
    {
      id: `${PLAN_PREFIX}-ready-1`,
      label: 'Heir relationship cards written',
      complete: true,
    },
    {
      id: `${PLAN_PREFIX}-ready-2`,
      label: 'Ballroom hazard map reviewed',
      complete: true,
    },
    {
      id: `${PLAN_PREFIX}-ready-3`,
      label: 'Crown voice handout recorded',
      complete: false,
    },
    {
      id: `${PLAN_PREFIX}-ready-4`,
      label: 'Cinder wight stat block playtested',
      complete: false,
    },
    {
      id: `${PLAN_PREFIX}-ready-5`,
      label: 'Player-facing summary written',
      complete: false,
    },
    {
      id: `${PLAN_PREFIX}-ready-6`,
      label: 'Closing beat checked',
      complete: false,
    },
    {
      id: `${PLAN_PREFIX}-ready-7`,
      label: 'Proclamation and heir letters printed',
      complete: true,
    },
    {
      id: `${PLAN_PREFIX}-ready-8`,
      label: 'Crown verses table marked for session 1',
      complete: false,
    },
    {
      id: `${PLAN_PREFIX}-ready-9`,
      label: 'Fire clock tokens and banner counters prepared',
      complete: false,
    },
  ],
  dependencies: [
    { objectId: 'scene-hall-of-nine-banners', status: 'ready' },
    { objectId: 'encounter-cinder-wights-dais', status: 'needs-review' },
    { objectId: 'handout-crown-voice-transcript', status: 'needs-review' },
    { objectId: 'handout-sealed-genealogy', status: 'ready' },
    { objectId: 'handout-proclamation-of-mourning', status: 'ready' },
    { objectId: 'handout-ysolde-letter', status: 'needs-review' },
    { objectId: 'lore-crowns-verses', status: 'needs-review' },
  ],
  steps: session1StepInputs.map((step, index) => ({
    ...step,
    id: `${PLAN_PREFIX}-step-${index + 1}`,
    order: index + 1,
  })),
  notes: [
    'Keep the three heirs sympathetic; this is a values choice, not a correct-answer puzzle.',
    'Use the burning tapestries as a visible three-round clock.',
    'Foreshadow the Cloister ash on the wights, but do not name it. The Wardens’ brazier ash is a session 2 reveal.',
    'Each heir should be caught in one small, forgivable lie in session 1 so the crown’s accusation lands as ambiguous rather than damning.',
  ],
  playerFacingSummary:
    'You came to witness a coronation. By nightfall, the realm may ask you to choose its ruler.',
  attachments: [
    'handout-coronation-program',
    'handout-crown-voice-transcript',
    'handout-sealed-genealogy',
    'lore-succession-law',
    'handout-proclamation-of-mourning',
    'handout-ysolde-letter',
    'handout-corvin-dispatch',
    'handout-tamsin-note',
  ],
};

const buildDraftPlan = (
  sessionNumber: number,
  options: Pick<
    SessionPlan,
    | 'lastEdited'
    | 'readiness'
    | 'dependencies'
    | 'notes'
    | 'playerFacingSummary'
    | 'attachments'
  > & { steps: Omit<SessionPlanStep, 'id' | 'order'>[] },
): SessionPlan => ({
  revision: 1,
  lastEdited: options.lastEdited,
  estimatedMinutes: options.steps.reduce(
    (total, step) => total + step.durationMinutes,
    0,
  ),
  readiness: options.readiness,
  dependencies: options.dependencies,
  steps: options.steps.map((step, index) => ({
    ...step,
    id: `${CROWN_CAMPAIGN_ID}-session-${sessionNumber}-step-${index + 1}`,
    order: index + 1,
  })),
  notes: options.notes,
  playerFacingSummary: options.playerFacingSummary,
  attachments: options.attachments,
});

export const crownSession2Plan: SessionPlan = buildDraftPlan(2, {
  lastEdited: '2 days ago',
  readiness: [
    {
      id: `${CROWN_CAMPAIGN_ID}-session-2-ready-1`,
      label: 'Guttered Candle cellar map drafted',
      complete: true,
    },
    {
      id: `${CROWN_CAMPAIGN_ID}-session-2-ready-2`,
      label: 'Nell Soot and Sera Lampwright voices decided',
      complete: false,
    },
    {
      id: `${CROWN_CAMPAIGN_ID}-session-2-ready-3`,
      label: 'Barge chase terrain sketched',
      complete: false,
    },
    {
      id: `${CROWN_CAMPAIGN_ID}-session-2-ready-4`,
      label: 'Flame signal code sheet ready for Ivo’s player',
      complete: false,
    },
  ],
  dependencies: [
    { objectId: 'scene-guttered-candle-cellar', status: 'ready' },
    { objectId: 'encounter-guttered-candle-brawl', status: 'needs-review' },
    { objectId: 'encounter-ashwater-chase', status: 'needs-review' },
    { objectId: 'handout-flame-signal-sketch', status: 'ready' },
  ],
  steps: [
    {
      kind: 'recap',
      track: 'main',
      title: 'Recap: the night after the fire',
      durationMinutes: 10,
      visibility: 'shared',
      body: 'Name what the party took from session 1: the brand, the letters and the courier’s sealed genealogy. Ask each player what their character did after the coronation.',
    },
    {
      kind: 'scene',
      track: 'main',
      title: 'Lamplighters’ Row after dark',
      durationMinutes: 25,
      visibility: 'shared',
      objectId: 'location-lamplighters-row',
      body: 'The lamps burn black-glassed and the Row is silent. Sera Lampwright finds Ivo before he finds anyone; she saw who tapped out the old code and will talk if he asks as one of her own.',
    },
    {
      kind: 'scene',
      track: 'main',
      title: 'The Guttered Candle cellar',
      durationMinutes: 40,
      visibility: 'shared',
      objectId: 'scene-guttered-candle-cellar',
      body: 'Nell Soot trades the guild’s story for a favor and a clean name. The signal sequence is a decade out of date; someone copied it from an old guild ledger.',
    },
    {
      kind: 'encounter',
      track: 'parallel',
      title: 'Optional: Brawl at the Guttered Candle',
      durationMinutes: 20,
      visibility: 'dm-only',
      objectId: 'encounter-guttered-candle-brawl',
      body: 'Use only if the party leans on Nell too hard. Defuse it with a favor or a good bluff and move straight to the quay.',
    },
    {
      kind: 'encounter',
      track: 'main',
      title: 'Chase across the ash barges',
      durationMinutes: 35,
      visibility: 'dm-only',
      objectId: 'encounter-ashwater-chase',
      body: 'The bandit carrying the courier’s stolen satchel runs for the tidal flats. Cinematic, not lethal; the satchel holds a second page of the genealogy.',
    },
    {
      kind: 'closing',
      track: 'main',
      title: 'Brack summons the party',
      durationMinutes: 10,
      visibility: 'shared',
      body: 'End as a Warden courier delivers Marshal Brack’s summons to the Cloister: the ash on the wights was not wild, and he wants to know who in the Cloister has been feeding the Unquenched.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Note: The Soot Hands are not the villains',
      durationMinutes: 0,
      visibility: 'dm-only',
      objectId: 'faction-soot-hands',
      body: 'The guild was framed. Their code is a decade old because the thief used an old ledger, which means the thief had access to guild records from before Nell’s time.',
    },
  ],
  notes: [
    'Nell Soot will not betray the guild, but she will trade the ledger’s hiding place for a clean name.',
    'If the party is fast, run Inkwell Court from session 3 here as a short side scene.',
  ],
  playerFacingSummary:
    'The wights’ fire was lit with a guild code, and the guild swears it was not them. The only people who can prove it live where the lamps never go out.',
  attachments: ['handout-flame-signal-sketch', 'handout-ysolde-letter'],
});

export const crownSession3Plan: SessionPlan = buildDraftPlan(3, {
  lastEdited: '3 days ago',
  readiness: [
    {
      id: `${CROWN_CAMPAIGN_ID}-session-3-ready-1`,
      label: 'Ledger, receipt and writ handouts printed',
      complete: false,
    },
    {
      id: `${CROWN_CAMPAIGN_ID}-session-3-ready-2`,
      label: 'Marchwarden parley skill-challenge DCs set',
      complete: false,
    },
    {
      id: `${CROWN_CAMPAIGN_ID}-session-3-ready-3`,
      label: 'Queen’s timeline reconciled with the Wardens’ log',
      complete: false,
    },
    {
      id: `${CROWN_CAMPAIGN_ID}-session-3-ready-4`,
      label: 'Pell’s three contracts outlined',
      complete: true,
    },
    {
      id: `${CROWN_CAMPAIGN_ID}-session-3-ready-5`,
      label: 'Inkwell Court map sketched',
      complete: false,
    },
  ],
  dependencies: [
    { objectId: 'encounter-border-lords-parley', status: 'needs-review' },
    { objectId: 'encounter-forgers-den', status: 'needs-review' },
    { objectId: 'encounter-queens-chambers-inquest', status: 'needs-review' },
    { objectId: 'handout-physicians-report', status: 'needs-review' },
    { objectId: 'handout-pell-ledger-excerpt', status: 'ready' },
  ],
  steps: [
    {
      kind: 'recap',
      track: 'main',
      title: 'Recap: what the guilds said',
      durationMinutes: 10,
      visibility: 'shared',
      body: 'Remind the table which heir courted whom and what each letter asked. Mention that the Marchers have moved a company within three days’ ride.',
    },
    {
      kind: 'scene',
      track: 'main',
      title: 'Pell’s private gallery',
      durationMinutes: 30,
      visibility: 'shared',
      objectId: 'location-gilded-exchange',
      body: 'Oswin Pell offers a contract for every faction the party has visited. Let the party find the torn ledger page by noticing who Pell does not mention.',
    },
    {
      kind: 'encounter',
      track: 'main',
      title: 'Parley at Marchwarden House',
      durationMinutes: 30,
      visibility: 'dm-only',
      objectId: 'encounter-border-lords-parley',
      body: 'A skill challenge disguised as a conversation. Rook opens by asking what the party wants for itself.',
    },
    {
      kind: 'encounter',
      track: 'main',
      title: 'Inquest in the Queen’s Chambers',
      durationMinutes: 30,
      visibility: 'dm-only',
      objectId: 'encounter-queens-chambers-inquest',
      body: 'Interview the physician, chambermaids and door-guard separately. The second bell versus third bell discrepancy is the thread to pull.',
    },
    {
      kind: 'encounter',
      track: 'parallel',
      title: 'Optional: The Forger’s Den',
      durationMinutes: 25,
      visibility: 'dm-only',
      objectId: 'encounter-forgers-den',
      body: 'Use if the party wants the commission book from Ferrant Inkwell. The spy’s escape route is the clock.',
    },
    {
      kind: 'choice',
      track: 'main',
      title: 'Which heir do you tell?',
      durationMinutes: 15,
      visibility: 'shared',
      body: 'The party now holds three heirs’ secrets. Whom they tell, and what they withhold, sets which heir trusts them in session 4.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'Share handout: Torn Page of Pell’s Ledger',
      durationMinutes: 3,
      visibility: 'shared',
      objectId: 'handout-pell-ledger-excerpt',
      body: 'Hand over once the party has noticed the missing pages. The “C.A.” line is the hook for the genealogy’s true commissioner.',
    },
  ],
  notes: [
    'Do not resolve who “C.A.” is. It can be Cinder Assassin, a cloister name, or the claimant; decide at the end of session 4.',
    'The Marchers’ ultimatum has a clock: Rook leaves the capital at the end of the week.',
  ],
  playerFacingSummary:
    'Every heir wants something and every faction has a price. The queen died at the second bell, or the third, and someone was paid in advance.',
  attachments: [
    'handout-pell-ledger-excerpt',
    'handout-forgers-receipt',
    'handout-marchwarden-writ',
    'handout-physicians-report',
  ],
});

const emptyLinks = {
  questIds: [] as string[],
  npcIds: [] as string[],
  factionIds: [] as string[],
  locationIds: [] as string[],
  encounterIds: [] as string[],
  clueIds: [] as string[],
  handoutIds: [] as string[],
};

export const crownSessions: CampaignSession[] = [
  {
    ...emptyLinks,
    id: crownSessionId(1),
    campaignId: CROWN_CAMPAIGN_ID,
    actId: ACT_1,
    number: 1,
    title: 'Embers at the Coronation',
    status: 'planned',
    summary:
      'A royal investiture erupts into an elemental assassination, leaving the party with a talking crown and three competing heirs. Open with private audiences, let the ceremony turn on the crown’s accusation, run the burning hall as a three-round clock, and close on a courier carrying a sealed genealogy for a dead prince.',
    plannedDate: '2026-10-03',
    durationHours: 3,
    partyLevel: 1,
    tags: ['Court intrigue', 'Mystery', 'Elemental hazard'],
    questIds: [
      'quest-who-wears-the-crown',
      'quest-trace-the-cinder-assassins',
      'quest-dead-princes-genealogy',
    ],
    npcIds: [
      'npc-corvin-vell',
      'npc-ysolde-vell',
      'npc-tamsin-vell',
      'npc-the-crown',
      'npc-halden-brack',
      'npc-courier-wren',
    ],
    factionIds: [
      'faction-house-vell',
      'faction-ember-wardens',
      'faction-unquenched',
    ],
    locationIds: ['location-hall-of-nine-banners'],
    encounterIds: [
      'encounter-cinder-wights-dais',
      'encounter-heirs-audience',
    ],
    clueIds: [
      'clue-heirs-contradictions',
      'clue-unquenched-brand',
      'clue-dead-prince-seal',
    ],
    handoutIds: [
      'handout-coronation-program',
      'handout-crown-voice-transcript',
      'handout-sealed-genealogy',
      'handout-heir-relationship-cards',
      'lore-succession-law',
      'handout-proclamation-of-mourning',
      'handout-ysolde-letter',
      'handout-corvin-dispatch',
      'handout-tamsin-note',
      'lore-crowns-verses',
      'lore-court-gossip',
    ],
    plan: crownSession1Plan,
  },
  {
    ...emptyLinks,
    id: crownSessionId(2),
    campaignId: CROWN_CAMPAIGN_ID,
    actId: ACT_1,
    number: 2,
    title: 'The Guttered Candle',
    status: 'draft',
    summary:
      'The party follows the stolen guild flame signal into the Ashgate underworld and meets Nell Soot. Lamplighters’ Row is silent, the guild swears it was framed, and the trail ends in a chase across the ash barges at Ashwater Quay, with Marshal Brack’s summons waiting at the close.',
    partyLevel: 1,
    tags: ['Urban', 'Investigation', 'Social'],
    questIds: [
      'quest-trace-the-cinder-assassins',
      'quest-ink-without-blood',
      'quest-keep-ashgate-from-burning',
    ],
    npcIds: [
      'npc-nell-soot',
      'npc-sera-lampwright',
      'npc-vessa-thornscale',
      'npc-halden-brack',
      'npc-courier-wren',
    ],
    factionIds: [
      'faction-soot-hands',
      'faction-ember-wardens',
      'faction-ashgate-watch',
    ],
    locationIds: [
      'location-lamplighters-row',
      'location-guttered-candle',
      'location-ashwater-quay',
    ],
    encounterIds: [
      'encounter-guttered-candle-brawl',
      'encounter-ashwater-chase',
    ],
    clueIds: ['clue-flame-signal', 'clue-cloister-ash-mismatch'],
    handoutIds: [
      'handout-flame-signal-sketch',
      'handout-ysolde-letter',
      'lore-court-gossip',
    ],
    plan: crownSession2Plan,
  },
  {
    ...emptyLinks,
    id: crownSessionId(3),
    campaignId: CROWN_CAMPAIGN_ID,
    actId: ACT_2,
    number: 3,
    title: 'Ledgers and Lies',
    status: 'draft',
    summary:
      'Each heir courts the party while the Gilded Ledger offers contracts and the genealogy is put under a magnifying glass. The Marcher Lords press Corvin’s war debt, the physician’s report and the Wardens’ door log disagree about the hour the queen died, and a torn ledger page names a fourth, unexplained payment.',
    partyLevel: 2,
    tags: ['Urban', 'Intrigue'],
    questIds: [
      'quest-who-wears-the-crown',
      'quest-dead-princes-genealogy',
      'quest-queens-last-night',
      'quest-border-lords-ultimatum',
      'quest-ink-without-blood',
      'quest-keep-ashgate-from-burning',
    ],
    npcIds: [
      'npc-oswin-pell',
      'npc-ysolde-vell',
      'npc-corvin-vell',
      'npc-dagna-rook',
      'npc-ferrant-inkwell',
      'npc-maren-vell',
      'npc-vessa-thornscale',
    ],
    factionIds: [
      'faction-gilded-ledger',
      'faction-house-vell',
      'faction-border-lords',
      'faction-ashgate-watch',
      'faction-soot-hands',
    ],
    locationIds: [
      'location-gilded-exchange',
      'location-marchwarden-house',
      'location-queens-chambers',
      'location-inkwell-court',
    ],
    encounterIds: [
      'encounter-border-lords-parley',
      'encounter-forgers-den',
      'encounter-queens-chambers-inquest',
    ],
    clueIds: [
      'clue-heirs-contradictions',
      'clue-dead-prince-seal',
      'clue-queens-last-night',
      'clue-pells-marginalia',
      'clue-forgers-ink',
      'clue-corvin-war-writ',
    ],
    handoutIds: [
      'handout-sealed-genealogy',
      'handout-physicians-report',
      'handout-pell-ledger-excerpt',
      'handout-forgers-receipt',
      'handout-marchwarden-writ',
      'handout-corvin-dispatch',
      'lore-court-gossip',
    ],
    plan: crownSession3Plan,
  },
  {
    ...emptyLinks,
    id: crownSessionId(4),
    campaignId: CROWN_CAMPAIGN_ID,
    actId: ACT_2,
    number: 4,
    title: 'The Crown Vault',
    status: 'draft',
    summary:
      'Tamsin opens the sealed vault; the crown recites the names of the rulers it has burned. Brother Quillon admits what the Wardens sealed, the guardians test the party’s honesty, and a trip to the Vellgrave Mausoleum reveals that the infant prince’s coffin is empty.',
    partyLevel: 3,
    tags: ['Dungeon', 'Lore', 'Puzzle'],
    questIds: [
      'quest-crown-remembers',
      'quest-dead-princes-genealogy',
      'quest-queens-last-night',
    ],
    npcIds: [
      'npc-tamsin-vell',
      'npc-the-crown',
      'npc-oswin-pell',
      'npc-quillon-thrum',
      'npc-maren-vell',
      'npc-aurel-claimant',
    ],
    factionIds: [
      'faction-ember-wardens',
      'faction-house-vell',
      'faction-unquenched',
    ],
    locationIds: ['location-crown-vault', 'location-royal-mausoleum'],
    encounterIds: [
      'encounter-vault-guardians',
      'encounter-mausoleum-vigil',
    ],
    clueIds: ['clue-burn-list', 'clue-empty-coffin'],
    handoutIds: [
      'lore-burned-rulers-roll',
      'lore-crowns-verses',
      'lore-history-of-the-crown',
      'handout-mausoleum-register',
      'handout-tamsin-note',
    ],
  },
  {
    ...emptyLinks,
    id: crownSessionId(5),
    campaignId: CROWN_CAMPAIGN_ID,
    actId: ACT_3,
    number: 5,
    title: 'Beneath the Ember Cloister',
    status: 'draft',
    summary:
      'The paymaster trail leads under the Cloister, where the Unquenched are feeding a rite pit. The ash on the wights came from the Wardens’ own braziers, so the party must decide how much to tell Marshal Brack before Mother Cinder steps out of the smoke.',
    partyLevel: 4,
    tags: ['Dungeon', 'Combat', 'Villain reveal'],
    questIds: [
      'quest-trace-the-cinder-assassins',
      'quest-crown-remembers',
      'quest-keep-ashgate-from-burning',
    ],
    npcIds: [
      'npc-mother-cinder',
      'npc-halden-brack',
      'npc-quillon-thrum',
    ],
    factionIds: ['faction-unquenched', 'faction-ember-wardens'],
    locationIds: ['location-ashen-catacombs', 'location-ember-cloister'],
    encounterIds: ['encounter-catacomb-ashbound'],
    clueIds: ['clue-unquenched-brand', 'clue-cloister-ash-mismatch'],
    handoutIds: ['lore-unquenched-creed', 'lore-warden-founding-oath'],
  },
  {
    ...emptyLinks,
    id: crownSessionId(6),
    campaignId: CROWN_CAMPAIGN_ID,
    actId: ACT_3,
    number: 6,
    title: 'The Crown Remembers',
    status: 'draft',
    summary:
      'Back in the Hall of Nine Banners, the party invokes the witness clause and decides who wears the crown. Every secret they gathered becomes an argument: Corvin’s debt, Ysolde’s loan, Tamsin’s private talks with the crown, the claimant’s coffin, and whatever the queen told the crown on her last night.',
    partyLevel: 4,
    tags: ['Court intrigue', 'Finale', 'Choice'],
    questIds: [
      'quest-who-wears-the-crown',
      'quest-crown-remembers',
      'quest-queens-last-night',
      'quest-border-lords-ultimatum',
    ],
    npcIds: [
      'npc-corvin-vell',
      'npc-ysolde-vell',
      'npc-tamsin-vell',
      'npc-the-crown',
      'npc-mother-cinder',
      'npc-dagna-rook',
      'npc-aurel-claimant',
      'npc-vessa-thornscale',
      'npc-maren-vell',
    ],
    factionIds: [
      'faction-house-vell',
      'faction-unquenched',
      'faction-ember-wardens',
      'faction-border-lords',
    ],
    locationIds: ['location-hall-of-nine-banners'],
    encounterIds: ['encounter-witness-clause'],
    handoutIds: [
      'lore-succession-law',
      'lore-crowns-verses',
      'lore-history-of-the-crown',
    ],
  },
];
