import type { CampaignHandout } from '../ashes-of-veyra/types';
import { KHARAD_CAMPAIGN_ID as C } from './campaign';

const S1 = `${C}-session-1`;
const S2 = `${C}-session-2`;
const S3 = `${C}-session-3`;

export const kharadHandouts: CampaignHandout[] = [
  {
    id: 'handout-inverted-star-chart',
    campaignId: C,
    title: 'The Inverted Star Chart',
    kind: 'handout',
    summary:
      'A crystal-etched chart in which the stars are caverns and the sky is solid rock.',
    content: [
      'Seven glowing points ring a larger, dimmer one. Beneath each is a hold seal; beneath the largest is a single word in old Dwarvish: Kharad.',
      'The lines between the points are not roads but transit routes, and each is broken in exactly one place.',
    ],
    visibility: 'shared',
    sessionIds: [S1, S2],
    clueIds: ['clue-inverted-constellation', 'clue-seven-hold-seals'],
    questIds: ['quest-read-inverted-chart'],
    locationIds: ['location-inverted-observatory'],
    factionIds: ['faction-chalkline-collegium'],
  },
  {
    id: 'handout-survey-crew-log',
    campaignId: C,
    title: 'Survey Crew Log',
    kind: 'handout',
    summary:
      'A water-stained log kept by the trapped crew before the collapse.',
    content: [
      'Day 3: the fault sang back our own voices before we sang them. Yarrow says it is a trick of the quartz. Nobody laughs.',
      'Day 5: the walls are warm. The compass will not settle. If anyone finds this, do not dig toward the light.',
    ],
    visibility: 'shared',
    sessionIds: [S1],
    clueIds: ['clue-echoes-run-early'],
    questIds: ['quest-rescue-survey-crew'],
    locationIds: ['location-singing-fault', 'location-kharad-mine'],
    factionIds: ['faction-kharad-delvers-union'],
  },
  {
    id: 'lore-seven-holds-charter',
    campaignId: C,
    title: 'The Seven-Hold Charter',
    kind: 'lore',
    summary:
      'The founding compact of the Concord and the seals each hold contributed.',
    content: [
      'Seven holds bound themselves to share the deep roads, and pledged that no one hold should claim any thing found beneath the shared stone.',
      'Article Nine reserves any machine of the old builders to a named custodian who answers to all seven.',
    ],
    visibility: 'dm-only',
    sessionIds: [S2],
    clueIds: ['clue-seven-hold-seals', 'clue-gate-custodian-oath'],
    questIds: ['quest-open-the-transit-gate', 'quest-read-inverted-chart'],
    locationIds: ['location-broken-gate-hall'],
    factionIds: ['faction-seven-hold-concord'],
  },
  {
    id: 'handout-concord-writ-of-custodianship',
    campaignId: C,
    title: 'Writ of Custodianship',
    kind: 'handout',
    summary:
      'The Concord writ naming Dagna Seven-Chalks custodian of the star engine.',
    content: [
      'By the authority of Article Nine, the Concord names Dagna Seven-Chalks custodian of the engine beneath Kharad, answerable to all seven holds.',
      'Witnessed by Magistrate Ilsa Vaunt. The gate will answer only to the named custodian.',
    ],
    visibility: 'shared',
    sessionIds: [S2],
    clueIds: ['clue-gate-custodian-oath'],
    questIds: ['quest-open-the-transit-gate'],
    locationIds: ['location-broken-gate-hall'],
    factionIds: ['faction-seven-hold-concord'],
  },
  {
    id: 'handout-ordrun-sealed-orders',
    campaignId: C,
    title: 'Ordrun’s Sealed Orders',
    kind: 'handout',
    summary:
      'Orders recovered from the marshal’s courier revealing the Company’s plan.',
    content: [
      'Secure the engine at any cost. Should the custodian refuse, the vessel is to be bound to the Company’s command word.',
      'A note in the margin, in Duskforge script: “Our delegate will keep the Concord divided until you are inside.”',
    ],
    visibility: 'dm-only',
    sessionIds: [S2],
    clueIds: ['clue-ordrun-orders'],
    questIds: [
      'quest-race-ordrun-to-the-engine',
      'quest-sabotage-for-the-holds',
    ],
    locationIds: ['location-transit-line'],
    factionIds: ['faction-ardent-deep-company', 'faction-duskforge-hold'],
  },
  {
    id: 'lore-star-engine-purpose',
    campaignId: C,
    title: 'What the Star Engine Is For',
    kind: 'lore',
    summary:
      'The builders’ purpose for the engine, pieced together across the campaign.',
    content: [
      'The engine is a launch cradle for a vessel meant to carry a civilization to the sky, and a failsafe meant to burn the vessel if it falls into hostile hands.',
      'The Astronomer serves whichever purpose the rings select; naming a shared purpose is the only way to hold both at bay.',
    ],
    visibility: 'dm-only',
    sessionIds: [S3],
    clueIds: [
      'clue-engine-ring-alignment',
      'clue-astronomers-purpose',
      'clue-ark-or-weapon',
    ],
    questIds: ['quest-fate-of-the-vessel'],
    locationIds: ['location-engine-heart'],
    factionIds: ['faction-astronomers-watch'],
  },
  {
    id: 'handout-astronomers-final-message',
    campaignId: C,
    title: 'The Astronomer’s Final Message',
    kind: 'handout',
    summary:
      'The guardian’s parting words as the rings fall still.',
    content: [
      'You have named a purpose that neither launches nor destroys. I was not built to answer such a question; I will keep the light you have made.',
      'Tell the holds the sky was never a place. It was a promise, and you have kept it.',
    ],
    visibility: 'shared',
    sessionIds: [S3],
    clueIds: ['clue-astronomers-purpose', 'clue-ark-or-weapon'],
    questIds: ['quest-fate-of-the-vessel'],
    locationIds: ['location-engine-heart'],
    factionIds: ['faction-astronomers-watch'],
  },
  {
    id: 'handout-epilogue-proclamation',
    campaignId: C,
    title: 'Proclamation of the Commons',
    kind: 'handout',
    summary:
      'The Concord proclamation founding the Commons of Seven Chalks under the deep sun.',
    content: [
      'Under the light the heroes made, the seven holds establish a Commons where miners, scholars, and delegates sit as equals.',
      'Custodianship of the engine passes to a rotating council; Dagna Seven-Chalks holds the first seat. Hold Duskforge’s claim to the engine is denied.',
    ],
    visibility: 'shared',
    sessionIds: [S3],
    clueIds: [],
    questIds: ['quest-honor-the-seven-promises'],
    locationIds: ['location-kharad-commons'],
    factionIds: ['faction-seven-hold-concord', 'faction-kharad-delvers-union'],
  },
  {
    id: 'lore-legacy-of-kharad',
    campaignId: C,
    title: 'The Legacy of Kharad',
    kind: 'lore',
    summary:
      'How each hold, and each hero, remembers the night the deep sky opened.',
    content: [
      'Miners call it the Kindling. Scholars call it the Chalk Revision, since Dagna’s theory was vindicated on every syllabus.',
      'Orik keeps the survey hammer at the Commons gate; Nima sealed her engine key inside the deep sun’s casing; Hale-of-Echoes tends the shrine where the evening bell rings.',
    ],
    visibility: 'dm-only',
    sessionIds: [S3],
    clueIds: [],
    questIds: [
      'quest-honor-the-seven-promises',
      'quest-fate-of-the-vessel',
    ],
    locationIds: ['location-kharad-commons', 'location-engine-heart'],
    factionIds: [
      'faction-seven-hold-concord',
      'faction-chalkline-collegium',
      'faction-kharad-delvers-union',
    ],
  },
  {
    id: 'lore-seven-holds-gazetteer',
    campaignId: C,
    title: 'Gazetteer of the Seven Holds',
    kind: 'lore',
    summary:
      'A one-page portrait of each hold in the Concord: what it makes, whom it distrusts and what its delegate wants from the engine.',
    content: [
      'Duskforge: the smithing hold, rich in iron and grievance. Its forgemasters believe the engine is the largest anvil ever found, and that a hammer is only a tool until someone with a grudge picks it up. Delegate: Oskar Deepfire. Distrusts Greywarden, who once refused to garrison its foundries.',
      'Greywarden: the wall-wardens who hold the border galleries. Their sentries have spent four centuries learning that every door someone leaves unwatched becomes a war. Delegate: Brondi Greywall. Wants the engine behind a lock that needs seven keys and sees any single-key proposal as treason.',
      'Thrumhall: bell-founders and railwrights; every rail, switch and timetable on the transit line bears a Thrumhall stamp. Delegate: Sunniva Thrum. Wants the line to run and her hold credited. Rival of Highvein over tolls.',
      'Highvein: silver-vein bankers who underwrite half the Concord’s treasuries. Delegate: Orla Silvervein. Wants a stake in whatever the engine becomes, and prefers interest to victory.',
      'Marrowstone: ossuary-keepers who bury the dead of all seven holds and keep their names in stone. Delegate: Bodil Marrowsong. Wants to know whether the sleepers are Marrowstone’s own.',
      'Bellowmere: steam-brewers and mushroom farmers who believe a hungry delegate is a hostile one. Delegate: Kjeld Bellows. Trades votes for kitchens.',
      'Ghostlamp: lampwrights and oil-merchants who light every shared tunnel. Delegate: Ysolde Ghostlamp. Wants to understand why her lamps burn violet and to sell that knowledge before anyone else can.',
    ],
    visibility: 'shared',
    sessionIds: [S2],
    clueIds: ['clue-seven-hold-seals'],
    questIds: ['quest-read-inverted-chart', 'quest-open-the-transit-gate'],
    locationIds: ['location-broken-gate-hall'],
    factionIds: [
      'faction-seven-hold-concord',
      'faction-duskforge-hold',
      'faction-hold-greywarden',
      'faction-hold-thrumhall',
      'faction-hold-highvein',
      'faction-hold-marrowstone',
      'faction-hold-bellowmere',
      'faction-hold-ghostlamp',
    ],
  },
  {
    id: 'lore-star-chart-legend',
    campaignId: C,
    title: 'Legend of the Star Chart',
    kind: 'lore',
    summary:
      'Pell Quartz’s key to the chart’s symbols, translated from the builders’ marginalia and annotated with what remains unexplained.',
    content: [
      'A filled point is a hold with a living delegation at the time the chart was cut; a ringed point is a hold that has since lapsed. Seven filled points surround the larger, dimmer point labelled Kharad, which Pell reads as “the place where the sky was kept.”',
      'A solid line is a transit route; a line with a single gap marks a safety break, one on each of the seven routes. A dotted line from Kharad downward has no label at all and is the only line on the chart that does not touch a hold seal.',
      'Along the rim, in a different, smaller script, Pell found a faint mark outside the constellation, directly beneath Kharad. It has no seal, no name and no line leading to it. Pell’s margin note reads: “Either the cartographer’s hand slipped, or someone asked it to be there.”',
      'The legend explains the glow on the chart table: the builders used the same color for “awake” and “watching”. Pell cautions against reading it as a threat until more of the language is understood.',
    ],
    visibility: 'dm-only',
    sessionIds: [S1],
    clueIds: ['clue-compass-turns-down', 'clue-the-eighth-point'],
    questIds: ['quest-read-inverted-chart', 'quest-the-eighth-light'],
    locationIds: ['location-inverted-observatory'],
    factionIds: ['faction-chalkline-collegium'],
  },
  {
    id: 'handout-thrumhall-line-ledger',
    campaignId: C,
    title: 'Thrumhall Line Ledger',
    kind: 'handout',
    summary:
      'A page from the transit line’s maintenance ledger, listing each safety break and the hold that last repaired it.',
    content: [
      'Route One, Greywarden spur: break at the seventh switch, last maintained by Thrumhall in the year of the Long Frost. Note: no one has ever been able to repair this break, only reset it.',
      'Route Two, Duskforge spur: break at the second signal tower. Repaired by order of the Duskforge forgemasters, who requested that the break be “forgotten” in the ledger. Request refused by the railwrights, in pen.',
      'Route Four, Highvein spur: two breaks recorded, both stamped with a Highvein seal. The second break is annotated: “Not original.”',
      'At the bottom, in Sunniva’s own hand: “Seven routes, seven breaks, and the oldest rule on the line: a train that tries to cross all seven in one night is not ours to stop.”',
    ],
    visibility: 'shared',
    sessionIds: [S2, S3],
    clueIds: ['clue-broken-in-one-place'],
    questIds: [
      'quest-open-the-transit-gate',
      'quest-seal-the-transit-line',
    ],
    locationIds: [
      'location-thrumhall-switchyard',
      'location-transit-line',
    ],
    factionIds: ['faction-hold-thrumhall'],
  },
  {
    id: 'handout-highvein-toll-ledger',
    campaignId: C,
    title: 'Highvein Toll Ledger',
    kind: 'handout',
    summary:
      'Copied pages from Highvein’s counting house showing a toll schedule for the Commons drafted before the Commons existed.',
    content: [
      'Lamp-toll: one silver bit per lamp per week. Bread-toll: one copper per loaf. Bell-toll: one copper per ring, “payable by whoever lifts the rope”. All items dated eleven days before the Concord voted to open the gate.',
      'A note in the ledger’s margin reads: “Do not publish until the hold is seated. Everything that can be counted can be charged.” The hand is Orla Silvervein’s.',
      'A second page lists exemptions: Highvein’s own delegates, Duskforge’s forge-crews, and “such persons as the Speaker may name in writing”. The Delvers’ Union is not on the exemption list.',
      'The final line, newly inked: “Await the custodian’s consent. If none is given, proceed under Article Nine, clause four: tolls on common stone.”',
    ],
    visibility: 'dm-only',
    sessionIds: [S3],
    clueIds: ['clue-highvein-toll-ledger'],
    questIds: ['quest-turn-the-tolls'],
    locationIds: [
      'location-highvein-counting-house',
      'location-kharad-commons',
    ],
    factionIds: ['faction-hold-highvein', 'faction-kharad-delvers-union'],
  },
  {
    id: 'handout-ketta-rawls-letter',
    campaignId: C,
    title: 'Letter from Ketta Rawl',
    kind: 'handout',
    summary:
      'A note pressed into the party’s hands at Meridian Station by the courier who carried Ordrun’s orders.',
    content: [
      'I carry orders I was never meant to read. I read them. If you are holding this, I left them where you would find them, because I would rather be a traitor than a witness to what the Marshal means to do with the light.',
      'The command word is written for a guardian, not a custodian. She does not intend to ask the Astronomer for anything. She intends to tell it. If it will not answer, she says the Company has a second word, and that I was never to know what it does.',
      'The margin note in Duskforge script was added in a hall I am not allowed to describe. I recognize the hand. I will not say whose it is until I am somewhere with a magistrate and a door that locks.',
      'Hide me, or do not. But do not let her reach the rings. — K.R.',
    ],
    visibility: 'shared',
    sessionIds: [S2],
    clueIds: [
      'clue-ketta-rawls-confession',
      'clue-duskforge-margin-script',
    ],
    questIds: [
      'quest-the-deserters-bargain',
      'quest-race-ordrun-to-the-engine',
    ],
    locationIds: ['location-meridian-station'],
    factionIds: ['faction-ardent-deep-company'],
  },
  {
    id: 'handout-marrowstone-sleeper-manifest',
    campaignId: C,
    title: 'The Sleeper Manifest',
    kind: 'handout',
    summary:
      'A copy of the vessel’s passenger manifest, made by Hold Marrowstone’s ossuary-keepers inside the berth galleries.',
    content: [
      'Total sleepers: forty thousand, one hundred and twelve. Berth rows are numbered in descending gold, one row per name. The last row is blank.',
      'Each berth carries an engraved lid with a name in the builders’ script. Pell has translated nine hundred and four; none are recognizably a hold’s family name. Bodil believes they are generations, not people.',
      'Every lid the party opened was empty. The berths show no wear, no residue and no sign of use. The air in the gallery smells of cold and nothing else.',
      'In the margin, in Bodil’s steady hand: “If they left, where? If they were never here, why are the lids warm?”',
    ],
    visibility: 'shared',
    sessionIds: [S3],
    clueIds: ['clue-empty-berths'],
    questIds: [
      'quest-bring-the-ancestors-home',
      'quest-the-eighth-light',
    ],
    locationIds: ['location-berth-galleries'],
    factionIds: ['faction-hold-marrowstone'],
  },
  {
    id: 'handout-ashglass-key-letter',
    campaignId: C,
    title: 'Letter from Grandmother Ashglass',
    kind: 'handout',
    summary:
      'The warning that came with Nima’s inherited key, finally delivered with Fennick’s cracked brass case.',
    content: [
      'Nima, if you are reading this, the engine is awake and I was wrong to hope it never would be. You carry one key. Do not use it alone.',
      'The Ashglass line cut two keys because the builders left one of them with someone who was meant to give it up. I never learned who. Your great-uncle Fennick knows only that the second key lives where silver is counted.',
      'If the light below Kharad ever answers to your key, close your hand. The engine will test whether you mean it. Say what you mean before you turn it.',
      'I am proud of every ugly, brilliant thing you built. — G.A.',
    ],
    visibility: 'shared',
    sessionIds: [S3],
    clueIds: ['clue-key-hums-toward-highvein'],
    questIds: ['quest-the-eighth-light'],
    locationIds: ['location-kharad-commons'],
    factionIds: ['faction-chalkline-collegium'],
  },
  {
    id: 'handout-delvers-union-roll',
    campaignId: C,
    title: 'Roll of the Rescued',
    kind: 'handout',
    summary:
      'The Delvers’ Union roll of the eleven miners and surveyors brought out of the Singing Fault.',
    content: [
      'Yarrow Stonesinger, fault-singer. Bruni Coalhand, lamp-bearer. Edda Lowseam, shoring-mistress. Garrick Flint-Tally, shift-clerk.',
      'Hilde Pickwright, pick-hand. Osric Deepdoor, door-warden. Maude Quartzwife, assayer. Torvi Anvilsleep, hammerman.',
      'Fenn Ladderkeep, rope-hand. Ragna Shaftborn, shaft-mate. Dunmar Chalkfinger, junior surveyor.',
      'Beneath the names, in Tamsin Brack’s square hand: “Eleven came out. The Union will remember who carried them, and the Union does not forget.”',
    ],
    visibility: 'shared',
    sessionIds: [S1, S3],
    clueIds: [],
    questIds: [
      'quest-rescue-survey-crew',
      'quest-light-the-evening-shrine',
    ],
    locationIds: ['location-kharad-mine', 'location-lift-head-shrine'],
    factionIds: ['faction-kharad-delvers-union'],
  },
  {
    id: 'lore-ghostlamp-lamp-liturgy',
    campaignId: C,
    title: 'The Ghostlamp Lamp Liturgy',
    kind: 'lore',
    summary:
      'The lamp-lighters’ prayer, and the color-code by which Hold Ghostlamp reads flame as omen.',
    content: [
      'Gold flame means a shaft is safe. Green flame means bad air. Red flame means a fire elsewhere. A blue flame means a lamp has gone out of true and should be replaced before the next shift. These are the old colors and every miner knows them.',
      'Violet flame, until the week of the collapse, appeared in one liturgy only, a funeral rite: “When the lamp turns violet, someone is awake who was not before.” Ysolde had never seen it in a working lamp.',
      'Her private log lists every violet lamp in the order it turned: first at the Kharad lift head, then in the lower galleries, then, impossibly, in a sealed lamp case in the Concord archive.',
      'Ghostlamp doctrine is clear on one point: you do not extinguish a violet lamp. You carry it, and you ask what it is waiting for.',
    ],
    visibility: 'dm-only',
    sessionIds: [S1],
    clueIds: ['clue-violet-lamplight'],
    questIds: [
      'quest-rescue-survey-crew',
      'quest-light-the-evening-shrine',
    ],
    locationIds: ['location-kharad-mine', 'location-lift-head-shrine'],
    factionIds: ['faction-hold-ghostlamp'],
  },
  {
    id: 'handout-epilogue-letter-hrolda',
    campaignId: C,
    title: 'Letter from Speaker Hrolda',
    kind: 'handout',
    summary:
      'A year-on letter from the Speaker to each member of the party, delivered through the Commons post.',
    content: [
      'The Commons is still standing, which is more than I expected and less than I hoped. Seven delegates still argue, but they argue in the same room. I have decided to count this as peace.',
      'Brondi Greywall has asked me to tell you that he will never say you were right, but that he now sleeps with the gate unlocked. Kjeld says the taproom is yours for life. Sunniva wants a word about the new timetable.',
      'There is a matter I cannot put in a letter. Orla Silvervein has asked for a private audience with the custodian. I have declined twice. I will decline a third time. After that, I do not know what the Concord can do. — H.',
    ],
    visibility: 'shared',
    sessionIds: [S3],
    clueIds: [],
    questIds: [
      'quest-honor-the-seven-promises',
      'quest-turn-the-tolls',
    ],
    locationIds: ['location-kharad-commons'],
    factionIds: ['faction-seven-hold-concord'],
  },
  {
    id: 'handout-epilogue-letter-orla',
    campaignId: C,
    title: 'Letter from Orla Silvervein',
    kind: 'handout',
    summary:
      'A courteous letter from Highvein’s delegate that is polite enough to be threatening.',
    content: [
      'Esteemed custodian, I write to congratulate you on the Commons. Commerce is the quiet sister of peace, and I am pleased to see her thriving beneath so handsome a sun.',
      'It has come to my attention that a certain tuning fork in your possession responds to an instrument kept in my counting house. I hope you will forgive my curiosity. I would not dream of asking you to hand it over, only to sit beside it, and hear what it says.',
      'I am told that an invitation to dinner is a gentler thing than a writ. I remain, as ever, your patient friend. — O.S.',
    ],
    visibility: 'shared',
    sessionIds: [S3],
    clueIds: ['clue-key-hums-toward-highvein'],
    questIds: ['quest-turn-the-tolls', 'quest-the-eighth-light'],
    locationIds: ['location-highvein-counting-house'],
    factionIds: ['faction-hold-highvein'],
  },
  {
    id: 'lore-kindling-night-oral-history',
    campaignId: C,
    title: 'The Kindling Night, as Told',
    kind: 'lore',
    summary:
      'Three accounts of the night the deep sun was lit, collected at the Commons’ first long table.',
    content: [
      'A miner’s account: “The ground stopped humming and I thought I was dead. Then it started again, softer. Then somebody opened a door I had always thought was a wall and light came up the stairs like water.”',
      'A scholar’s account: “The chalk revision will say that the engine yielded to reasoned argument. That is true, and it is also true that Dagna was shouting. I wish both to be recorded.”',
      'A delegate’s account: “I watched the vote in my own hall go from seven stubborn faces to seven afraid ones in the space of one breath. It was the first time we agreed on anything. I would not recommend it as a method.”',
      'A child’s account, collected by Gruvna Brightcut: “The sun came down to the shelf and sat. Then the Astronomer said goodnight.”',
    ],
    visibility: 'shared',
    sessionIds: [S3],
    clueIds: [],
    questIds: [
      'quest-fate-of-the-vessel',
      'quest-light-the-evening-shrine',
    ],
    locationIds: ['location-kharad-commons', 'location-engine-heart'],
    factionIds: [
      'faction-kindled-congregation',
      'faction-kharad-delvers-union',
    ],
  },
  {
    id: 'handout-eighth-point-rubbing',
    campaignId: C,
    title: 'Rubbing of the Eighth Point',
    kind: 'handout',
    summary:
      'A charcoal rubbing of the unlabeled mark beneath Kharad on the chart’s rim.',
    content: [
      'A single small circle with a vertical line through it, and below it, three tiny crescents arranged like the legs of a stool. Nothing else.',
      'Pell insists it is not a hold seal. Dagna insists it is a hold seal that was ground off. Nima notes that the line through the circle matches the keyway on her inherited key.',
      'A thumb-width smudge in the corner of the rubbing is, on close inspection, a fingerprint. It is far too small to be a dwarf’s.',
    ],
    visibility: 'shared',
    sessionIds: [S1, S3],
    clueIds: ['clue-the-eighth-point'],
    questIds: ['quest-the-eighth-light'],
    locationIds: [
      'location-inverted-observatory',
      'location-eighth-shaft',
    ],
    factionIds: ['faction-chalkline-collegium'],
  },
  {
    id: 'handout-bellowmere-kitchens-compact',
    campaignId: C,
    title: 'The Bellowmere Kitchens Compact',
    kind: 'handout',
    summary:
      'The shared-kitchens promise that bought Bellowmere’s swing vote at the council.',
    content: [
      'Bellowmere will open its steam-kitchens to any hold’s delegation on the day of a Concord sitting and will not charge for bread. In return, the Concord will agree that no sitting may adjourn hungry.',
      'Kjeld Bellows signs for Bellowmere; Magistrate Vaunt witnesses. A line in the margin reads: “Kept at the Commons dedication, by order of the taproom.”',
    ],
    visibility: 'shared',
    sessionIds: [S2],
    clueIds: [],
    questIds: [
      'quest-open-the-transit-gate',
      'quest-honor-the-seven-promises',
    ],
    locationIds: ['location-broken-gate-hall', 'location-kharad-commons'],
    factionIds: ['faction-hold-bellowmere', 'faction-seven-hold-concord'],
  },
];
