import type { FolderRecord, LibraryObject } from '../ashes-of-veyra/types';
import { KHARAD_ACT_EPILOGUE_ID, KHARAD_ACT_ONE_ID } from './campaign';

export const kharadLibraryObjects: LibraryObject[] = [
  {
    id: 'encounter-resonant-fault-collapse',
    title: 'Resonant Fault Collapse',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'encounter-survey-crew-defense',
    title: 'Defend the Survey Crew',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'handout-inverted-star-chart',
    title: 'The Inverted Star Chart',
    kind: 'handout',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'npc-tamsin-brack',
    title: 'Foreman Tamsin Brack',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'npc-hrolda-ironvein',
    title: 'Speaker Hrolda Ironvein',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'lore-seven-holds-charter',
    title: 'The Seven-Hold Charter',
    kind: 'lore',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'faction-seven-hold-concord',
    title: 'The Seven-Hold Concord',
    kind: 'faction',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'quest-read-inverted-chart',
    title: 'Read the Inverted Star Chart',
    kind: 'quest',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'encounter-astronomer-awakens',
    title: 'The Astronomer Awakens',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-the-astronomer',
    title: 'The Astronomer',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'lore-star-engine-purpose',
    title: 'What the Star Engine Is For',
    kind: 'lore',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'location-kharad-commons',
    title: 'The Commons of Seven Chalks',
    kind: 'scene',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'handout-epilogue-proclamation',
    title: 'Proclamation of the Commons',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'lore-legacy-of-kharad',
    title: 'The Legacy of Kharad',
    kind: 'lore',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'quest-honor-the-seven-promises',
    title: 'Honor the Seven Promises',
    kind: 'quest',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'location-lift-head-shrine',
    title: 'The Lift-Head Shrine',
    kind: 'scene',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'location-chalk-gallery',
    title: 'The Chalk Gallery',
    kind: 'scene',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'location-thrumhall-switchyard',
    title: 'The Thrumhall Switchyard',
    kind: 'scene',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'location-meridian-station',
    title: 'Meridian Station',
    kind: 'scene',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'location-berth-galleries',
    title: 'The Berth Galleries',
    kind: 'scene',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'location-eighth-shaft',
    title: 'The Eighth Shaft',
    kind: 'scene',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'location-highvein-counting-house',
    title: 'The Highvein Counting House',
    kind: 'scene',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'location-evening-bell-shrine',
    title: 'The Evening Bell Shrine',
    kind: 'scene',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'npc-brondi-greywall',
    title: 'Warden-Delegate Brondi Greywall',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-sunniva-thrum',
    title: 'Railwright Sunniva Thrum',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-orla-silvervein',
    title: 'Banker-Delegate Orla Silvervein',
    kind: 'npc',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'npc-bodil-marrowsong',
    title: 'Ancestor-Keeper Bodil Marrowsong',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-kjeld-bellows',
    title: 'Brewmaster Kjeld Bellows',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-ysolde-ghostlamp',
    title: 'Lampwright Ysolde Ghostlamp',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-ketta-rawl',
    title: 'Courier Ketta Rawl',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-fennick-ashglass',
    title: 'Tinker Fennick Ashglass',
    kind: 'npc',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'npc-gruvna-brightcut',
    title: 'Echo-Prior Gruvna Brightcut',
    kind: 'npc',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'encounter-quartz-spur-bridge',
    title: 'The Quartz Spur Bridge',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'encounter-banquet-of-seven-knives',
    title: 'The Banquet of Seven Knives',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'encounter-thrumhall-switchyard',
    title: 'The Thrumhall Switchyard',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'encounter-ketta-pursuit',
    title: 'Knife-Squads at the Meridian Siding',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'encounter-deep-sun-flare',
    title: 'The Deep Sun Flare',
    kind: 'encounter',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'encounter-eighth-shaft-descent',
    title: 'Descent into the Eighth Shaft',
    kind: 'encounter',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '2 months ago',
  },
  {
    id: 'lore-seven-holds-gazetteer',
    title: 'Gazetteer of the Seven Holds',
    kind: 'lore',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'lore-star-chart-legend',
    title: 'Legend of the Star Chart',
    kind: 'lore',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'lore-ghostlamp-lamp-liturgy',
    title: 'The Ghostlamp Lamp Liturgy',
    kind: 'lore',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'lore-kindling-night-oral-history',
    title: 'The Kindling Night, as Told',
    kind: 'lore',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'handout-thrumhall-line-ledger',
    title: 'Thrumhall Line Ledger',
    kind: 'handout',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'handout-ketta-rawls-letter',
    title: 'Letter from Ketta Rawl',
    kind: 'handout',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'handout-bellowmere-kitchens-compact',
    title: 'The Bellowmere Kitchens Compact',
    kind: 'handout',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'handout-delvers-union-roll',
    title: 'Roll of the Rescued',
    kind: 'handout',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'handout-eighth-point-rubbing',
    title: 'Rubbing of the Eighth Point',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'handout-marrowstone-sleeper-manifest',
    title: 'The Sleeper Manifest',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'handout-ashglass-key-letter',
    title: 'Letter from Grandmother Ashglass',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'handout-highvein-toll-ledger',
    title: 'Highvein Toll Ledger',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'handout-epilogue-letter-hrolda',
    title: 'Letter from Speaker Hrolda',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '2 months ago',
  },
  {
    id: 'handout-epilogue-letter-orla',
    title: 'Letter from Orla Silvervein',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '2 months ago',
  },
  {
    id: 'faction-hold-greywarden',
    title: 'Hold Greywarden',
    kind: 'faction',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'faction-hold-thrumhall',
    title: 'Hold Thrumhall',
    kind: 'faction',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'faction-hold-highvein',
    title: 'Hold Highvein',
    kind: 'faction',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'faction-hold-marrowstone',
    title: 'Hold Marrowstone',
    kind: 'faction',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'faction-hold-bellowmere',
    title: 'Hold Bellowmere',
    kind: 'faction',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'faction-hold-ghostlamp',
    title: 'Hold Ghostlamp',
    kind: 'faction',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'faction-kindled-congregation',
    title: 'The Kindled Congregation',
    kind: 'faction',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'quest-seal-the-transit-line',
    title: 'Seal the Transit Line',
    kind: 'quest',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'quest-bring-the-ancestors-home',
    title: 'Bring the Ancestors Home',
    kind: 'quest',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'quest-the-deserters-bargain',
    title: 'The Deserter’s Bargain',
    kind: 'quest',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'quest-light-the-evening-shrine',
    title: 'Light the Evening Shrine',
    kind: 'quest',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '3 months ago',
  },
  {
    id: 'quest-turn-the-tolls',
    title: 'Turn the Tolls',
    kind: 'quest',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '2 months ago',
  },
  {
    id: 'quest-the-eighth-light',
    title: 'The Eighth Light',
    kind: 'quest',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '2 months ago',
  },
];

export const kharadFolders: FolderRecord[] = [
  {
    id: 'folder-kharad-act-one',
    title: 'Act I - The Buried Constellation',
    actId: KHARAD_ACT_ONE_ID,
    objectIds: [
      'encounter-resonant-fault-collapse',
      'encounter-survey-crew-defense',
      'handout-inverted-star-chart',
      'npc-tamsin-brack',
      'npc-hrolda-ironvein',
      'lore-seven-holds-charter',
      'faction-seven-hold-concord',
      'quest-read-inverted-chart',
      'encounter-astronomer-awakens',
      'npc-the-astronomer',
      'lore-star-engine-purpose',
      'location-lift-head-shrine',
      'location-chalk-gallery',
      'location-thrumhall-switchyard',
      'location-meridian-station',
      'npc-brondi-greywall',
      'npc-sunniva-thrum',
      'npc-bodil-marrowsong',
      'npc-kjeld-bellows',
      'npc-ysolde-ghostlamp',
      'npc-ketta-rawl',
      'encounter-quartz-spur-bridge',
      'encounter-banquet-of-seven-knives',
      'encounter-thrumhall-switchyard',
      'encounter-ketta-pursuit',
      'lore-seven-holds-gazetteer',
      'lore-star-chart-legend',
      'lore-ghostlamp-lamp-liturgy',
      'handout-thrumhall-line-ledger',
      'handout-ketta-rawls-letter',
      'handout-bellowmere-kitchens-compact',
      'handout-delvers-union-roll',
      'faction-hold-greywarden',
      'faction-hold-thrumhall',
      'faction-hold-marrowstone',
      'faction-hold-bellowmere',
      'faction-hold-ghostlamp',
      'quest-the-deserters-bargain',
    ],
    children: [
      { kind: 'scene', count: 4 },
      { kind: 'npc', count: 9 },
      { kind: 'encounter', count: 7 },
      { kind: 'handout', count: 10 },
    ],
  },
  {
    id: 'folder-kharad-epilogue',
    title: 'Epilogue - Under a Changed Sky',
    actId: KHARAD_ACT_EPILOGUE_ID,
    objectIds: [
      'location-kharad-commons',
      'handout-epilogue-proclamation',
      'lore-legacy-of-kharad',
      'quest-honor-the-seven-promises',
      'location-berth-galleries',
      'location-eighth-shaft',
      'location-highvein-counting-house',
      'location-evening-bell-shrine',
      'npc-orla-silvervein',
      'npc-fennick-ashglass',
      'npc-gruvna-brightcut',
      'encounter-deep-sun-flare',
      'encounter-eighth-shaft-descent',
      'lore-kindling-night-oral-history',
      'handout-eighth-point-rubbing',
      'handout-marrowstone-sleeper-manifest',
      'handout-ashglass-key-letter',
      'handout-highvein-toll-ledger',
      'handout-epilogue-letter-hrolda',
      'handout-epilogue-letter-orla',
      'faction-hold-highvein',
      'faction-kindled-congregation',
      'quest-seal-the-transit-line',
      'quest-bring-the-ancestors-home',
      'quest-light-the-evening-shrine',
      'quest-turn-the-tolls',
      'quest-the-eighth-light',
    ],
    children: [
      { kind: 'scene', count: 5 },
      { kind: 'npc', count: 3 },
      { kind: 'encounter', count: 2 },
      { kind: 'handout', count: 9 },
    ],
  },
];
