import type { FolderRecord, LibraryObject } from '../ashes-of-veyra/types';
import { KHARAD_ACT_EPILOGUE_ID, KHARAD_ACT_ONE_ID } from './campaign';

export const kharadLibraryObjects: LibraryObject[] = [
  {
    id: 'encounter-resonant-fault-collapse',
    title: 'Resonant Fault Collapse',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'encounter-survey-crew-defense',
    title: 'Defend the Survey Crew',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'handout-inverted-star-chart',
    title: 'The Inverted Star Chart',
    kind: 'handout',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'npc-tamsin-brack',
    title: 'Foreman Tamsin Brack',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '5 months ago',
  },
  {
    id: 'npc-hrolda-ironvein',
    title: 'Speaker Hrolda Ironvein',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'lore-seven-holds-charter',
    title: 'The Seven-Hold Charter',
    kind: 'lore',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'faction-seven-hold-concord',
    title: 'The Seven-Hold Concord',
    kind: 'faction',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'quest-read-inverted-chart',
    title: 'Read the Inverted Star Chart',
    kind: 'quest',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'encounter-astronomer-awakens',
    title: 'The Astronomer Awakens',
    kind: 'encounter',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'npc-the-astronomer',
    title: 'The Astronomer',
    kind: 'npc',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'lore-star-engine-purpose',
    title: 'What the Star Engine Is For',
    kind: 'lore',
    folderActId: KHARAD_ACT_ONE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'location-kharad-commons',
    title: 'The Commons of Seven Chalks',
    kind: 'scene',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'handout-epilogue-proclamation',
    title: 'Proclamation of the Commons',
    kind: 'handout',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'lore-legacy-of-kharad',
    title: 'The Legacy of Kharad',
    kind: 'lore',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
  {
    id: 'quest-honor-the-seven-promises',
    title: 'Honor the Seven Promises',
    kind: 'quest',
    folderActId: KHARAD_ACT_EPILOGUE_ID,
    updatedLabel: '4 months ago',
  },
];

export const kharadFolders: FolderRecord[] = [
  {
    id: 'folder-kharad-act-one',
    title: 'Act I - The Buried Constellation',
    actId: KHARAD_ACT_ONE_ID,
    objectIds: [
      'encounter-resonant-fault-collapse',
      'encounter-survey-crew-defense',
      'handout-inverted-star-chart',
      'npc-tamsin-brack',
      'npc-hrolda-ironvein',
      'lore-seven-holds-charter',
      'faction-seven-hold-concord',
      'quest-read-inverted-chart',
      'encounter-astronomer-awakens',
      'npc-the-astronomer',
      'lore-star-engine-purpose',
    ],
    children: [
      { kind: 'scene', count: 7 },
      { kind: 'npc', count: 7 },
      { kind: 'encounter', count: 7 },
      { kind: 'handout', count: 5 },
    ],
  },
  {
    id: 'folder-kharad-epilogue',
    title: 'Epilogue - Under a Changed Sky',
    actId: KHARAD_ACT_EPILOGUE_ID,
    objectIds: [
      'location-kharad-commons',
      'handout-epilogue-proclamation',
      'lore-legacy-of-kharad',
      'quest-honor-the-seven-promises',
    ],
    children: [
      { kind: 'scene', count: 1 },
      { kind: 'npc', count: 0 },
      { kind: 'encounter', count: 1 },
      { kind: 'handout', count: 2 },
    ],
  },
];
