import type { CampaignLocation } from '../ashes-of-veyra/types';
import { KHARAD_CAMPAIGN_ID as C } from './campaign';

const MAP = 'map-buried-constellation';

export const kharadLocations: CampaignLocation[] = [
  {
    id: 'location-kharad-mine',
    campaignId: C,
    name: 'Kharad Mine',
    type: 'district',
    shortDescription:
      'A deep working mine whose collapse exposed the observatory.',
    description: [
      'Lamp-lit galleries run down through seams of blue quartz. The collapse shows as a raw scar across the lowest shaft.',
      'Miners’ families keep a shrine at the lift head for those who did not come back from earlier accidents.',
      'The upper galleries are where the party first heard the fault sing. Even now the timber props carry chalk tallies of the shifts that went down on the morning of the collapse, and no one has had the heart to scrub them off.',
      'Since the kindling the mine has become a half-pilgrimage site: surface families ride the lift down to stand in the lower gallery and watch the violet lamp-light run along the quartz seams, then ride back up in silence.',
    ],
    tags: ['Mine', 'Surface', 'Delvers'],
    mapId: MAP,
    pinId: 'pin-kharad-mine',
    npcIds: ['npc-tamsin-brack', 'npc-ysolde-ghostlamp'],
    factionIds: [
      'faction-kharad-delvers-union',
      'faction-hold-ghostlamp',
    ],
    encounterIds: [
      'encounter-resonant-fault-collapse',
      'encounter-quartz-spur-bridge',
    ],
    questIds: ['quest-rescue-survey-crew'],
    handoutIds: [
      'handout-survey-crew-log',
      'handout-delvers-union-roll',
      'lore-ghostlamp-lamp-liturgy',
    ],
    notes: 'The party started here and was welcomed back here after the finale.',
  },
  {
    id: 'location-lift-head-shrine',
    campaignId: C,
    name: 'The Lift-Head Shrine',
    type: 'landmark',
    shortDescription:
      'A miners’ shrine at the top of the Kharad lift, now carrying every name the mine has lost.',
    description: [
      'A low stone alcove beside the lift cage, lit by a single violet lamp. Brass plates line the walls, each engraved with a miner’s name and the year they went below and did not return.',
      'For three generations the shrine held eighty-one plates. Since the kindling, Tamsin Brack and the Kindled Congregation have added another forty-two, including names the Union had left off for reasons of shame, politics or paperwork.',
      'Hale-of-Echoes sits here most mornings before the first shift, not praying so much as listening. The lift cable hums in the key of the fault, which Yarrow says is “the only honest tuning in the mine.”',
    ],
    tags: ['Shrine', 'Memorial', 'Miners'],
    parentLocationId: 'location-kharad-mine',
    mapId: MAP,
    pinId: 'pin-lift-head-shrine',
    npcIds: ['npc-tamsin-brack', 'npc-gruvna-brightcut'],
    factionIds: [
      'faction-kindled-congregation',
      'faction-hold-ghostlamp',
      'faction-kharad-delvers-union',
    ],
    encounterIds: [],
    questIds: ['quest-light-the-evening-shrine'],
    handoutIds: ['handout-delvers-union-roll', 'lore-ghostlamp-lamp-liturgy'],
    notes:
      'Good place for a quiet roleplay scene; any PC may add a name to the wall at no cost.',
  },
  {
    id: 'location-singing-fault',
    campaignId: C,
    name: 'The Singing Fault',
    type: 'landmark',
    shortDescription:
      'A crystalline crack that answers voices a minute before they speak.',
    description: [
      'Quartz spurs hum a low chord that shifts as anyone approaches. The echoes are always slightly ahead of the speaker.',
      'Yarrow Stonesinger can name each spur by its pitch and warns which ones will not hold weight.',
      'The fault drops two hundred feet in a single ragged stair of quartz, with a natural span of crystal halfway down that the survey crews call the Bridge. It holds if you sing the right note, and does not if you sing the wrong one.',
      'The echoes ran a minute ahead of the speaker. Scholars at the Collegium now believe the fault is a kind of ear: the engine listened to the surface, and what it heard first it answered first.',
    ],
    tags: ['Fault', 'Hazard', 'Echoes'],
    parentLocationId: 'location-kharad-mine',
    mapId: MAP,
    pinId: 'pin-singing-fault',
    npcIds: ['npc-yarrow-stonesinger'],
    factionIds: ['faction-kharad-delvers-union'],
    encounterIds: [
      'encounter-resonant-fault-collapse',
      'encounter-quartz-spur-bridge',
    ],
    questIds: ['quest-rescue-survey-crew'],
    handoutIds: ['handout-survey-crew-log'],
    notes: 'The echoes fell silent once the deep sun was kindled.',
  },
  {
    id: 'location-inverted-observatory',
    campaignId: C,
    name: 'The Inverted Observatory',
    type: 'landmark',
    shortDescription:
      'An ancient observatory whose chart shows caverns instead of stars.',
    description: [
      'Domed and open to solid rock, the observatory’s lenses point down. The chart table glows faintly violet.',
      'Pell Quartz spent nights copying the chart, insisting every line was deliberate.',
      'The dome is not glass but a single sheet of faceted quartz that bends the glow of the chart table into a slow wheel of light on the ceiling. Scholars lie on their backs on the floor to read it.',
      'The chart’s rim carries a faint eighth mark that nobody has been able to explain. The Collegium keeps the rubbing under glass in the Chalk Gallery, and the original table remains lit all night in case it changes.',
    ],
    tags: ['Observatory', 'Discovery', 'Ancient'],
    mapId: MAP,
    pinId: 'pin-inverted-observatory',
    npcIds: ['npc-pell-quartz', 'npc-yarrow-stonesinger'],
    factionIds: ['faction-chalkline-collegium'],
    encounterIds: ['encounter-survey-crew-defense'],
    questIds: ['quest-read-inverted-chart', 'quest-the-eighth-light'],
    handoutIds: [
      'handout-inverted-star-chart',
      'lore-star-chart-legend',
      'handout-eighth-point-rubbing',
    ],
    notes: 'Now a Collegium research hall open to all seven holds.',
  },
  {
    id: 'location-chalk-gallery',
    campaignId: C,
    name: 'The Chalk Gallery',
    type: 'district',
    shortDescription:
      'The Collegium’s working gallery above the observatory, where every survey of the deep is chalked on the walls.',
    description: [
      'A long vaulted hall whose walls are a continuous palimpsest of surveyors’ chalk: tunnel sketches, correction marks, arguments in the margins and a few outright insults. The Collegium refuses to whitewash any of it.',
      'Dagna keeps a table by the east window. Her original paper, the one that got her disgraced, hangs on the wall in a plain frame with a single word chalked beneath it: “Right.”',
      'The rubbing of the eighth point hangs in a glass case at the far end, lit by a plain lamp. Scholars stand in front of it in silence the way people stand in front of a grave.',
    ],
    tags: ['Collegium', 'Research', 'Chalk'],
    parentLocationId: 'location-inverted-observatory',
    mapId: MAP,
    pinId: 'pin-chalk-gallery',
    npcIds: ['npc-pell-quartz'],
    factionIds: ['faction-chalkline-collegium'],
    encounterIds: [],
    questIds: ['quest-the-eighth-light'],
    handoutIds: ['handout-eighth-point-rubbing', 'lore-star-chart-legend'],
    notes: 'A natural research hub for any sequel; Pell will always open the door.',
  },
  {
    id: 'location-broken-gate-hall',
    campaignId: C,
    name: 'Hall of the Broken Gate',
    type: 'government',
    shortDescription:
      'Where the Concord meets before a sealed and fractured transit gate.',
    description: [
      'Seven carved seats face a cracked arch of dark metal. Delegates bicker beneath banners hung in order of precedence.',
      'Magistrate Ilsa Vaunt keeps the charter on a lectern beside the gate.',
      'Each seat carries its hold’s seal and a different style of cushion, which Kjeld Bellows claims is the real source of the Concord’s tension. The hall’s acoustics carry any raised voice to every seat at once, so quarrels have to be conducted in whispers or not at all.',
      'The gate itself is a ten-foot arch of dark metal with a hairline crack from the keystone to the floor. It does not respond to any touch, key or spell, only to a named custodian.',
    ],
    tags: ['Council', 'Politics', 'Gate'],
    mapId: MAP,
    pinId: 'pin-broken-gate-hall',
    npcIds: [
      'npc-hrolda-ironvein',
      'npc-oskar-deepfire',
      'npc-ilsa-vaunt',
      'npc-brondi-greywall',
      'npc-sunniva-thrum',
      'npc-orla-silvervein',
      'npc-bodil-marrowsong',
      'npc-kjeld-bellows',
      'npc-ysolde-ghostlamp',
    ],
    factionIds: [
      'faction-seven-hold-concord',
      'faction-duskforge-hold',
      'faction-hold-greywarden',
      'faction-hold-thrumhall',
      'faction-hold-highvein',
      'faction-hold-marrowstone',
      'faction-hold-bellowmere',
      'faction-hold-ghostlamp',
    ],
    encounterIds: [
      'encounter-council-at-broken-gate',
      'encounter-banquet-of-seven-knives',
    ],
    questIds: [
      'quest-open-the-transit-gate',
      'quest-sabotage-for-the-holds',
      'quest-read-inverted-chart',
      'quest-turn-the-tolls',
    ],
    handoutIds: [
      'lore-seven-holds-charter',
      'handout-concord-writ-of-custodianship',
      'lore-seven-holds-gazetteer',
      'handout-bellowmere-kitchens-compact',
    ],
    notes: 'The gate answers only to its custodian, Dagna.',
  },
  {
    id: 'location-transit-line',
    campaignId: C,
    name: 'The Transit Line',
    type: 'landmark',
    shortDescription:
      'A chain of abandoned stations ending at Meridian Station.',
    description: [
      'Rails hum with unstable gravity. Each station rearranges its platform when the line is disturbed.',
      'Meridian Station is the last stop before the vault and the natural place for an ambush.',
      'The line runs in seven spurs, one for each hold, with a safety break cut into each that no repair has ever mended. The party ran the whole route in a single night, which Sunniva still says is not possible.',
      'After the finale the line was sealed. Each switch now answers to a three-key lock, and the single working timetable is posted in the switchyard so that no one can claim they were never told.',
    ],
    tags: ['Rail', 'Chase', 'Hazard'],
    mapId: MAP,
    pinId: 'pin-transit-line',
    npcIds: ['npc-vessa-ordrun', 'npc-sunniva-thrum'],
    factionIds: [
      'faction-ardent-deep-company',
      'faction-hold-thrumhall',
    ],
    encounterIds: [
      'encounter-transit-line-chase',
      'encounter-ordrun-station-ambush',
      'encounter-thrumhall-switchyard',
    ],
    questIds: [
      'quest-open-the-transit-gate',
      'quest-race-ordrun-to-the-engine',
      'quest-seal-the-transit-line',
    ],
    handoutIds: [
      'handout-ordrun-sealed-orders',
      'handout-thrumhall-line-ledger',
    ],
    notes: 'The line was sealed after the finale to prevent another race.',
  },
  {
    id: 'location-thrumhall-switchyard',
    campaignId: C,
    name: 'The Thrumhall Switchyard',
    type: 'landmark',
    shortDescription:
      'A vast rail-yard of rotating platforms where the line’s timetable is kept in iron.',
    description: [
      'A gantry-ringed pit where seven rails converge on a ring of turntables, each large enough to carry a full train. Bells hang from every gantry and ring the hour in Thrumhall’s old cipher.',
      'The timetable is cast into the floor plates in raised iron. A character who can read it knows what the platforms will do before they do it.',
      'Sunniva Thrum keeps a watching-room at the east gantry with a brass speaking-horn and a standing order to be woken for any train that is not hers.',
    ],
    tags: ['Rail', 'Thrumhall', 'Puzzle'],
    parentLocationId: 'location-transit-line',
    mapId: MAP,
    pinId: 'pin-thrumhall-switchyard',
    npcIds: ['npc-sunniva-thrum'],
    factionIds: ['faction-hold-thrumhall'],
    encounterIds: ['encounter-thrumhall-switchyard'],
    questIds: [
      'quest-open-the-transit-gate',
      'quest-seal-the-transit-line',
    ],
    handoutIds: ['handout-thrumhall-line-ledger'],
    notes: 'A good fallback setpiece if the party wants one more chase.',
  },
  {
    id: 'location-meridian-station',
    campaignId: C,
    name: 'Meridian Station',
    type: 'landmark',
    shortDescription:
      'The last station before the vault: a vaulted platform where Ordrun sprang her ambush.',
    description: [
      'A circular platform with seven arches, each leading to a different spur. A chandelier of dark quartz hangs in the middle, unlit since the station was built.',
      'This is where the party fought the Ardent Deep Company, and where Ketta Rawl left her letter in a satchel and walked into the dark.',
      'Since the sealing the platform has been closed with a three-key door. The scorch marks from the ambush are still visible on the floor, and a chalk heart that Ketta drew on the wall by the stairs has been left alone.',
    ],
    tags: ['Rail', 'Ambush', 'Sealed'],
    parentLocationId: 'location-transit-line',
    mapId: MAP,
    pinId: 'pin-meridian-station',
    npcIds: ['npc-ketta-rawl', 'npc-vessa-ordrun'],
    factionIds: [
      'faction-ardent-deep-company',
      'faction-hold-thrumhall',
    ],
    encounterIds: [
      'encounter-ordrun-station-ambush',
      'encounter-ketta-pursuit',
    ],
    questIds: [
      'quest-race-ordrun-to-the-engine',
      'quest-the-deserters-bargain',
      'quest-seal-the-transit-line',
    ],
    handoutIds: ['handout-ketta-rawls-letter'],
    notes: 'The place to hide a deserter, or a secret.',
  },
  {
    id: 'location-zero-gravity-vault',
    campaignId: C,
    name: 'The Zero-Gravity Vault',
    type: 'landmark',
    shortDescription:
      'A vast chamber of floating fragments from the seven holds’ history.',
    description: [
      'Shards of carved stone drift in the dark, each replaying a scene from a hold’s past when touched.',
      'Gargoyle statues cling to the larger fragments and wake when anyone crosses too close.',
      'The shards replay not just scenes but sounds: a forge-song from Duskforge, a lamp-lighter’s call from Ghostlamp, the low bell of Marrowstone. Characters who linger find themselves humming without meaning to.',
      'Bodil Marrowsong catalogued seventy-one shards before the kindling and describes them as “not history, but intention: how each hold wished to be remembered.”',
    ],
    tags: ['Vault', 'Zero-g', 'History'],
    mapId: MAP,
    pinId: 'pin-zero-gravity-vault',
    npcIds: ['npc-the-astronomer', 'npc-bodil-marrowsong'],
    factionIds: [
      'faction-astronomers-watch',
      'faction-hold-marrowstone',
    ],
    encounterIds: ['encounter-zero-gravity-vault'],
    questIds: [
      'quest-race-ordrun-to-the-engine',
      'quest-fate-of-the-vessel',
      'quest-bring-the-ancestors-home',
    ],
    handoutIds: ['handout-astronomers-final-message'],
    notes: 'Its fragments now hang as memorials in the Commons.',
  },
  {
    id: 'location-engine-heart',
    campaignId: C,
    name: 'The Engine Heart',
    type: 'landmark',
    shortDescription:
      'The chamber of three alignable rings, now home to the deep sun.',
    description: [
      'Three concentric rings turn around a vessel the size of a small fortress. The rings’ alignment decides its fate.',
      'After the finale a soft golden sun hangs in the chamber, warming the deep caverns beyond.',
      'The deep sun is not a flame but a slow spin of light inside a golden casing. It gives off warmth but no smoke, and the air in the chamber carries a faint, sweet smell like rain on hot stone.',
      'The Astronomer’s rings still turn, but slowly, a gesture rather than a mechanism. The seams in the casing occasionally flare with a violet glint that the Congregation calls “the sun breathing.”',
    ],
    tags: ['Finale', 'Rings', 'Deep sun'],
    mapId: MAP,
    pinId: 'pin-engine-heart',
    npcIds: ['npc-the-astronomer', 'npc-vessa-ordrun', 'npc-oskar-deepfire'],
    factionIds: [
      'faction-astronomers-watch',
      'faction-ardent-deep-company',
      'faction-duskforge-hold',
    ],
    encounterIds: [
      'encounter-astronomer-awakens',
      'encounter-fate-of-the-vessel',
      'encounter-deep-sun-flare',
    ],
    questIds: [
      'quest-fate-of-the-vessel',
      'quest-honor-the-seven-promises',
      'quest-light-the-evening-shrine',
    ],
    handoutIds: [
      'lore-star-engine-purpose',
      'lore-legacy-of-kharad',
      'lore-kindling-night-oral-history',
    ],
    notes: 'The Astronomer remains here as the deep sun’s steward.',
  },
  {
    id: 'location-berth-galleries',
    campaignId: C,
    name: 'The Berth Galleries',
    type: 'landmark',
    shortDescription:
      'Tiers of sleeper berths inside the vessel, each with an engraved lid and no one inside.',
    description: [
      'Forty thousand lids line the curved walls in rows that rise out of sight. Every lid is warm to the touch and engraved with a name in the builders’ script. Every berth beneath is empty.',
      'Bodil Marrowsong walks the rows with a bone-handled counting rod, tapping each lid and murmuring a name. She has counted four thousand so far and refuses to be hurried.',
      'The air is cold and smells of nothing. Footsteps make no echo. Hale-of-Echoes says that is the strangest part: a place that large should not be this quiet.',
    ],
    tags: ['Vessel', 'Mystery', 'Sleepers'],
    parentLocationId: 'location-engine-heart',
    mapId: MAP,
    pinId: 'pin-berth-galleries',
    npcIds: ['npc-bodil-marrowsong', 'npc-the-astronomer'],
    factionIds: [
      'faction-hold-marrowstone',
      'faction-astronomers-watch',
    ],
    encounterIds: [],
    questIds: [
      'quest-bring-the-ancestors-home',
      'quest-the-eighth-light',
    ],
    handoutIds: ['handout-marrowstone-sleeper-manifest'],
    notes:
      'Open thread: nobody knows where the sleepers went. Keep the lids warm in any sequel.',
  },
  {
    id: 'location-eighth-shaft',
    campaignId: C,
    name: 'The Eighth Shaft',
    type: 'landmark',
    shortDescription:
      'A sealed shaft beneath the engine heart, matching the unlabeled eighth point on the chart.',
    description: [
      'Behind the engine’s lowest ring is a circular hatch of the same dark metal as the gate, with a keyway that matches Nima’s inherited key. It has never opened, and the Astronomer has declined to say what lies below.',
      'Rubbings of the hatch show three tiny crescents arranged like the legs of a stool: the same mark that sits on the eighth point of the chart.',
      'Yarrow Stonesinger says the stone beneath the hatch hums at a pitch lower than any she has heard, and that it runs a heartbeat behind her own voice, not ahead of it.',
    ],
    tags: ['Sealed', 'Sequel hook', 'Mystery'],
    parentLocationId: 'location-engine-heart',
    mapId: MAP,
    pinId: 'pin-eighth-shaft',
    npcIds: ['npc-the-astronomer', 'npc-yarrow-stonesinger'],
    factionIds: [
      'faction-astronomers-watch',
      'faction-chalkline-collegium',
    ],
    encounterIds: ['encounter-eighth-shaft-descent'],
    questIds: ['quest-the-eighth-light'],
    handoutIds: ['handout-eighth-point-rubbing', 'handout-ashglass-key-letter'],
    notes:
      'Reserved for a sequel; nothing here has been run. Do not reveal its contents without a prepared descent.',
  },
  {
    id: 'location-kharad-commons',
    campaignId: C,
    name: 'The Commons of Seven Chalks',
    type: 'market',
    shortDescription:
      'The new gathering hall and market built beneath the deep sun.',
    description: [
      'Miners, scholars, and delegates share long tables in a hall lit by the deep sun’s glow.',
      'An evening bell tuned to the fault’s hum marks the end of each shift.',
      'Seventy-one memorial shards hang from the dome on bronze chains, each turning slowly and murmuring a scrap of its hold’s music. At night the hall sounds like seven choirs warming up in different rooms.',
      'Every table carries a chalk line down its middle: delegates sit on one side, miners on the other, and the chalk is wiped away at the start of each meal.',
    ],
    tags: ['Epilogue', 'Market', 'Legacy'],
    mapId: MAP,
    pinId: 'pin-kharad-commons',
    npcIds: [
      'npc-tamsin-brack',
      'npc-pell-quartz',
      'npc-hrolda-ironvein',
      'npc-ilsa-vaunt',
      'npc-kjeld-bellows',
      'npc-ketta-rawl',
      'npc-fennick-ashglass',
      'npc-gruvna-brightcut',
    ],
    factionIds: [
      'faction-seven-hold-concord',
      'faction-chalkline-collegium',
      'faction-kharad-delvers-union',
      'faction-hold-bellowmere',
    ],
    encounterIds: ['encounter-fate-of-the-vessel'],
    questIds: [
      'quest-honor-the-seven-promises',
      'quest-turn-the-tolls',
      'quest-bring-the-ancestors-home',
    ],
    handoutIds: [
      'handout-epilogue-proclamation',
      'lore-legacy-of-kharad',
      'handout-epilogue-letter-hrolda',
      'handout-bellowmere-kitchens-compact',
    ],
    notes: 'Epilogue location; each hero has an assigned seat.',
  },
  {
    id: 'location-highvein-counting-house',
    campaignId: C,
    name: 'The Highvein Counting House',
    type: 'market',
    shortDescription:
      'Highvein’s polished new counting house on the Commons’ east side, where every road is priced.',
    description: [
      'A handsome three-storey hall of dressed silver-veined stone, built in eleven weeks and already the busiest building in the Commons. A brass door-bell plays three notes whenever someone enters.',
      'The ground floor is a bright, welcoming exchange where miners can cash their shift tokens. The upper floors are a different place: reading rooms, locked cabinets, and a tall pair of doors at the back that no one has been allowed through.',
      'Orla Silvervein keeps a plain desk by the street window and greets every visitor by name. She has never once raised her voice.',
      'The tuning fork Nima carries has hummed every time she has walked past the back doors. Orla has noticed.',
    ],
    tags: ['Highvein', 'Commerce', 'Open thread'],
    parentLocationId: 'location-kharad-commons',
    mapId: MAP,
    pinId: 'pin-highvein-counting-house',
    npcIds: ['npc-orla-silvervein'],
    factionIds: ['faction-hold-highvein'],
    encounterIds: [],
    questIds: ['quest-turn-the-tolls', 'quest-the-eighth-light'],
    handoutIds: [
      'handout-highvein-toll-ledger',
      'handout-epilogue-letter-orla',
    ],
    notes:
      'Social intrigue site for the sequel; the sealed back doors are the hook.',
  },
  {
    id: 'location-evening-bell-shrine',
    campaignId: C,
    name: 'The Evening Bell Shrine',
    type: 'landmark',
    shortDescription:
      'A small open-air shrine above the Commons where the evening bell is rung by whoever finishes work last.',
    description: [
      'A rope, a bronze bell the size of a pot, and a stone shelf where visitors leave chalk, lamp-wicks or a sliver of bread. There is no door and no priest, though Gruvna Brightcut sweeps the steps every morning.',
      'The bell is tuned a half-tone beneath the fault’s hum and is rung at the end of every shift, not by an official but by whoever happens to be passing. The Commons has agreed that no one may be turned away from the rope.',
      'Hale-of-Echoes has made the shrine into something quieter than a temple: a place to stand and listen for the pitch that is not quite there.',
    ],
    tags: ['Shrine', 'Congregation', 'Commons'],
    parentLocationId: 'location-kharad-commons',
    mapId: MAP,
    pinId: 'pin-evening-bell-shrine',
    npcIds: ['npc-gruvna-brightcut', 'npc-yarrow-stonesinger'],
    factionIds: [
      'faction-kindled-congregation',
      'faction-hold-ghostlamp',
    ],
    encounterIds: [],
    questIds: ['quest-light-the-evening-shrine'],
    handoutIds: ['lore-kindling-night-oral-history'],
    notes: 'A natural quiet scene for an epilogue or a short reunion session.',
  },
];
