import type { CampaignMap, MapPin } from '../ashes-of-veyra/types';
import { KHARAD_CAMPAIGN_ID } from './campaign';

export const MAP_BURIED_CONSTELLATION_ID = 'map-buried-constellation';

/**
 * No Kharad-specific map artwork exists yet. Following the "do not fabricate
 * binary assets" rule, this reuses the existing Ashes of Veyra placeholder
 * image, which the map preparation view already loads for demo campaigns.
 */
export const KHARAD_MAP_IMAGE_PATH =
  '/demo/ashes-of-veyra/glass-harbor-map.png';

const allLocationIds = [
  'location-kharad-mine',
  'location-singing-fault',
  'location-inverted-observatory',
  'location-broken-gate-hall',
  'location-transit-line',
  'location-zero-gravity-vault',
  'location-engine-heart',
  'location-kharad-commons',
  'location-lift-head-shrine',
  'location-chalk-gallery',
  'location-thrumhall-switchyard',
  'location-meridian-station',
  'location-berth-galleries',
  'location-eighth-shaft',
  'location-highvein-counting-house',
  'location-evening-bell-shrine',
];

export const kharadMaps: CampaignMap[] = [
  {
    id: MAP_BURIED_CONSTELLATION_ID,
    campaignId: KHARAD_CAMPAIGN_ID,
    title: 'The Buried Constellation',
    description:
      'Cutaway map of Kharad and the seven-hold constellation, from the mine head down to the engine heart.',
    imagePath: KHARAD_MAP_IMAGE_PATH,
    locationIds: allLocationIds,
    layers: [
      {
        id: 'layer-kharad-locations',
        label: 'Locations',
        visibleByDefault: true,
        locationIds: allLocationIds,
      },
      {
        id: 'layer-kharad-encounters',
        label: 'Encounters',
        visibleByDefault: true,
        locationIds: allLocationIds.filter(
          (id) => id !== 'location-kharad-mine',
        ),
      },
      {
        id: 'layer-kharad-npcs',
        label: 'NPCs',
        visibleByDefault: true,
        locationIds: allLocationIds,
      },
      {
        id: 'layer-kharad-notes',
        label: 'Notes',
        visibleByDefault: true,
        locationIds: [
          'location-engine-heart',
          'location-kharad-commons',
          'location-berth-galleries',
          'location-eighth-shaft',
          'location-highvein-counting-house',
        ],
      },
      {
        id: 'layer-kharad-environment',
        label: 'Environment',
        visibleByDefault: true,
        locationIds: [
          'location-singing-fault',
          'location-zero-gravity-vault',
          'location-transit-line',
          'location-thrumhall-switchyard',
          'location-meridian-station',
        ],
      },
      {
        id: 'layer-kharad-grid',
        label: 'Grid',
        visibleByDefault: false,
        locationIds: [],
      },
      {
        id: 'layer-kharad-labels',
        label: 'Labels',
        visibleByDefault: false,
        locationIds: [],
      },
      {
        id: 'layer-kharad-fog-of-war',
        label: 'Fog of War',
        visibleByDefault: false,
        locationIds: [],
      },
    ],
  },
];

const standardLayers = [
  'layer-kharad-locations',
  'layer-kharad-encounters',
  'layer-kharad-npcs',
];

export const kharadMapPins: MapPin[] = [
  {
    id: 'pin-kharad-mine',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-kharad-mine',
    label: 'Kharad Mine',
    order: 1,
    x: 0.5,
    y: 0.1,
    layerIds: ['layer-kharad-locations', 'layer-kharad-npcs'],
    linkedObjectIds: ['npc-tamsin-brack', 'handout-survey-crew-log'],
    selectedByDefault: false,
  },
  {
    id: 'pin-singing-fault',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-singing-fault',
    label: 'The Singing Fault',
    order: 2,
    x: 0.3,
    y: 0.25,
    layerIds: [...standardLayers, 'layer-kharad-environment'],
    linkedObjectIds: [
      'encounter-resonant-fault-collapse',
      'npc-yarrow-stonesinger',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-inverted-observatory',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-inverted-observatory',
    label: 'The Inverted Observatory',
    order: 3,
    x: 0.68,
    y: 0.28,
    layerIds: standardLayers,
    linkedObjectIds: [
      'encounter-survey-crew-defense',
      'handout-inverted-star-chart',
      'npc-pell-quartz',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-broken-gate-hall',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-broken-gate-hall',
    label: 'Hall of the Broken Gate',
    order: 4,
    x: 0.42,
    y: 0.45,
    layerIds: standardLayers,
    linkedObjectIds: [
      'encounter-council-at-broken-gate',
      'npc-hrolda-ironvein',
      'handout-concord-writ-of-custodianship',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-transit-line',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-transit-line',
    label: 'The Transit Line',
    order: 5,
    x: 0.72,
    y: 0.55,
    layerIds: [...standardLayers, 'layer-kharad-environment'],
    linkedObjectIds: [
      'encounter-transit-line-chase',
      'encounter-ordrun-station-ambush',
      'npc-vessa-ordrun',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-zero-gravity-vault',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-zero-gravity-vault',
    label: 'The Zero-Gravity Vault',
    order: 6,
    x: 0.3,
    y: 0.7,
    layerIds: [...standardLayers, 'layer-kharad-environment'],
    linkedObjectIds: ['encounter-zero-gravity-vault', 'npc-the-astronomer'],
    selectedByDefault: false,
  },
  {
    id: 'pin-engine-heart',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-engine-heart',
    label: 'The Engine Heart',
    order: 7,
    x: 0.5,
    y: 0.86,
    layerIds: [...standardLayers, 'layer-kharad-notes'],
    linkedObjectIds: [
      'encounter-astronomer-awakens',
      'encounter-fate-of-the-vessel',
      'lore-star-engine-purpose',
    ],
    selectedByDefault: true,
  },
  {
    id: 'pin-kharad-commons',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-kharad-commons',
    label: 'The Commons of Seven Chalks',
    order: 8,
    x: 0.82,
    y: 0.82,
    layerIds: [...standardLayers, 'layer-kharad-notes'],
    linkedObjectIds: [
      'handout-epilogue-proclamation',
      'lore-legacy-of-kharad',
      'npc-ilsa-vaunt',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-lift-head-shrine',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-lift-head-shrine',
    label: 'The Lift-Head Shrine',
    order: 9,
    x: 0.58,
    y: 0.15,
    layerIds: ['layer-kharad-locations', 'layer-kharad-npcs'],
    linkedObjectIds: ['npc-gruvna-brightcut', 'handout-delvers-union-roll'],
    selectedByDefault: false,
  },
  {
    id: 'pin-chalk-gallery',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-chalk-gallery',
    label: 'The Chalk Gallery',
    order: 10,
    x: 0.62,
    y: 0.37,
    layerIds: ['layer-kharad-locations', 'layer-kharad-npcs'],
    linkedObjectIds: ['npc-pell-quartz', 'handout-eighth-point-rubbing'],
    selectedByDefault: false,
  },
  {
    id: 'pin-thrumhall-switchyard',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-thrumhall-switchyard',
    label: 'The Thrumhall Switchyard',
    order: 11,
    x: 0.84,
    y: 0.47,
    layerIds: [...standardLayers, 'layer-kharad-environment'],
    linkedObjectIds: [
      'encounter-thrumhall-switchyard',
      'npc-sunniva-thrum',
      'handout-thrumhall-line-ledger',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-meridian-station',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-meridian-station',
    label: 'Meridian Station',
    order: 12,
    x: 0.86,
    y: 0.65,
    layerIds: [...standardLayers, 'layer-kharad-environment'],
    linkedObjectIds: [
      'encounter-ketta-pursuit',
      'npc-ketta-rawl',
      'handout-ketta-rawls-letter',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-berth-galleries',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-berth-galleries',
    label: 'The Berth Galleries',
    order: 13,
    x: 0.36,
    y: 0.92,
    layerIds: ['layer-kharad-locations', 'layer-kharad-npcs', 'layer-kharad-notes'],
    linkedObjectIds: [
      'npc-bodil-marrowsong',
      'handout-marrowstone-sleeper-manifest',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-eighth-shaft',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-eighth-shaft',
    label: 'The Eighth Shaft',
    order: 14,
    x: 0.5,
    y: 0.96,
    layerIds: [...standardLayers, 'layer-kharad-notes'],
    linkedObjectIds: [
      'encounter-eighth-shaft-descent',
      'quest-the-eighth-light',
      'handout-eighth-point-rubbing',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-highvein-counting-house',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-highvein-counting-house',
    label: 'The Highvein Counting House',
    order: 15,
    x: 0.7,
    y: 0.74,
    layerIds: ['layer-kharad-locations', 'layer-kharad-npcs', 'layer-kharad-notes'],
    linkedObjectIds: [
      'npc-orla-silvervein',
      'handout-highvein-toll-ledger',
      'quest-turn-the-tolls',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-evening-bell-shrine',
    mapId: MAP_BURIED_CONSTELLATION_ID,
    locationId: 'location-evening-bell-shrine',
    label: 'The Evening Bell Shrine',
    order: 16,
    x: 0.92,
    y: 0.76,
    layerIds: ['layer-kharad-locations', 'layer-kharad-npcs'],
    linkedObjectIds: [
      'npc-gruvna-brightcut',
      'lore-kindling-night-oral-history',
    ],
    selectedByDefault: false,
  },
];
