import type { CampaignQuest, QuestObjective } from '../ashes-of-veyra/types';
import { KHARAD_CAMPAIGN_ID as C } from './campaign';

const S1 = `${C}-session-1`;
const S2 = `${C}-session-2`;
const S3 = `${C}-session-3`;

/**
 * The shared quest model has no `failed` or `abandoned` state, so outcomes are
 * mapped as follows: resolved quests are `complete`; an abandoned quest is
 * `on-hold`. A failed objective is `blocked`; an abandoned one is `pending`.
 * Each summary opens with the real outcome.
 */
export const kharadQuests: CampaignQuest[] = [
  {
    id: 'quest-rescue-survey-crew',
    campaignId: C,
    title: 'Rescue the Survey Crew',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: all eleven trapped miners and surveyors were pulled out of the collapsing singing fault.',
    giverNpcId: 'npc-tamsin-brack',
    factionIds: ['faction-kharad-delvers-union'],
    sessionIds: [S1],
    locationIds: ['location-kharad-mine', 'location-singing-fault'],
    objectiveIds: [
      'objective-locate-trapped-crews',
      'objective-stabilize-the-fault',
      'objective-evacuate-survivors',
    ],
    resolution:
      'All eleven were carried out alive. Yarrow held the fault’s chord steady with her voice while Orik shouldered the last beam, and Tamsin made the Union promise that no crew would ever again be left below on a hold’s schedule.',
  },
  {
    id: 'quest-read-inverted-chart',
    campaignId: C,
    title: 'Read the Inverted Star Chart',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: the chart proved to be a map of seven holds and the star engine beneath them, and each hold seal was matched to its owner.',
    giverNpcId: 'npc-pell-quartz',
    factionIds: ['faction-chalkline-collegium'],
    sessionIds: [S1, S2],
    locationIds: ['location-inverted-observatory', 'location-broken-gate-hall'],
    objectiveIds: [
      'objective-copy-the-chart',
      'objective-identify-seven-holds',
      'objective-match-hold-seals',
    ],
    resolution:
      'Pell Quartz’s copy proved the chart was a map of seven holds around a newly woken star. Each seal was matched to its delegation; the overwritten Duskforge seal became the party’s first evidence that someone had edited history.',
  },
  {
    id: 'quest-open-the-transit-gate',
    campaignId: C,
    title: 'Open the Transit Gate',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: the Concord agreed to open the gate, the party ran the unstable line, and Dagna accepted custodianship.',
    giverNpcId: 'npc-hrolda-ironvein',
    factionIds: ['faction-seven-hold-concord'],
    sessionIds: [S2],
    locationIds: ['location-broken-gate-hall', 'location-transit-line'],
    objectiveIds: [
      'objective-secure-concord-consensus',
      'objective-run-transit-line',
      'objective-name-the-custodian',
    ],
    resolution:
      'The Concord voted four to three to open the gate, with Bellowmere’s swing vote bought by a promise of shared kitchens. Dagna signed the Writ of Custodianship and the gate answered to her alone.',
  },
  {
    id: 'quest-sabotage-for-the-holds',
    campaignId: C,
    title: 'Sabotage for the Holds',
    status: 'on-hold',
    priority: 'low',
    summary:
      'Abandoned: two delegates privately asked the party to sabotage a rival, and the party declined both and reported neither.',
    giverNpcId: 'npc-oskar-deepfire',
    factionIds: ['faction-duskforge-hold', 'faction-seven-hold-concord'],
    sessionIds: [S2],
    locationIds: ['location-broken-gate-hall'],
    objectiveIds: [
      'objective-hear-secret-requests',
      'objective-sabotage-a-rival',
    ],
    resolution:
      'Neither Oskar Deepfire nor Orla Silvervein got their sabotage. The party refused both in private and reported neither in public, which kept the Concord intact and left two delegates owing nothing and resenting it.',
  },
  {
    id: 'quest-race-ordrun-to-the-engine',
    campaignId: C,
    title: 'Race Ordrun to the Engine',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: the party beat the Ardent Deep Company through Meridian Station and reached the engine first.',
    giverNpcId: 'npc-hrolda-ironvein',
    factionIds: ['faction-ardent-deep-company'],
    sessionIds: [S2, S3],
    locationIds: ['location-transit-line', 'location-zero-gravity-vault'],
    objectiveIds: [
      'objective-reach-meridian-station',
      'objective-recover-sealed-orders',
      'objective-reach-engine-first',
    ],
    resolution:
      'The party reached the engine ahead of the Company by a handful of minutes. Ordrun’s sealed orders, left in the courier’s satchel, proved the Company meant to bind the vessel to its own command word.',
  },
  {
    id: 'quest-fate-of-the-vessel',
    campaignId: C,
    title: 'The Fate of the Vessel',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: rather than launch or bury it, the party kindled the vessel into a deep sun and the Astronomer stood down.',
    giverNpcId: 'npc-the-astronomer',
    factionIds: ['faction-astronomers-watch', 'faction-chalkline-collegium'],
    sessionIds: [S3],
    locationIds: ['location-zero-gravity-vault', 'location-engine-heart'],
    objectiveIds: [
      'objective-align-the-rings',
      'objective-name-a-shared-purpose',
      'objective-choose-the-fate',
    ],
    resolution:
      'Once the party named a shared purpose, the Astronomer lowered its rings. The vessel was kindled into a deep sun that neither launches nor burns, and the guardian remained as its steward.',
  },
  {
    id: 'quest-honor-the-seven-promises',
    campaignId: C,
    title: 'Honor the Seven Promises',
    status: 'complete',
    priority: 'medium',
    summary:
      'Closed out: five of the six promises made to the holds were kept; the weapon promised to Duskforge was refused.',
    giverNpcId: 'npc-ilsa-vaunt',
    factionIds: [
      'faction-seven-hold-concord',
      'faction-kharad-delvers-union',
      'faction-duskforge-hold',
    ],
    sessionIds: [S3],
    locationIds: ['location-engine-heart', 'location-kharad-commons'],
    objectiveIds: [
      'objective-tally-the-promises',
      'objective-deliver-duskforge-weapon',
      'objective-seat-the-commons',
    ],
    resolution:
      'Five of the six promises were kept in full. The sixth, a weapon for Hold Duskforge, was refused openly and recorded in the Commons charter; Oskar left the dedication early and has not signed anything since.',
  },
  {
    id: 'quest-seal-the-transit-line',
    campaignId: C,
    title: 'Seal the Transit Line',
    status: 'complete',
    priority: 'medium',
    summary:
      'Completed: after the race, Thrumhall railwrights refit the builders’ safety breaks, shut Meridian Station, and locked the line so it can only run with the custodian’s consent.',
    giverNpcId: 'npc-sunniva-thrum',
    factionIds: [
      'faction-hold-thrumhall',
      'faction-hold-greywarden',
      'faction-seven-hold-concord',
    ],
    sessionIds: [S3],
    locationIds: [
      'location-transit-line',
      'location-thrumhall-switchyard',
      'location-meridian-station',
    ],
    objectiveIds: [
      'objective-survey-the-rail-damage',
      'objective-refit-the-safety-breaks',
      'objective-seal-meridian-station',
    ],
    resolution:
      'The line is locked. Every switch now answers to a three-key lock held by Thrumhall, Greywarden and Dagna; Sunniva framed the old timetable and hung it in the switchyard, grudgingly crediting “the quick ones who broke it first”.',
  },
  {
    id: 'quest-bring-the-ancestors-home',
    campaignId: C,
    title: 'Bring the Ancestors Home',
    status: 'complete',
    priority: 'medium',
    summary:
      'Completed: Marrowstone’s memorial rite was carried out for the vault’s drifting history shards, which now hang in the Commons; the question of who the berths held was left open.',
    giverNpcId: 'npc-bodil-marrowsong',
    factionIds: ['faction-hold-marrowstone', 'faction-chalkline-collegium'],
    sessionIds: [S3],
    locationIds: [
      'location-zero-gravity-vault',
      'location-berth-galleries',
      'location-kharad-commons',
    ],
    objectiveIds: [
      'objective-gather-the-memorial-shards',
      'objective-count-the-berths',
      'objective-hang-the-shards',
    ],
    resolution:
      'Seventy-one shards were carried up and hung under the Commons’ dome, each named for the hold whose story it replays. Bodil read the rite of rest over all of them, and left the berths themselves unsealed “until I know what I am burying”.',
  },
  {
    id: 'quest-the-deserters-bargain',
    campaignId: C,
    title: 'The Deserter’s Bargain',
    status: 'complete',
    priority: 'low',
    summary:
      'Completed: Ordrun’s courier Ketta Rawl was hidden from the Company’s knife-squads and traded her testimony for a Concord pardon.',
    giverNpcId: 'npc-ketta-rawl',
    factionIds: ['faction-ardent-deep-company', 'faction-seven-hold-concord'],
    sessionIds: [S2, S3],
    locationIds: [
      'location-meridian-station',
      'location-transit-line',
      'location-kharad-commons',
    ],
    objectiveIds: [
      'objective-hide-the-courier',
      'objective-record-the-testimony',
      'objective-win-the-pardon',
    ],
    resolution:
      'Ketta testified before Ilsa Vaunt that the marshal’s command word was written for “a custodian who will not be asked”. Her pardon was entered in the Commons registry, and she now trims lamp wicks under a name only the party knows.',
  },
  {
    id: 'quest-light-the-evening-shrine',
    campaignId: C,
    title: 'Light the Evening Shrine',
    status: 'complete',
    priority: 'low',
    summary:
      'Completed: Hale-of-Echoes and Echo-Prior Gruvna carried a flame from the deep sun, tuned the evening bell to the fault’s hum, and lit the shrine above the Commons.',
    giverNpcId: 'npc-gruvna-brightcut',
    factionIds: [
      'faction-kindled-congregation',
      'faction-hold-ghostlamp',
      'faction-kharad-delvers-union',
    ],
    sessionIds: [S3],
    locationIds: [
      'location-evening-bell-shrine',
      'location-lift-head-shrine',
      'location-kharad-commons',
    ],
    objectiveIds: [
      'objective-carry-the-deep-flame',
      'objective-tune-the-evening-bell',
      'objective-name-the-lost-miners',
    ],
    resolution:
      'The first evening bell rang a half-tone under the fault’s hum, which Yarrow says is exactly right. The lift-head shrine now carries the names of every miner lost at Kharad, including three that Tamsin had never been able to bring herself to write down.',
  },
  {
    id: 'quest-turn-the-tolls',
    campaignId: C,
    title: 'Turn the Tolls',
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Open thread: Highvein has begun charging the Commons a lamp, bread and bell toll; the Union wants it stopped and the party never got to the Concord vote.',
    giverNpcId: 'npc-tamsin-brack',
    factionIds: [
      'faction-hold-highvein',
      'faction-kharad-delvers-union',
      'faction-hold-thrumhall',
      'faction-hold-bellowmere',
    ],
    sessionIds: [S3],
    locationIds: [
      'location-highvein-counting-house',
      'location-kharad-commons',
    ],
    objectiveIds: [
      'objective-read-the-toll-ledger',
      'objective-bring-tolls-to-the-concord',
      'objective-seat-a-miners-auditor',
    ],
  },
  {
    id: 'quest-the-eighth-light',
    campaignId: C,
    title: 'The Eighth Light',
    status: 'on-hold',
    priority: 'high',
    summary:
      'Sequel hook: a faint eighth point on the chart lies beneath the engine, the sleeper berths were empty, and Nima’s second key hums toward Highvein.',
    giverNpcId: 'npc-pell-quartz',
    factionIds: [
      'faction-chalkline-collegium',
      'faction-hold-marrowstone',
      'faction-astronomers-watch',
    ],
    sessionIds: [S3],
    locationIds: [
      'location-eighth-shaft',
      'location-engine-heart',
      'location-berth-galleries',
    ],
    objectiveIds: [
      'objective-copy-the-eighth-point',
      'objective-account-for-the-sleepers',
      'objective-match-the-second-key',
      'objective-descend-the-eighth-shaft',
    ],
  },
];

export const kharadQuestObjectives: QuestObjective[] = [
  {
    id: 'objective-locate-trapped-crews',
    questId: 'quest-rescue-survey-crew',
    order: 1,
    title: 'Locate the trapped crews by their echoes',
    status: 'complete',
    clueIds: ['clue-echoes-run-early'],
    locationIds: ['location-singing-fault'],
  },
  {
    id: 'objective-stabilize-the-fault',
    questId: 'quest-rescue-survey-crew',
    order: 2,
    title: 'Stabilize the resonating fault',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-singing-fault'],
  },
  {
    id: 'objective-evacuate-survivors',
    questId: 'quest-rescue-survey-crew',
    order: 3,
    title: 'Evacuate the survivors to Kharad',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-mine'],
  },
  {
    id: 'objective-copy-the-chart',
    questId: 'quest-read-inverted-chart',
    order: 1,
    title: 'Copy the inverted star chart',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-inverted-observatory'],
  },
  {
    id: 'objective-identify-seven-holds',
    questId: 'quest-read-inverted-chart',
    order: 2,
    title: 'Identify the seven holds on the chart',
    status: 'complete',
    clueIds: ['clue-inverted-constellation'],
    locationIds: ['location-inverted-observatory'],
  },
  {
    id: 'objective-match-hold-seals',
    questId: 'quest-read-inverted-chart',
    order: 3,
    title: 'Match each hold seal to its delegate',
    status: 'complete',
    clueIds: ['clue-seven-hold-seals'],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-secure-concord-consensus',
    questId: 'quest-open-the-transit-gate',
    order: 1,
    title: 'Win a Concord majority to open the gate',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-run-transit-line',
    questId: 'quest-open-the-transit-gate',
    order: 2,
    title: 'Run the unstable transit line',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-transit-line'],
  },
  {
    id: 'objective-name-the-custodian',
    questId: 'quest-open-the-transit-gate',
    order: 3,
    title: 'Name a custodian for the engine',
    status: 'complete',
    clueIds: ['clue-gate-custodian-oath'],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-hear-secret-requests',
    questId: 'quest-sabotage-for-the-holds',
    order: 1,
    title: 'Hear the delegates’ private requests',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-sabotage-a-rival',
    questId: 'quest-sabotage-for-the-holds',
    order: 2,
    title: 'Sabotage a rival delegation',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-reach-meridian-station',
    questId: 'quest-race-ordrun-to-the-engine',
    order: 1,
    title: 'Reach Meridian Station ahead of Ordrun',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-transit-line'],
  },
  {
    id: 'objective-recover-sealed-orders',
    questId: 'quest-race-ordrun-to-the-engine',
    order: 2,
    title: 'Recover the marshal’s sealed orders',
    status: 'complete',
    clueIds: ['clue-ordrun-orders'],
    locationIds: ['location-transit-line'],
  },
  {
    id: 'objective-reach-engine-first',
    questId: 'quest-race-ordrun-to-the-engine',
    order: 3,
    title: 'Reach the engine before the Ardent Company',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-zero-gravity-vault'],
  },
  {
    id: 'objective-align-the-rings',
    questId: 'quest-fate-of-the-vessel',
    order: 1,
    title: 'Survive the three-ring alignment',
    status: 'complete',
    clueIds: ['clue-engine-ring-alignment'],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-name-a-shared-purpose',
    questId: 'quest-fate-of-the-vessel',
    order: 2,
    title: 'Name a purpose the Astronomer will accept',
    status: 'complete',
    clueIds: ['clue-astronomers-purpose'],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-choose-the-fate',
    questId: 'quest-fate-of-the-vessel',
    order: 3,
    title: 'Choose: launch, bury, or kindle',
    status: 'complete',
    clueIds: ['clue-ark-or-weapon'],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-tally-the-promises',
    questId: 'quest-honor-the-seven-promises',
    order: 1,
    title: 'Tally every promise made to the holds',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-commons'],
  },
  {
    id: 'objective-deliver-duskforge-weapon',
    questId: 'quest-honor-the-seven-promises',
    order: 2,
    title: 'Deliver Duskforge’s promised weapon',
    status: 'blocked',
    clueIds: [],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-seat-the-commons',
    questId: 'quest-honor-the-seven-promises',
    order: 3,
    title: 'Seat the Commons of Seven Chalks',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-commons'],
  },
  {
    id: 'objective-survey-the-rail-damage',
    questId: 'quest-seal-the-transit-line',
    order: 1,
    title: 'Survey the damage along the line',
    status: 'complete',
    clueIds: ['clue-broken-in-one-place'],
    locationIds: ['location-transit-line'],
  },
  {
    id: 'objective-refit-the-safety-breaks',
    questId: 'quest-seal-the-transit-line',
    order: 2,
    title: 'Refit the builders’ safety breaks',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-thrumhall-switchyard'],
  },
  {
    id: 'objective-seal-meridian-station',
    questId: 'quest-seal-the-transit-line',
    order: 3,
    title: 'Seal Meridian Station behind a three-key lock',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-meridian-station'],
  },
  {
    id: 'objective-gather-the-memorial-shards',
    questId: 'quest-bring-the-ancestors-home',
    order: 1,
    title: 'Gather the vault’s memorial shards',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-zero-gravity-vault'],
  },
  {
    id: 'objective-count-the-berths',
    questId: 'quest-bring-the-ancestors-home',
    order: 2,
    title: 'Count the berths with Bodil Marrowsong',
    status: 'complete',
    clueIds: ['clue-empty-berths'],
    locationIds: ['location-berth-galleries'],
  },
  {
    id: 'objective-hang-the-shards',
    questId: 'quest-bring-the-ancestors-home',
    order: 3,
    title: 'Hang the shards beneath the Commons dome',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-commons'],
  },
  {
    id: 'objective-hide-the-courier',
    questId: 'quest-the-deserters-bargain',
    order: 1,
    title: 'Hide Ketta Rawl from the Company’s knife-squads',
    status: 'complete',
    clueIds: ['clue-ketta-rawls-confession'],
    locationIds: ['location-meridian-station'],
  },
  {
    id: 'objective-record-the-testimony',
    questId: 'quest-the-deserters-bargain',
    order: 2,
    title: 'Record her testimony before the magistrate',
    status: 'complete',
    clueIds: ['clue-duskforge-margin-script'],
    locationIds: ['location-kharad-commons'],
  },
  {
    id: 'objective-win-the-pardon',
    questId: 'quest-the-deserters-bargain',
    order: 3,
    title: 'Win a Concord pardon for the deserter',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-commons'],
  },
  {
    id: 'objective-carry-the-deep-flame',
    questId: 'quest-light-the-evening-shrine',
    order: 1,
    title: 'Carry a flame up from the deep sun',
    status: 'complete',
    clueIds: ['clue-violet-lamplight'],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-tune-the-evening-bell',
    questId: 'quest-light-the-evening-shrine',
    order: 2,
    title: 'Tune the evening bell to the fault’s hum',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-evening-bell-shrine'],
  },
  {
    id: 'objective-name-the-lost-miners',
    questId: 'quest-light-the-evening-shrine',
    order: 3,
    title: 'Carve the lost miners’ names at the lift head',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-lift-head-shrine'],
  },
  {
    id: 'objective-read-the-toll-ledger',
    questId: 'quest-turn-the-tolls',
    order: 1,
    title: 'Read Highvein’s toll ledger',
    status: 'complete',
    clueIds: ['clue-highvein-toll-ledger'],
    locationIds: ['location-highvein-counting-house'],
  },
  {
    id: 'objective-bring-tolls-to-the-concord',
    questId: 'quest-turn-the-tolls',
    order: 2,
    title: 'Bring the tolls to a Concord vote',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-seat-a-miners-auditor',
    questId: 'quest-turn-the-tolls',
    order: 3,
    title: 'Seat a miners’ auditor in the counting house',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-highvein-counting-house'],
  },
  {
    id: 'objective-copy-the-eighth-point',
    questId: 'quest-the-eighth-light',
    order: 1,
    title: 'Copy the eighth point from the chart’s rim',
    status: 'complete',
    clueIds: ['clue-the-eighth-point'],
    locationIds: ['location-inverted-observatory'],
  },
  {
    id: 'objective-account-for-the-sleepers',
    questId: 'quest-the-eighth-light',
    order: 2,
    title: 'Account for the 40,112 missing sleepers',
    status: 'pending',
    clueIds: ['clue-empty-berths'],
    locationIds: ['location-berth-galleries'],
  },
  {
    id: 'objective-match-the-second-key',
    questId: 'quest-the-eighth-light',
    order: 3,
    title: 'Match the second Ashglass key to its lock',
    status: 'pending',
    clueIds: ['clue-key-hums-toward-highvein'],
    locationIds: ['location-highvein-counting-house'],
  },
  {
    id: 'objective-descend-the-eighth-shaft',
    questId: 'quest-the-eighth-light',
    order: 4,
    title: 'Descend the sealed shaft beneath the engine',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-eighth-shaft'],
  },
];
