import type { CampaignQuest, QuestObjective } from '../ashes-of-veyra/types';
import { KHARAD_CAMPAIGN_ID as C } from './campaign';

const S1 = `${C}-session-1`;
const S2 = `${C}-session-2`;
const S3 = `${C}-session-3`;

/**
 * The shared quest model has no `failed` or `abandoned` state, so outcomes are
 * mapped as follows: resolved quests are `complete`; an abandoned quest is
 * `on-hold`. A failed objective is `blocked`; an abandoned one is `pending`.
 * Each summary opens with the real outcome.
 */
export const kharadQuests: CampaignQuest[] = [
  {
    id: 'quest-rescue-survey-crew',
    campaignId: C,
    title: 'Rescue the Survey Crew',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: all eleven trapped miners and surveyors were pulled out of the collapsing singing fault.',
    giverNpcId: 'npc-tamsin-brack',
    factionIds: ['faction-kharad-delvers-union'],
    sessionIds: [S1],
    locationIds: ['location-kharad-mine', 'location-singing-fault'],
    objectiveIds: [
      'objective-locate-trapped-crews',
      'objective-stabilize-the-fault',
      'objective-evacuate-survivors',
    ],
  },
  {
    id: 'quest-read-inverted-chart',
    campaignId: C,
    title: 'Read the Inverted Star Chart',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: the chart proved to be a map of seven holds and the star engine beneath them, and each hold seal was matched to its owner.',
    giverNpcId: 'npc-pell-quartz',
    factionIds: ['faction-chalkline-collegium'],
    sessionIds: [S1, S2],
    locationIds: ['location-inverted-observatory', 'location-broken-gate-hall'],
    objectiveIds: [
      'objective-copy-the-chart',
      'objective-identify-seven-holds',
      'objective-match-hold-seals',
    ],
  },
  {
    id: 'quest-open-the-transit-gate',
    campaignId: C,
    title: 'Open the Transit Gate',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: the Concord agreed to open the gate, the party ran the unstable line, and Dagna accepted custodianship.',
    giverNpcId: 'npc-hrolda-ironvein',
    factionIds: ['faction-seven-hold-concord'],
    sessionIds: [S2],
    locationIds: ['location-broken-gate-hall', 'location-transit-line'],
    objectiveIds: [
      'objective-secure-concord-consensus',
      'objective-run-transit-line',
      'objective-name-the-custodian',
    ],
  },
  {
    id: 'quest-sabotage-for-the-holds',
    campaignId: C,
    title: 'Sabotage for the Holds',
    status: 'on-hold',
    priority: 'low',
    summary:
      'Abandoned: two delegates privately asked the party to sabotage a rival, and the party declined both and reported neither.',
    giverNpcId: 'npc-oskar-deepfire',
    factionIds: ['faction-duskforge-hold', 'faction-seven-hold-concord'],
    sessionIds: [S2],
    locationIds: ['location-broken-gate-hall'],
    objectiveIds: [
      'objective-hear-secret-requests',
      'objective-sabotage-a-rival',
    ],
  },
  {
    id: 'quest-race-ordrun-to-the-engine',
    campaignId: C,
    title: 'Race Ordrun to the Engine',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: the party beat the Ardent Deep Company through Meridian Station and reached the engine first.',
    giverNpcId: 'npc-hrolda-ironvein',
    factionIds: ['faction-ardent-deep-company'],
    sessionIds: [S2, S3],
    locationIds: ['location-transit-line', 'location-zero-gravity-vault'],
    objectiveIds: [
      'objective-reach-meridian-station',
      'objective-recover-sealed-orders',
      'objective-reach-engine-first',
    ],
  },
  {
    id: 'quest-fate-of-the-vessel',
    campaignId: C,
    title: 'The Fate of the Vessel',
    status: 'complete',
    priority: 'high',
    summary:
      'Completed: rather than launch or bury it, the party kindled the vessel into a deep sun and the Astronomer stood down.',
    giverNpcId: 'npc-the-astronomer',
    factionIds: ['faction-astronomers-watch', 'faction-chalkline-collegium'],
    sessionIds: [S3],
    locationIds: ['location-zero-gravity-vault', 'location-engine-heart'],
    objectiveIds: [
      'objective-align-the-rings',
      'objective-name-a-shared-purpose',
      'objective-choose-the-fate',
    ],
  },
  {
    id: 'quest-honor-the-seven-promises',
    campaignId: C,
    title: 'Honor the Seven Promises',
    status: 'complete',
    priority: 'medium',
    summary:
      'Closed out: five of the six promises made to the holds were kept; the weapon promised to Duskforge was refused.',
    giverNpcId: 'npc-ilsa-vaunt',
    factionIds: [
      'faction-seven-hold-concord',
      'faction-kharad-delvers-union',
      'faction-duskforge-hold',
    ],
    sessionIds: [S3],
    locationIds: ['location-engine-heart', 'location-kharad-commons'],
    objectiveIds: [
      'objective-tally-the-promises',
      'objective-deliver-duskforge-weapon',
      'objective-seat-the-commons',
    ],
  },
];

export const kharadQuestObjectives: QuestObjective[] = [
  {
    id: 'objective-locate-trapped-crews',
    questId: 'quest-rescue-survey-crew',
    order: 1,
    title: 'Locate the trapped crews by their echoes',
    status: 'complete',
    clueIds: ['clue-echoes-run-early'],
    locationIds: ['location-singing-fault'],
  },
  {
    id: 'objective-stabilize-the-fault',
    questId: 'quest-rescue-survey-crew',
    order: 2,
    title: 'Stabilize the resonating fault',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-singing-fault'],
  },
  {
    id: 'objective-evacuate-survivors',
    questId: 'quest-rescue-survey-crew',
    order: 3,
    title: 'Evacuate the survivors to Kharad',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-mine'],
  },
  {
    id: 'objective-copy-the-chart',
    questId: 'quest-read-inverted-chart',
    order: 1,
    title: 'Copy the inverted star chart',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-inverted-observatory'],
  },
  {
    id: 'objective-identify-seven-holds',
    questId: 'quest-read-inverted-chart',
    order: 2,
    title: 'Identify the seven holds on the chart',
    status: 'complete',
    clueIds: ['clue-inverted-constellation'],
    locationIds: ['location-inverted-observatory'],
  },
  {
    id: 'objective-match-hold-seals',
    questId: 'quest-read-inverted-chart',
    order: 3,
    title: 'Match each hold seal to its delegate',
    status: 'complete',
    clueIds: ['clue-seven-hold-seals'],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-secure-concord-consensus',
    questId: 'quest-open-the-transit-gate',
    order: 1,
    title: 'Win a Concord majority to open the gate',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-run-transit-line',
    questId: 'quest-open-the-transit-gate',
    order: 2,
    title: 'Run the unstable transit line',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-transit-line'],
  },
  {
    id: 'objective-name-the-custodian',
    questId: 'quest-open-the-transit-gate',
    order: 3,
    title: 'Name a custodian for the engine',
    status: 'complete',
    clueIds: ['clue-gate-custodian-oath'],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-hear-secret-requests',
    questId: 'quest-sabotage-for-the-holds',
    order: 1,
    title: 'Hear the delegates’ private requests',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-sabotage-a-rival',
    questId: 'quest-sabotage-for-the-holds',
    order: 2,
    title: 'Sabotage a rival delegation',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-broken-gate-hall'],
  },
  {
    id: 'objective-reach-meridian-station',
    questId: 'quest-race-ordrun-to-the-engine',
    order: 1,
    title: 'Reach Meridian Station ahead of Ordrun',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-transit-line'],
  },
  {
    id: 'objective-recover-sealed-orders',
    questId: 'quest-race-ordrun-to-the-engine',
    order: 2,
    title: 'Recover the marshal’s sealed orders',
    status: 'complete',
    clueIds: ['clue-ordrun-orders'],
    locationIds: ['location-transit-line'],
  },
  {
    id: 'objective-reach-engine-first',
    questId: 'quest-race-ordrun-to-the-engine',
    order: 3,
    title: 'Reach the engine before the Ardent Company',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-zero-gravity-vault'],
  },
  {
    id: 'objective-align-the-rings',
    questId: 'quest-fate-of-the-vessel',
    order: 1,
    title: 'Survive the three-ring alignment',
    status: 'complete',
    clueIds: ['clue-engine-ring-alignment'],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-name-a-shared-purpose',
    questId: 'quest-fate-of-the-vessel',
    order: 2,
    title: 'Name a purpose the Astronomer will accept',
    status: 'complete',
    clueIds: ['clue-astronomers-purpose'],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-choose-the-fate',
    questId: 'quest-fate-of-the-vessel',
    order: 3,
    title: 'Choose: launch, bury, or kindle',
    status: 'complete',
    clueIds: ['clue-ark-or-weapon'],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-tally-the-promises',
    questId: 'quest-honor-the-seven-promises',
    order: 1,
    title: 'Tally every promise made to the holds',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-commons'],
  },
  {
    id: 'objective-deliver-duskforge-weapon',
    questId: 'quest-honor-the-seven-promises',
    order: 2,
    title: 'Deliver Duskforge’s promised weapon',
    status: 'blocked',
    clueIds: [],
    locationIds: ['location-engine-heart'],
  },
  {
    id: 'objective-seat-the-commons',
    questId: 'quest-honor-the-seven-promises',
    order: 3,
    title: 'Seat the Commons of Seven Chalks',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-kharad-commons'],
  },
];
