import type {
  CampaignSession,
  SessionPlan,
  SessionPlanStep,
} from '../ashes-of-veyra/types';
import {
  KHARAD_ACT_ONE_ID,
  KHARAD_CAMPAIGN_ID,
  KHARAD_SESSION_1_ID,
  KHARAD_SESSION_2_ID,
  KHARAD_SESSION_3_ID,
} from './campaign';

type StepInput = Omit<SessionPlanStep, 'id' | 'order'>;

function buildPlan(input: {
  idPrefix: string;
  revision: number;
  lastEdited: string;
  readiness: string[];
  dependencies: string[];
  steps: StepInput[];
  notes: string[];
  playerFacingSummary: string;
  attachments: string[];
}): SessionPlan {
  const steps = input.steps.map((step, index) => ({
    ...step,
    id: `${input.idPrefix}-step-${index + 1}`,
    order: index + 1,
  }));
  return {
    revision: input.revision,
    lastEdited: input.lastEdited,
    estimatedMinutes: steps.reduce(
      (total, step) => total + step.durationMinutes,
      0,
    ),
    readiness: input.readiness.map((label, index) => ({
      id: `${input.idPrefix}-ready-${index + 1}`,
      label,
      complete: true,
    })),
    dependencies: input.dependencies.map((objectId) => ({
      objectId,
      status: 'ready' as const,
    })),
    steps,
    notes: input.notes,
    playerFacingSummary: input.playerFacingSummary,
    attachments: input.attachments,
  };
}

export const session1Plan: SessionPlan = buildPlan({
  idPrefix: KHARAD_SESSION_1_ID,
  revision: 4,
  lastEdited: '5 months ago',
  readiness: [
    'Collapsed mine skill challenge ready',
    'Star engine diagram ready',
    'Rescued miner names written',
    'Ghostlamp violet-lamp seeds prepared',
    'Eighth-mark rubbing printed for the table',
  ],
  dependencies: [
    'encounter-resonant-fault-collapse',
    'encounter-survey-crew-defense',
    'handout-inverted-star-chart',
    'encounter-quartz-spur-bridge',
    'handout-delvers-union-roll',
  ],
  steps: [
    {
      kind: 'scene',
      track: 'main',
      title: 'Descend through the singing fault',
      durationMinutes: 40,
      visibility: 'shared',
      objectId: 'encounter-resonant-fault-collapse',
      body: 'Rescue trapped miners while crystalline echoes imitate the party’s plans one minute early.',
    },
    {
      kind: 'encounter',
      track: 'main',
      title: 'Defend the survey crew',
      durationMinutes: 55,
      visibility: 'dm-only',
      objectId: 'encounter-survey-crew-defense',
      body: 'Gravitic pulses move every creature toward a different wall at initiative count 20.',
    },
    {
      kind: 'handout',
      track: 'main',
      title: 'Read the inverted star chart',
      durationMinutes: 25,
      visibility: 'shared',
      objectId: 'handout-inverted-star-chart',
      body: 'The chart identifies Kharad as one point in a buried constellation spanning seven holds.',
    },
    {
      kind: 'closing',
      track: 'main',
      title: 'The first star wakes',
      durationMinutes: 10,
      visibility: 'shared',
      body: 'A violet light ignites miles below, and every compass turns downward.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Outcome: every miner lived',
      durationMinutes: 0,
      visibility: 'dm-only',
      body: 'All eleven trapped miners were brought out; Foreman Brack owes the party the Delvers’ Union’s trust for the rest of the campaign.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'Survey Crew Log',
      durationMinutes: 3,
      visibility: 'shared',
      objectId: 'handout-survey-crew-log',
      body: 'Surface when the party searches the observatory’s antechamber for the missing surveyors.',
    },
    {
      kind: 'encounter',
      track: 'parallel',
      title: 'The Quartz Spur Bridge',
      durationMinutes: 20,
      visibility: 'dm-only',
      objectId: 'encounter-quartz-spur-bridge',
      body: 'Optional crossing for a party that wants a harder route to the farthest crew; Yarrow’s note-matching skill challenge decides how many spurs hold.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'Roll of the Rescued',
      durationMinutes: 3,
      visibility: 'shared',
      objectId: 'handout-delvers-union-roll',
      body: 'Hand over at the lift head once all eleven are counted; the Union’s roll becomes the shrine’s epilogue list.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Seed: the violet lamps',
      durationMinutes: 0,
      visibility: 'dm-only',
      objectId: 'lore-ghostlamp-lamp-liturgy',
      body: 'Ysolde Ghostlamp’s lamps burn violet near the fault; never explain why, only that she insists on carrying them.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Seed: the eighth mark',
      durationMinutes: 0,
      visibility: 'dm-only',
      objectId: 'handout-eighth-point-rubbing',
      body: 'If a player asks about the unlabeled mark beneath Kharad, Pell only answers “I do not know who asked for it.”',
    },
  ],
  notes: [
    'Give rescued miners names before revealing the observatory.',
    'Recap: the party pulled the survey crew out of the Kharad collapse, found the inverted observatory, and watched the first star wake.',
    'Lingering thread to preserve: the unlabeled eighth point on the chart’s rim; Pell copies it but never speculates.',
    'Table feel: let the fault’s early echoes become a running gag the party can use for tactical foreknowledge.',
  ],
  playerFacingSummary:
    'The mine collapse was no accident, and the light below Kharad does not come from fire. You brought everyone out alive, and now every compass points down.',
  attachments: [
    'handout-inverted-star-chart',
    'handout-survey-crew-log',
    'handout-delvers-union-roll',
    'lore-star-chart-legend',
  ],
});

export const session2Plan: SessionPlan = buildPlan({
  idPrefix: KHARAD_SESSION_2_ID,
  revision: 5,
  lastEdited: '4 months ago',
  readiness: [
    'Hold delegate motives ready',
    'Transit gate complications ready',
    'Ordrun ambush map ready',
    'Seven delegate portraits and seats ready',
    'Ketta Rawl’s letter ready to hand over',
  ],
  dependencies: [
    'encounter-council-at-broken-gate',
    'encounter-transit-line-chase',
    'encounter-ordrun-station-ambush',
    'handout-concord-writ-of-custodianship',
    'encounter-banquet-of-seven-knives',
    'encounter-thrumhall-switchyard',
    'encounter-ketta-pursuit',
    'lore-seven-holds-gazetteer',
  ],
  steps: [
    {
      kind: 'recap',
      track: 'main',
      title: 'The buried constellation',
      durationMinutes: 10,
      visibility: 'shared',
      body: 'Place seven hold tokens on the chart and mark the newly awakened point.',
    },
    {
      kind: 'scene',
      track: 'main',
      title: 'Council at the broken gate',
      durationMinutes: 50,
      visibility: 'shared',
      objectId: 'encounter-council-at-broken-gate',
      body: 'Each delegate offers aid with a visible price; two privately ask the party to sabotage a rival.',
    },
    {
      kind: 'encounter',
      track: 'main',
      title: 'Run the unstable transit line',
      durationMinutes: 70,
      visibility: 'dm-only',
      objectId: 'encounter-transit-line-chase',
      body: 'A three-stage chase crosses abandoned stations as the rival expedition closes from behind.',
    },
    {
      kind: 'choice',
      track: 'main',
      title: 'Name the engine’s custodian',
      durationMinutes: 25,
      visibility: 'shared',
      objectId: 'handout-concord-writ-of-custodianship',
      body: 'The gate activates only after someone accepts legal and magical responsibility for it.',
    },
    {
      kind: 'encounter',
      track: 'main',
      title: 'Ordrun’s ambush at Meridian Station',
      durationMinutes: 40,
      visibility: 'dm-only',
      objectId: 'encounter-ordrun-station-ambush',
      body: 'The rival marshal springs her trap the moment the gate opens; she breaks off once the party holds her sealed orders.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'Ordrun’s Sealed Orders',
      durationMinutes: 3,
      visibility: 'dm-only',
      objectId: 'handout-ordrun-sealed-orders',
      body: 'Recovered from the marshal’s courier; reveals the Ardent Deep Company intends to weaponize the vessel.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Outcome: Dagna signs as custodian',
      durationMinutes: 0,
      visibility: 'dm-only',
      body: 'Dagna Seven-Chalks accepted custodianship. The party declined both secret sabotage requests, souring Hold Duskforge.',
    },
    {
      kind: 'closing',
      track: 'main',
      title: 'The gate opens on the deep sky',
      durationMinutes: 10,
      visibility: 'shared',
      body: 'The gate spits the party onto a platform with no ceiling, only the seven-hold constellation turning overhead.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'Gazetteer of the Seven Holds',
      durationMinutes: 5,
      visibility: 'shared',
      objectId: 'lore-seven-holds-gazetteer',
      body: 'Hand out before the council so players can match each delegate to a hold and a motive.',
    },
    {
      kind: 'encounter',
      track: 'parallel',
      title: 'The Banquet of Seven Knives',
      durationMinutes: 30,
      visibility: 'dm-only',
      objectId: 'encounter-banquet-of-seven-knives',
      body: 'The night-before dinner: Bellowmere’s kitchens, a hired cup-bearer, and every delegate working the room. Use to seed Highvein’s and Duskforge’s private offers.',
    },
    {
      kind: 'encounter',
      track: 'parallel',
      title: 'The Thrumhall Switchyard',
      durationMinutes: 25,
      visibility: 'dm-only',
      objectId: 'encounter-thrumhall-switchyard',
      body: 'A puzzle-combat on the line; Sunniva shouts the timetable if the party names a valid train.',
    },
    {
      kind: 'encounter',
      track: 'parallel',
      title: 'Knife-squads at the Meridian siding',
      durationMinutes: 20,
      visibility: 'dm-only',
      objectId: 'encounter-ketta-pursuit',
      body: 'Ketta’s defection triggers the Company’s enforcers; the party decides whether to shield her or sacrifice the lead.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'Letter from Ketta Rawl',
      durationMinutes: 3,
      visibility: 'shared',
      objectId: 'handout-ketta-rawls-letter',
      body: 'Pressed into a player’s hand at the platform stairs; the margin note in Duskforge script is Oskar’s own hand.',
    },
  ],
  notes: [
    'Track promises to each hold; every accepted resource creates a finale complication.',
    'Recap: the Concord met at the broken gate, the party ran the transit line, beat Ordrun’s ambush, and named Dagna custodian.',
    'Promises to track: Bellowmere’s shared kitchens, Thrumhall’s timetable credit, Greywarden’s three-key lock, Marrowstone’s memorial rite, Duskforge’s weapon, Highvein’s toll schedule.',
    'Orla Silvervein’s private sabotage request is a seed: she asks politely, accepts the refusal graciously, and is never seen angry.',
  ],
  playerFacingSummary:
    'Seven holds claim the star beneath Kharad, and the road between them has just reopened. You crossed it first, and your name is on the writ.',
  attachments: [
    'lore-seven-holds-charter',
    'handout-concord-writ-of-custodianship',
    'handout-ordrun-sealed-orders',
    'handout-ketta-rawls-letter',
    'handout-thrumhall-line-ledger',
    'handout-bellowmere-kitchens-compact',
    'lore-seven-holds-gazetteer',
  ],
});

export const session3Plan: SessionPlan = buildPlan({
  idPrefix: KHARAD_SESSION_3_ID,
  revision: 6,
  lastEdited: '4 months ago',
  readiness: [
    'Final chamber phases ready',
    'Faction consequence cards ready',
    'Epilogue prompts ready',
    'Legacy lore archived',
    'Sequel seeds (eighth light, toll letters) prepared',
    'Deep sun flare coda ready',
  ],
  dependencies: [
    'encounter-zero-gravity-vault',
    'encounter-astronomer-awakens',
    'encounter-fate-of-the-vessel',
    'handout-astronomers-final-message',
    'handout-epilogue-proclamation',
    'encounter-deep-sun-flare',
    'handout-marrowstone-sleeper-manifest',
    'handout-epilogue-letter-hrolda',
    'handout-epilogue-letter-orla',
  ],
  steps: [
    {
      kind: 'scene',
      track: 'main',
      title: 'Cross the zero-gravity vault',
      durationMinutes: 45,
      visibility: 'shared',
      objectId: 'encounter-zero-gravity-vault',
      body: 'Characters navigate by jumping between fragments of the seven holds’ shared history.',
    },
    {
      kind: 'encounter',
      track: 'main',
      title: 'The astronomer awakens',
      durationMinutes: 90,
      visibility: 'dm-only',
      objectId: 'encounter-astronomer-awakens',
      body: 'The guardian changes gravity, terrain, and its goal as three engine rings align.',
    },
    {
      kind: 'choice',
      track: 'main',
      title: 'Choose the fate of the vessel',
      durationMinutes: 35,
      visibility: 'shared',
      objectId: 'encounter-fate-of-the-vessel',
      body: 'Launch, burial, and ignition each honor one promise and break at least one other.',
    },
    {
      kind: 'handout',
      track: 'main',
      title: 'The Astronomer’s final message',
      durationMinutes: 5,
      visibility: 'shared',
      objectId: 'handout-astronomers-final-message',
      body: 'Read aloud once the guardian surrenders and the rings fall still.',
    },
    {
      kind: 'closing',
      track: 'main',
      title: 'Epilogues under a changed sky',
      durationMinutes: 30,
      visibility: 'shared',
      objectId: 'handout-epilogue-proclamation',
      body: 'Ask each player what their character builds now that the holds must share a future.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Outcome: the deep sun',
      durationMinutes: 0,
      visibility: 'dm-only',
      body: 'The party kindled the vessel rather than launching or burying it. Five promises held; the promise to Hold Duskforge for a weapon was broken.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Campaign wrap-up and legacy',
      durationMinutes: 0,
      visibility: 'dm-only',
      objectId: 'lore-legacy-of-kharad',
      body: 'Archive the campaign; the legacy lore entry records how the holds remember the party.',
    },
    {
      kind: 'encounter',
      track: 'parallel',
      title: 'The deep sun flare',
      durationMinutes: 20,
      visibility: 'dm-only',
      objectId: 'encounter-deep-sun-flare',
      body: 'A short coda combat in the first minute of kindling; the Astronomer can vent the flare once per round.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'The Sleeper Manifest',
      durationMinutes: 5,
      visibility: 'shared',
      objectId: 'handout-marrowstone-sleeper-manifest',
      body: 'Bodil hands over her copy at the berth galleries; leave the question of where the sleepers went unanswered.',
    },
    {
      kind: 'handout',
      track: 'parallel',
      title: 'Letters under a changed sky',
      durationMinutes: 5,
      visibility: 'shared',
      objectId: 'handout-epilogue-letter-hrolda',
      body: 'Read Hrolda’s letter, then Orla’s: peace has a price and one hold has already priced it.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Sequel seeds: The Eighth Light',
      durationMinutes: 0,
      visibility: 'dm-only',
      objectId: 'quest-the-eighth-light',
      body: 'Three open threads: the unlabeled eighth point, the empty berths, and the second Ashglass key. Do not resolve any of them in the epilogue.',
    },
    {
      kind: 'note',
      track: 'parallel',
      title: 'Open thread: the toll war',
      durationMinutes: 0,
      visibility: 'dm-only',
      objectId: 'quest-turn-the-tolls',
      body: 'Highvein’s toll ledger is dated before the vote. Tamsin wants it stopped; the Concord has not been asked.',
    },
  ],
  notes: [
    'Resolve faction promises before describing the cosmic result.',
    'The guardian can surrender once the party articulates a shared purpose.',
    'Recap: the party crossed the vault, out-argued the Astronomer as three rings aligned, and kindled the vessel into a deep sun.',
    'Epilogue prompts: what does each hero build, who sits beside them in the Commons, and what are they afraid will come up from below?',
    'Lingering threads: the eighth point, the empty berths, the second Ashglass key, and Highvein’s tolls. Leave all four open.',
  ],
  playerFacingSummary:
    'The deep sky is opening. What waits beneath Kharad was built to carry a civilization—or burn one. You chose a third road: a sun of your own making.',
  attachments: [
    'lore-star-engine-purpose',
    'handout-astronomers-final-message',
    'handout-epilogue-proclamation',
    'lore-legacy-of-kharad',
    'handout-marrowstone-sleeper-manifest',
    'handout-epilogue-letter-hrolda',
    'handout-epilogue-letter-orla',
    'handout-ashglass-key-letter',
  ],
});

export const sessions: CampaignSession[] = [
  {
    id: KHARAD_SESSION_1_ID,
    campaignId: KHARAD_CAMPAIGN_ID,
    actId: KHARAD_ACT_ONE_ID,
    number: 1,
    title: 'The Observatory Beneath the Mine',
    status: 'complete',
    summary:
      'A routine rescue exposes an ancient observatory whose constellations depict caverns instead of the sky. The party hears the Singing Fault replay their words a minute early, carries eleven miners up the lift, and watches the first star wake as every compass turns to point down.',
    plannedDate: '2026-05-02',
    durationHours: 4,
    partyLevel: 9,
    tags: ['Underdark', 'Rescue', 'Discovery', 'Mystery seed'],
    questIds: ['quest-rescue-survey-crew', 'quest-read-inverted-chart'],
    npcIds: [
      'npc-tamsin-brack',
      'npc-yarrow-stonesinger',
      'npc-pell-quartz',
      'npc-ysolde-ghostlamp',
    ],
    factionIds: [
      'faction-kharad-delvers-union',
      'faction-chalkline-collegium',
      'faction-hold-ghostlamp',
    ],
    locationIds: [
      'location-kharad-mine',
      'location-singing-fault',
      'location-inverted-observatory',
      'location-lift-head-shrine',
      'location-chalk-gallery',
    ],
    encounterIds: [
      'encounter-resonant-fault-collapse',
      'encounter-survey-crew-defense',
      'encounter-quartz-spur-bridge',
    ],
    clueIds: [
      'clue-echoes-run-early',
      'clue-inverted-constellation',
      'clue-compass-turns-down',
      'clue-violet-lamplight',
      'clue-the-eighth-point',
    ],
    handoutIds: [
      'handout-inverted-star-chart',
      'handout-survey-crew-log',
      'handout-delvers-union-roll',
      'lore-star-chart-legend',
      'lore-ghostlamp-lamp-liturgy',
      'handout-eighth-point-rubbing',
    ],
    plan: session1Plan,
  },
  {
    id: KHARAD_SESSION_2_ID,
    campaignId: KHARAD_CAMPAIGN_ID,
    actId: KHARAD_ACT_ONE_ID,
    number: 2,
    title: 'Seven Holds, One Night',
    status: 'complete',
    summary:
      'The party races a rival expedition through a transit gate while negotiating which hold will control the star engine. Seven delegates trade votes for promises over a banquet and a cracked arch, two of them ask for sabotage in private, and Dagna signs the Writ of Custodianship before the line is run in a single night.',
    plannedDate: '2026-05-16',
    durationHours: 4,
    partyLevel: 9,
    tags: ['Political', 'Race', 'Planar transit', 'Delegates'],
    questIds: [
      'quest-open-the-transit-gate',
      'quest-sabotage-for-the-holds',
      'quest-race-ordrun-to-the-engine',
      'quest-the-deserters-bargain',
    ],
    npcIds: [
      'npc-hrolda-ironvein',
      'npc-vessa-ordrun',
      'npc-oskar-deepfire',
      'npc-ilsa-vaunt',
      'npc-pell-quartz',
      'npc-brondi-greywall',
      'npc-sunniva-thrum',
      'npc-orla-silvervein',
      'npc-bodil-marrowsong',
      'npc-kjeld-bellows',
      'npc-ysolde-ghostlamp',
      'npc-ketta-rawl',
    ],
    factionIds: [
      'faction-seven-hold-concord',
      'faction-ardent-deep-company',
      'faction-duskforge-hold',
      'faction-hold-greywarden',
      'faction-hold-thrumhall',
      'faction-hold-highvein',
      'faction-hold-marrowstone',
      'faction-hold-bellowmere',
      'faction-hold-ghostlamp',
    ],
    locationIds: [
      'location-broken-gate-hall',
      'location-transit-line',
      'location-kharad-commons',
      'location-thrumhall-switchyard',
      'location-meridian-station',
    ],
    encounterIds: [
      'encounter-council-at-broken-gate',
      'encounter-transit-line-chase',
      'encounter-ordrun-station-ambush',
      'encounter-banquet-of-seven-knives',
      'encounter-thrumhall-switchyard',
      'encounter-ketta-pursuit',
    ],
    clueIds: [
      'clue-seven-hold-seals',
      'clue-gate-custodian-oath',
      'clue-ordrun-orders',
      'clue-broken-in-one-place',
      'clue-ketta-rawls-confession',
      'clue-duskforge-margin-script',
    ],
    handoutIds: [
      'lore-seven-holds-charter',
      'handout-concord-writ-of-custodianship',
      'handout-ordrun-sealed-orders',
      'lore-seven-holds-gazetteer',
      'handout-thrumhall-line-ledger',
      'handout-ketta-rawls-letter',
      'handout-bellowmere-kitchens-compact',
    ],
    plan: session2Plan,
  },
  {
    id: KHARAD_SESSION_3_ID,
    campaignId: KHARAD_CAMPAIGN_ID,
    actId: KHARAD_ACT_ONE_ID,
    number: 3,
    title: 'When the Deep Sky Opens',
    status: 'complete',
    summary:
      'At the heart of the constellation, the party decides whether to launch an impossible vessel, bury it, or turn it into a new sun. After the Astronomer’s surrender, the epilogue tallies five kept promises and one broken one, founds the Commons beneath the deep sun, and leaves four loose threads: the eighth point, the empty berths, the second Ashglass key and Highvein’s tolls.',
    plannedDate: '2026-05-30',
    durationHours: 5,
    partyLevel: 10,
    tags: ['Finale', 'Mythic combat', 'Consequences', 'Epilogue', 'Sequel hooks'],
    questIds: [
      'quest-race-ordrun-to-the-engine',
      'quest-fate-of-the-vessel',
      'quest-honor-the-seven-promises',
      'quest-seal-the-transit-line',
      'quest-bring-the-ancestors-home',
      'quest-the-deserters-bargain',
      'quest-light-the-evening-shrine',
      'quest-turn-the-tolls',
      'quest-the-eighth-light',
    ],
    npcIds: [
      'npc-the-astronomer',
      'npc-hrolda-ironvein',
      'npc-oskar-deepfire',
      'npc-vessa-ordrun',
      'npc-ilsa-vaunt',
      'npc-yarrow-stonesinger',
      'npc-pell-quartz',
      'npc-tamsin-brack',
      'npc-brondi-greywall',
      'npc-sunniva-thrum',
      'npc-orla-silvervein',
      'npc-bodil-marrowsong',
      'npc-kjeld-bellows',
      'npc-ysolde-ghostlamp',
      'npc-ketta-rawl',
      'npc-fennick-ashglass',
      'npc-gruvna-brightcut',
    ],
    factionIds: [
      'faction-astronomers-watch',
      'faction-seven-hold-concord',
      'faction-duskforge-hold',
      'faction-ardent-deep-company',
      'faction-kharad-delvers-union',
      'faction-chalkline-collegium',
      'faction-hold-greywarden',
      'faction-hold-thrumhall',
      'faction-hold-highvein',
      'faction-hold-marrowstone',
      'faction-hold-bellowmere',
      'faction-hold-ghostlamp',
      'faction-kindled-congregation',
    ],
    locationIds: [
      'location-zero-gravity-vault',
      'location-engine-heart',
      'location-kharad-commons',
      'location-berth-galleries',
      'location-eighth-shaft',
      'location-highvein-counting-house',
      'location-evening-bell-shrine',
      'location-lift-head-shrine',
      'location-thrumhall-switchyard',
      'location-meridian-station',
    ],
    encounterIds: [
      'encounter-zero-gravity-vault',
      'encounter-astronomer-awakens',
      'encounter-fate-of-the-vessel',
      'encounter-deep-sun-flare',
    ],
    clueIds: [
      'clue-engine-ring-alignment',
      'clue-astronomers-purpose',
      'clue-ark-or-weapon',
      'clue-empty-berths',
      'clue-key-hums-toward-highvein',
      'clue-highvein-toll-ledger',
      'clue-the-eighth-point',
      'clue-duskforge-margin-script',
    ],
    handoutIds: [
      'lore-star-engine-purpose',
      'handout-astronomers-final-message',
      'handout-epilogue-proclamation',
      'lore-legacy-of-kharad',
      'handout-marrowstone-sleeper-manifest',
      'handout-ashglass-key-letter',
      'handout-highvein-toll-ledger',
      'handout-epilogue-letter-hrolda',
      'handout-epilogue-letter-orla',
      'lore-kindling-night-oral-history',
      'handout-eighth-point-rubbing',
    ],
    plan: session3Plan,
  },
];
