import type { CampaignClue } from './types';

export const clues: CampaignClue[] = [
  {
    id: 'clue-strange-symbol',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Strange Symbol on Crate',
    priority: 'high',
    status: 'partially-understood',
    meaning:
      'The mark combines Ashen Synod ash script with a seal used by the drowned royal house. Lira has matched the ash half; the royal half implies the Synod holds a pre-Veyran writ nobody has seen.',
    sourceHandoutIds: [
      'handout-burned-shipping-ledger',
      'lore-azure-compact',
      'lore-synod-ash-script',
    ],
    relatedQuestIds: ['quest-find-ember-key', 'quest-fractured-spire'],
    locationIds: ['location-harbor-warehouse', 'location-fishmongers-row'],
    sessionIds: ['session-10', 'session-11', 'session-12'],
  },
  {
    id: 'clue-smuggler-note',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Note from the Smuggler',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'Mentions a key, an eastern-pier rendezvous, and the phrase "third bell." The handwriting is Crimson Wake, but the paper is Harbor Watch stock.',
    sourceHandoutIds: [
      'handout-burned-shipping-ledger',
      'handout-harbormasters-warning',
      'handout-unsigned-letter-pier6',
    ],
    relatedQuestIds: ['quest-find-ember-key', 'quest-a-debt-in-blood'],
    locationIds: ['location-south-pier', 'location-north-docks'],
    sessionIds: ['session-11', 'session-12'],
  },
  {
    id: 'clue-sahuagin-activity',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Sahuagin Activity',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'Patrols avoid one submerged route directly below the Old Customs House. They have not raided the harbor once since the Dawn Petrel arrived.',
    sourceHandoutIds: ['lore-bell-rhyme-shoals'],
    relatedQuestIds: ['quest-find-ember-key', 'quest-whispers-beneath-veyra'],
    locationIds: ['location-south-pier', 'location-old-customs-house'],
    sessionIds: ['session-3', 'session-12', 'session-13'],
  },
  {
    id: 'clue-broken-compass',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Broken Compass',
    priority: 'low',
    status: 'unresolved',
    meaning:
      'Its needle points inland toward the Fractured Spire instead of north. At the harbor it swings toward the Old Customs House.',
    sourceHandoutIds: [],
    relatedQuestIds: ['quest-fractured-spire'],
    locationIds: ['location-north-docks', 'location-glass-harbor'],
    sessionIds: ['session-4', 'session-8'],
  },
  {
    id: 'clue-northstar-scuttled',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'The Northstar Was Scuttled',
    priority: 'high',
    status: 'resolved',
    meaning:
      "The hull was holed from inside, below the waterline, by a crewman who then fled in the longboat. The captain's log confirms he was bribed with Wake coin to sink the ship before she reached port.",
    sourceHandoutIds: ['handout-northstar-captains-log'],
    relatedQuestIds: ['quest-survive-the-shoals', 'quest-find-ember-key'],
    locationIds: ['location-black-shoals'],
    sessionIds: ['session-1', 'session-3'],
  },
  {
    id: 'clue-spire-lens-inscription',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Lens Mount Inscription',
    priority: 'medium',
    status: 'partially-understood',
    meaning:
      'The empty lens mount is engraved with a ward line that, extended on a map, crosses Glass Harbor at the Old Customs House. The last four glyphs have not been translated.',
    sourceHandoutIds: [
      'handout-observatory-journal-page',
      'lore-azure-compact',
    ],
    relatedQuestIds: ['quest-fractured-spire'],
    locationIds: ['location-fractured-spire', 'location-glass-harbor'],
    sessionIds: ['session-4', 'session-8'],
  },
  {
    id: 'clue-ash-script-forgery',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Forged Endorsement in Ash-Ink',
    priority: 'high',
    status: 'partially-understood',
    meaning:
      "Inspector Vane's endorsement on the entry writ is written in Synod ash-ink, which fluoresces under lantern oil. Tamsin confirms he inked it, but not on whose authority.",
    sourceHandoutIds: [
      'handout-port-authority-writ',
      'handout-tamsin-confession',
      'lore-synod-ash-script',
    ],
    relatedQuestIds: ['quest-ash-and-ink', 'quest-clear-kaels-name'],
    locationIds: [
      'location-synod-relief-house',
      'location-old-customs-house',
    ],
    sessionIds: ['session-10', 'session-11', 'session-12'],
  },
  {
    id: 'clue-kaels-dismissal-seal',
    campaignId: 'campaign-ashes-of-veyra',
    title: "Seal on Kael's Dismissal Order",
    priority: 'high',
    status: 'partially-understood',
    meaning:
      'The Watch seal is genuine, but it is dated one day before the incident that supposedly justified the dismissal. Only someone with access to Rook private stamp could have prepared it.',
    sourceHandoutIds: ['handout-kael-dismissal-order'],
    relatedQuestIds: ['quest-clear-kaels-name'],
    locationIds: ['location-old-customs-house'],
    sessionIds: ['session-8', 'session-10'],
  },
  {
    id: 'clue-third-bell-tide',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'The Third Bell Is a Tide, Not a Time',
    priority: 'high',
    status: 'unresolved',
    meaning:
      'Lira suspects "third bell" is not a clock hour but the third tide-chime of the East Chain mooring, which rings only at the lowest ebb of the month. That is the night the arch opens.',
    sourceHandoutIds: [
      'lore-bell-rhyme-shoals',
      'handout-unsigned-letter-pier6',
      'handout-burned-shipping-ledger',
    ],
    relatedQuestIds: ['quest-find-ember-key', 'quest-whispers-beneath-veyra'],
    locationIds: ['location-south-pier', 'location-flooded-undercroft'],
    sessionIds: ['session-11', 'session-12', 'session-13'],
  },
  {
    id: 'clue-mira-debt-token',
    campaignId: 'campaign-ashes-of-veyra',
    title: "Mira's Family Debt Token",
    priority: 'medium',
    status: 'partially-understood',
    meaning:
      "A red glass token stamped with the Vale crest. It proves the family owes the Wake a favor, but the second line of the note names a person, not a sum.",
    sourceHandoutIds: ['handout-crimson-wake-debt-note'],
    relatedQuestIds: ['quest-a-debt-in-blood'],
    locationIds: ['location-salty-mast', 'location-north-docks'],
    sessionIds: ['session-5', 'session-9'],
  },
  {
    id: 'clue-cellar-grate-tally',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Tide Tally on the Cellar Grate',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'The grate beneath the Salty Mast is etched with a four-bar tide tally that matches the carved stair in the Old Customs House. The Choir used the cellar as a staging point.',
    sourceHandoutIds: ['handout-salty-mast-rumors', 'lore-bell-rhyme-shoals'],
    relatedQuestIds: [
      'quest-whispers-beneath-veyra',
      'quest-find-ember-key',
    ],
    locationIds: ['location-salty-mast', 'location-flooded-undercroft'],
    sessionIds: ['session-9', 'session-12'],
  },
  {
    id: 'clue-dawn-petrel-crew-roll',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Dawn Petrel Crew Roll Is Short Five',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'The Harbor Watch crew roll lists twelve sailors; the harbor chandler sold provisions for seventeen. Five crew vanished before the cargo was relabeled, and Captain Dray is among the missing.',
    sourceHandoutIds: [
      'handout-burned-shipping-ledger',
      'handout-harbor-map-legend',
    ],
    relatedQuestIds: ['quest-find-ember-key'],
    locationIds: ['location-north-docks', 'location-south-pier'],
    sessionIds: ['session-11', 'session-12'],
  },
];
