import type { CampaignFaction } from './types';

export const factions: CampaignFaction[] = [
  {
    id: 'faction-harbor-watch',
    campaignId: 'campaign-ashes-of-veyra',
    name: 'Harbor Watch',
    publicFace: 'Customs, patrols, and port security.',
    hiddenAgenda: 'Warden Rook diverts confiscated relics to private buyers.',
    leaderNpcId: 'npc-elian-rook',
    alliedFactionIds: ['faction-lantern-guild'],
    rivalFactionIds: ['faction-crimson-wake', 'faction-ashen-synod'],
    locationIds: [
      'location-glass-harbor',
      'location-old-customs-house',
      'location-south-pier',
    ],
    questIds: ['quest-find-ember-key'],
    status: 'unknown',
  },
  {
    id: 'faction-crimson-wake',
    campaignId: 'campaign-ashes-of-veyra',
    name: 'The Crimson Wake',
    publicFace: 'Smugglers, dockside fixers, and discreet cargo brokers.',
    hiddenAgenda:
      'Wants leverage over every faction, not open rule of the city.',
    leaderNpcId: 'npc-selka-marr',
    alliedFactionIds: [],
    rivalFactionIds: ['faction-harbor-watch', 'faction-ashen-synod'],
    locationIds: [
      'location-salty-mast',
      'location-north-docks',
      'location-harbor-warehouse',
    ],
    questIds: ['quest-find-ember-key', 'quest-a-debt-in-blood'],
    status: 'neutral',
  },
  {
    id: 'faction-ashen-synod',
    campaignId: 'campaign-ashes-of-veyra',
    name: 'Ashen Synod',
    publicFace: 'Temple relief, funerary rites, and historical stewardship.',
    hiddenAgenda: 'Believes the Hollow Crown can restore divine authority.',
    leaderNpcId: 'npc-oren-voss',
    alliedFactionIds: [],
    rivalFactionIds: ['faction-crimson-wake', 'faction-harbor-watch'],
    locationIds: ['location-glass-harbor', 'location-old-customs-house'],
    questIds: ['quest-find-ember-key'],
    status: 'opposition',
  },
  {
    id: 'faction-lantern-guild',
    campaignId: 'campaign-ashes-of-veyra',
    name: 'Lantern Guild',
    publicFace: 'Navigators, scholars, lighthouse keepers, and chartmakers.',
    hiddenAgenda:
      'Maps passages into the drowned city before any faction can claim them.',
    leaderNpcId: 'npc-neris-quill',
    alliedFactionIds: ['faction-harbor-watch'],
    rivalFactionIds: ['faction-choir-below'],
    locationIds: ['location-north-docks', 'location-glass-harbor'],
    questIds: ['quest-fractured-spire', 'quest-whispers-beneath-veyra'],
    status: 'ally',
  },
  {
    id: 'faction-choir-below',
    campaignId: 'campaign-ashes-of-veyra',
    name: 'Choir Below',
    publicFace: "A sailors' superstition about bells heard beneath a calm sea.",
    hiddenAgenda: 'A real cult awakening something beneath the crown vault.',
    alliedFactionIds: [],
    rivalFactionIds: ['faction-lantern-guild'],
    locationIds: ['location-south-pier', 'location-old-customs-house'],
    questIds: ['quest-whispers-beneath-veyra'],
    status: 'unknown',
  },
];
