import type { CampaignHandout } from './types';

export const handouts: CampaignHandout[] = [
  {
    id: 'handout-burned-shipping-ledger',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Burned Shipping Ledger',
    kind: 'handout',
    summary:
      'A smoke-damaged customs copy naming the Dawn Petrel and pier 6; several rows are deliberately missing.',
    content: [
      'The surviving entry lists the Dawn Petrel, a night arrival, and pier 6. The cargo is recorded as kiln glass, though the weight is wrong for the listed crates.',
      'A scorched line in the margin reads: "third bell, east chain." The neighboring names have been cut away with a narrow blade.',
      'On the reverse, in a second hand, someone has tallied a crew of twelve and underlined the number twice. A grease thumbprint covers the signature of the receiving clerk.',
    ],
    visibility: 'shared',
    sessionIds: ['session-11', 'session-12'],
    clueIds: [
      'clue-smuggler-note',
      'clue-strange-symbol',
      'clue-third-bell-tide',
      'clue-dawn-petrel-crew-roll',
    ],
    questIds: ['quest-find-ember-key'],
    locationIds: [
      'location-fishmongers-row',
      'location-south-pier',
      'location-harbor-warehouse',
    ],
    factionIds: ['faction-harbor-watch', 'faction-crimson-wake'],
  },
  {
    id: 'handout-harbormasters-warning',
    campaignId: 'campaign-ashes-of-veyra',
    title: "Harbormaster's Warning",
    kind: 'handout',
    summary:
      'A private note from Serin asking the party to watch the eastern pier without involving the Watch.',
    content: [
      'The eastern pier changes hands at dusk. Watch the cargo, not the people; I need to know which vessel carried the ash-marked crate.',
      'Do not involve the Watch. If Rook learns I sent you, the manifest will disappear before morning.',
      'Burn this when you have read it. If you cannot, keep it where the rain cannot find it. S.D.',
    ],
    visibility: 'shared',
    sessionIds: ['session-12'],
    clueIds: ['clue-smuggler-note'],
    questIds: ['quest-find-ember-key'],
    locationIds: ['location-south-pier', 'location-old-customs-house'],
    factionIds: ['faction-harbor-watch'],
  },
  {
    id: 'handout-port-authority-writ',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Port Authority Entry Writ',
    kind: 'handout',
    summary:
      'An official stamped permit granting access through warehouse district gates during restricted hours.',
    content: [
      'Issued under the seal of the Veyra Port Authority. Bearer is authorized passage through Gates 3 through 7 between second and fourth bell.',
      'A handwritten endorsement at the bottom notes: "Approved by Inspector Vane for dry cargo inspection only."',
      'Held at an angle, the endorsement glows faintly green. The ink is not the Port Authority blue-black.',
    ],
    visibility: 'shared',
    sessionIds: ['session-10', 'session-12'],
    clueIds: ['clue-smuggler-note', 'clue-ash-script-forgery'],
    questIds: ['quest-find-ember-key', 'quest-ash-and-ink'],
    locationIds: ['location-harbor-warehouse', 'location-south-pier'],
    factionIds: ['faction-harbor-watch'],
  },
  {
    id: 'handout-unsigned-letter-pier6',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Mysterious Unsigned Letter (pier 6)',
    kind: 'handout',
    summary:
      'A hastily penned message recovered near pier 6 referencing the third bell cargo exchange.',
    content: [
      'The exchange happens at the third bell by the east chain mooring. Bring the secondary key or the arrangement is void.',
      'Do not trust the red lanterns. If you are followed into the warehouse, scatter toward the fishmongers.',
      'If the water answers, do not wait for the others. The arch will not stay open.',
    ],
    visibility: 'shared',
    sessionIds: ['session-12'],
    clueIds: [
      'clue-smuggler-note',
      'clue-strange-symbol',
      'clue-third-bell-tide',
    ],
    questIds: ['quest-find-ember-key'],
    locationIds: ['location-south-pier'],
    factionIds: ['faction-crimson-wake'],
  },
  {
    id: 'lore-azure-compact',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'The Azure Compact',
    kind: 'lore',
    summary:
      'A historical treaty that divided salvage rights after the sinking of old Veyra.',
    content: [
      'The Compact grants the harbor city rights to wreckage above the old tide line, while sealed royal property below it belongs to no living house.',
      'Its witness marks match the blue-green ward lines Lira has found around the Ember Key references.',
      'Article nine, rarely quoted, allows any "keeper of the chain" to reclaim the sealed vault if the bells below are answered three times in a single tide. The Concord has quietly built its salvage claim on that clause.',
    ],
    visibility: 'shared',
    sessionIds: ['session-4', 'session-8', 'session-10'],
    clueIds: ['clue-strange-symbol', 'clue-spire-lens-inscription'],
    questIds: ['quest-fractured-spire', 'quest-find-ember-key'],
    locationIds: ['location-old-customs-house', 'location-glass-harbor'],
    factionIds: [
      'faction-lantern-guild',
      'faction-ashen-synod',
      'faction-gilded-concord',
    ],
  },
  {
    id: 'lore-bell-rhyme-shoals',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Bell-Rhyme of the Shoals',
    kind: 'lore',
    summary:
      'A children song whose four beats match the drowned cult signal recorded beneath the harbor.',
    content: [
      'One for the mast and two for the chain, three for the door below the rain; four when the harbor answers back, then follow the sound through the black.',
      'Mara remembers hearing the final beat from the cellar grate at low tide.',
      'Older versions replace "door" with "crown." Children in the south wards skip a rope on the third beat, and nobody can say who taught them.',
    ],
    visibility: 'dm-only',
    sessionIds: ['session-6', 'session-9', 'session-12'],
    clueIds: [
      'clue-sahuagin-activity',
      'clue-third-bell-tide',
      'clue-cellar-grate-tally',
    ],
    questIds: ['quest-whispers-beneath-veyra'],
    locationIds: ['location-salty-mast', 'location-south-pier'],
    factionIds: ['faction-choir-below'],
  },
  {
    id: 'handout-northstar-captains-log',
    campaignId: 'campaign-ashes-of-veyra',
    title: "Captain's Log of the Northstar",
    kind: 'handout',
    summary:
      'A salt-stained final log recovered from the wreck, ending mid-sentence.',
    content: [
      'Fourth watch, calm sea. The cargo hums again. I told the crew it is the kiln crates settling, but the cook has stopped sleeping below deck and the cat will not go near the hold.',
      'Mr. Tarn came to my cabin this evening and asked to be put ashore at the next island. I laughed at him. He did not laugh back. I have written his name on the manifest in a smaller hand than the others, for reasons I cannot explain to myself.',
      'Fifth watch. A knocking from the keel, steady, patient. I sent Dobbs to listen and he has not come up. Whatever we are carrying, it is not glass, and I begin to think it was never meant to arrive. If you find this, tell the harbor master that',
    ],
    visibility: 'shared',
    sessionIds: ['session-1', 'session-3'],
    clueIds: ['clue-northstar-scuttled'],
    questIds: ['quest-survive-the-shoals'],
    locationIds: ['location-black-shoals'],
    factionIds: [],
  },
  {
    id: 'handout-lantern-writ-of-passage',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Lantern Guild Writ of Passage',
    kind: 'handout',
    summary:
      'A guild letter granting four named bearers priority berth and inspection leave in Glass Harbor.',
    content: [
      'By the authority of the Lantern Guild, keepers of light and chart, let the bearers of this writ pass without hindrance through any port that honors the lamp. They travel in the interest of the Guild and carry no contraband.',
      'Bearers: Kael Ardyn, Mira Vale, Torin Stonewake, Lira Fen. Sponsor: Neris Quill, Archivist of the Third Reading Room.',
      'Note in the margin, small and hurried: "The crate in the ballast barrel is not on this list. I have not seen it. N.Q."',
    ],
    visibility: 'shared',
    sessionIds: ['session-7'],
    clueIds: [],
    questIds: ['quest-passage-to-veyra'],
    locationIds: ['location-veyra-coast', 'location-glass-harbor'],
    factionIds: ['faction-lantern-guild'],
  },
  {
    id: 'handout-observatory-journal-page',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Journal Page from the Spire Observatory',
    kind: 'handout',
    summary:
      'A water-stained page by the last keeper, describing the removal of the great lens and a promise made to a stranger.',
    content: [
      'The lens is gone and I will say who took it: nobody. It lifted out of its mount in the night, wrapped in its own light, and sank into the floor like a coin into a bath. The mount is warm to the hand.',
      'The ward lines have shifted three degrees west since the last survey. I traced them across the table to the harbor and the line ends at a mark I do not know. Under it, someone has scratched, in a childish hand, a bell.',
      'I have asked the Guild to send a surveyor. I have also put my notes in the stair wall, behind the third stone, in case the surveyor is not who the Guild sends.',
    ],
    visibility: 'shared',
    sessionIds: ['session-4', 'session-8'],
    clueIds: ['clue-spire-lens-inscription'],
    questIds: ['quest-fractured-spire'],
    locationIds: ['location-fractured-spire'],
    factionIds: ['faction-lantern-guild'],
  },
  {
    id: 'handout-kael-dismissal-order',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Dismissal Order: Officer Kael Ardyn',
    kind: 'handout',
    summary:
      "The Watch order that ended Kael's service, carrying a genuine seal and a suspicious date.",
    content: [
      'To the Harbor Watch Muster Clerk: Officer Kael Ardyn is relieved of duty effective immediately for conduct unbecoming a member of the Watch, including dereliction at the harbor chain and the loss of confiscated property.',
      'Authorized by Warden E. Rook, Commander of the Harbor Watch. Witnessed: one clerk, name obscured by a water stain.',
      'Dated the eleventh of Tidewane. The incident at the harbor chain is recorded in the Watch log as occurring on the twelfth.',
    ],
    visibility: 'shared',
    sessionIds: ['session-8', 'session-10'],
    clueIds: ['clue-kaels-dismissal-seal'],
    questIds: ['quest-clear-kaels-name'],
    locationIds: ['location-old-customs-house'],
    factionIds: ['faction-harbor-watch'],
  },
  {
    id: 'handout-crimson-wake-debt-note',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Crimson Wake Debt Note',
    kind: 'handout',
    summary:
      "A courteous letter to Mira's father that reads like a receipt and a threat.",
    content: [
      'Esteemed Master Vale: the Wake acknowledges receipt of the three nights of passage and the silence regarding the cargo of the Quiet Heron. In the old way, a favor has been given and a favor is owed.',
      'We do not ask for coin. We will ask once, at a time of our choosing, and the asking will be small. Please accept the enclosed token as proof of our regard. The second line has been left blank for the family to read in its own time.',
      'Written beneath, in a different hand: "The favor is a person. Ask her."',
    ],
    visibility: 'shared',
    sessionIds: ['session-5', 'session-9'],
    clueIds: ['clue-mira-debt-token'],
    questIds: ['quest-a-debt-in-blood'],
    locationIds: [
      'location-salty-mast',
      'location-north-docks',
      'location-veyra-coast',
    ],
    factionIds: ['faction-crimson-wake'],
  },
  {
    id: 'lore-synod-ash-script',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Primer on Synod Ash-Script',
    kind: 'lore',
    summary:
      'DM reference on how the Synod ash-ink is made, what it fluoresces under, and who can write it.',
    content: [
      'Ash-script is written with ink ground from funeral pyre embers and fixed with lantern oil. Under a lit lantern it glows faintly green. Only ordained ash-readers are taught the cursive hand, and every reader signs with a trailing curl that identifies them.',
      'The royal Veyra seal is not part of the script. Its appearance on the Ember Key crate means someone has combined the two sets of marks on purpose, which only an ash-reader with access to pre-Veyran documents could do.',
      'Brother Tamsin knows the combined mark. He has drawn it four times on the Synod orders. If pressed he will admit the curl on the Entry Writ is his own.',
    ],
    visibility: 'dm-only',
    sessionIds: ['session-10', 'session-11'],
    clueIds: ['clue-strange-symbol', 'clue-ash-script-forgery'],
    questIds: ['quest-ash-and-ink'],
    locationIds: ['location-synod-relief-house'],
    factionIds: ['faction-ashen-synod'],
  },
  {
    id: 'lore-sinking-of-veyra',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'The Sinking of Old Veyra',
    kind: 'lore',
    summary:
      'A folk history of the night the royal quarter went under the bay, as sung in dockside taverns.',
    content: [
      'They say the bay was calm. The Queen of Veyra, grey with grief and clever with a crown, called the bells of the royal quarter and asked the sea to take the city rather than let it fall to the Hollow King. The sea, being a courtier, agreed.',
      'In the tavern version the bells ring three times and the city goes down in a single breath. In the temple version they ring once and the Queen is judged. In the Choir version they have never stopped ringing, and the drowned court is listening for someone to answer.',
      'The DM can use any version, but the truth is simpler and worse: the Queen sealed the vault with the court still inside, and the Ember Key was meant to be melted down. It never was.',
    ],
    visibility: 'dm-only',
    sessionIds: ['session-6', 'session-8'],
    clueIds: [],
    questIds: ['quest-whispers-beneath-veyra'],
    locationIds: ['location-glass-harbor', 'location-black-shoals'],
    factionIds: ['faction-choir-below', 'faction-lantern-guild'],
  },
  {
    id: 'handout-salty-mast-rumors',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Rumors from the Salty Mast',
    kind: 'handout',
    summary:
      'Six rumors scribbled on the back of a bar tab; two are true, one is dangerous, three are noise.',
    content: [
      '1. "The Watch burned a boat full of kiln glass last week, and the glass screamed." (False; a cargo of bottles shattered in a fire.) 2. "Selka Marr never sleeps, she just sits in the back room and listens to the drain." (True, and the drain is the point.)',
      '3. "A priest was seen buying lamp oil by the barrel on Third Quay." (True; the Synod ink runs hot.) 4. "The harbor chain sings on the lowest tides." (True.) 5. "The Concord is buying houses with cellars." (True; they are looking for the old stair.)',
      '6. "If you stand on the South Pier at the right ebb and hold a coin to your ear, you can hear someone counting." (A trap; the Choir uses it to find volunteers.) Mara has scrawled across the bottom: "Do not tell the children."',
    ],
    visibility: 'shared',
    sessionIds: ['session-9', 'session-12'],
    clueIds: ['clue-cellar-grate-tally'],
    questIds: ['quest-whispers-beneath-veyra'],
    locationIds: ['location-salty-mast'],
    factionIds: ['faction-choir-below', 'faction-crimson-wake'],
  },
  {
    id: 'handout-harbor-map-legend',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Harbor District Map Legend',
    kind: 'handout',
    summary:
      'The Lantern Guild chart key explaining berth numbers, chain marks and the six wards.',
    content: [
      'Berths run north to south, 1 to 14. Odd numbers are Concord leased, even numbers are Watch bonded. Pier 6 is the only even berth on the east chain that has not been inspected in two years.',
      'A dotted blue line marks the old tide line. A filled star marks a bell post. The Guild charts four posts; the fifth, in the lowest cellar of the Customs House, is drawn in pencil and has been erased twice.',
      'In the corner: "Crew rolls kept by the Watch are copies. The originals are with the chandler, who writes down the people who actually eat."',
    ],
    visibility: 'shared',
    sessionIds: ['session-8', 'session-11'],
    clueIds: ['clue-dawn-petrel-crew-roll'],
    questIds: ['quest-find-ember-key'],
    locationIds: ['location-north-docks', 'location-glass-harbor'],
    factionIds: ['faction-lantern-guild'],
  },
  {
    id: 'lore-concord-salvage-decree',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Concord Salvage Decree',
    kind: 'lore',
    summary:
      'A public decree posted at the counting hall claiming exclusive salvage rights beneath the old tide line.',
    content: [
      'By the authority of the Gilded Concord and by the terms of the Azure Compact, all salvage below the tide line of Glass Harbor shall be conducted only under Concord charter. Unlicensed dives are declared theft and subject to forfeiture.',
      'Charters are available to responsible parties who agree to submit copies of every relic, chart or record recovered. The Concord reserves first right of purchase on any object of royal origin.',
      'Posted in smaller type at the foot of the decree: "Sealed vaults are excluded from this clause pending determination of heirs." The DM should note that this carve-out applies to exactly one place.',
    ],
    visibility: 'shared',
    sessionIds: ['session-10'],
    clueIds: [],
    questIds: ['quest-find-ember-key'],
    locationIds: ['location-counting-hall'],
    factionIds: ['faction-gilded-concord'],
  },
  {
    id: 'handout-tamsin-confession',
    campaignId: 'campaign-ashes-of-veyra',
    title: "Brother Tamsin's Confession",
    kind: 'handout',
    summary:
      'A frightened, hurried letter slipped under the party door at the Salty Mast.',
    content: [
      'I am writing this at the relief house stove with a hand that will not stop shaking. I wrote the Port Authority endorsement. I wrote four manifests before it. Prelate Voss gave me the names and the weights and told me they were sacred work.',
      'I did not know the cargo until the Dawn Petrel came in. I smelled it on the paper, the same char-and-brine smell as the funeral stones. I do not think it is a relic. I think it is a door.',
      'If I am gone when you read this, do not look for me at the relief house. Ask Mara Venn about the third table. T.O.',
    ],
    visibility: 'shared',
    sessionIds: ['session-11', 'session-12'],
    clueIds: ['clue-ash-script-forgery'],
    questIds: ['quest-ash-and-ink'],
    locationIds: ['location-synod-relief-house', 'location-salty-mast'],
    factionIds: ['faction-ashen-synod'],
  },
];
