import type { FolderRecord, LibraryObject } from './types';

export const libraryObjects: LibraryObject[] = [
  {
    id: 'scene-glass-harbor-docks',
    title: 'Glass Harbor Docks',
    kind: 'scene',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Today',
  },
  {
    id: 'npc-captain-serin',
    title: 'Captain Serin',
    kind: 'npc',
    folderActId: 'act-glass-harbor',
    updatedLabel: '42 minutes ago',
  },
  {
    id: 'encounter-dockside-ambush',
    title: 'Dockside Ambush',
    kind: 'encounter',
    folderActId: 'act-glass-harbor',
    updatedLabel: '18 minutes ago',
  },
  {
    id: 'handout-burned-shipping-ledger',
    title: 'Burned Shipping Ledger',
    kind: 'handout',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Today',
  },
  {
    id: 'faction-azure-compact',
    title: 'The Azure Compact',
    kind: 'lore',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-selka-marr',
    title: 'Selka Marr',
    kind: 'npc',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-harbormasters-warning',
    title: "Harbormaster's Warning",
    kind: 'handout',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Today',
  },
  {
    id: 'quest-find-ember-key',
    title: 'Find the Ember Key',
    kind: 'quest',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Today',
  },
  {
    id: 'npc-elian-rook',
    title: 'Warden Elian Rook',
    kind: 'npc',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-oren-voss',
    title: 'Prelate Oren Voss',
    kind: 'npc',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-brother-tamsin',
    title: 'Brother Tamsin Ose',
    kind: 'npc',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-kestrel-ruhn',
    title: 'Kestrel Ruhn',
    kind: 'npc',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Today',
  },
  {
    id: 'npc-ysolde-marrow',
    title: 'Ysolde Marrow, the Tidewife',
    kind: 'npc',
    folderActId: 'act-glass-harbor',
    updatedLabel: '3 days ago',
  },
  {
    id: 'npc-neris-quill',
    title: 'Neris Quill',
    kind: 'npc',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Last week',
  },
  {
    id: 'encounter-warehouse-fire',
    title: "Fire on Fishmongers' Row",
    kind: 'encounter',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Last week',
  },
  {
    id: 'encounter-flooded-undercroft',
    title: 'The Flooded Undercroft',
    kind: 'encounter',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-rook-confrontation',
    title: 'Confronting Warden Rook',
    kind: 'encounter',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-wreck-scavengers',
    title: 'Scavengers of the Northstar Wreck',
    kind: 'encounter',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Last month',
  },
  {
    id: 'encounter-spire-wards',
    title: 'Guardians of the Fractured Spire',
    kind: 'encounter',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Last month',
  },
  {
    id: 'handout-tamsin-confession',
    title: "Brother Tamsin's Confession",
    kind: 'handout',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Last week',
  },
  {
    id: 'handout-kael-dismissal-order',
    title: 'Dismissal Order: Officer Kael Ardyn',
    kind: 'handout',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Last week',
  },
  {
    id: 'handout-northstar-captains-log',
    title: "Captain's Log of the Northstar",
    kind: 'handout',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Last month',
  },
  {
    id: 'handout-observatory-journal-page',
    title: 'Journal Page from the Spire Observatory',
    kind: 'handout',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Last month',
  },
  {
    id: 'lore-synod-ash-script',
    title: 'Primer on Synod Ash-Script',
    kind: 'lore',
    folderActId: 'act-glass-harbor',
    updatedLabel: '3 days ago',
  },
  {
    id: 'lore-sinking-of-veyra',
    title: 'The Sinking of Old Veyra',
    kind: 'lore',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Last month',
  },
  {
    id: 'faction-gilded-concord',
    title: 'Gilded Concord',
    kind: 'faction',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Last week',
  },
  {
    id: 'faction-crimson-wake',
    title: 'The Crimson Wake',
    kind: 'faction',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'quest-clear-kaels-name',
    title: "Clear Kael's Name",
    kind: 'quest',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Yesterday',
  },
  {
    id: 'quest-ash-and-ink',
    title: 'Ash and Ink',
    kind: 'quest',
    folderActId: 'act-glass-harbor',
    updatedLabel: 'Last week',
  },
  {
    id: 'quest-survive-the-shoals',
    title: 'Survive the Black Shoals',
    kind: 'quest',
    folderActId: 'act-fractured-tides',
    updatedLabel: 'Last month',
  },
];

export const folders: FolderRecord[] = [
  {
    id: 'folder-act-one',
    title: 'Act I - Fractured Tides',
    actId: 'act-fractured-tides',
    objectIds: [
      'faction-azure-compact',
      'npc-neris-quill',
      'encounter-wreck-scavengers',
      'encounter-spire-wards',
      'handout-northstar-captains-log',
      'handout-observatory-journal-page',
      'lore-sinking-of-veyra',
      'quest-survive-the-shoals',
    ],
    children: [
      { kind: 'scene', count: 6 },
      { kind: 'npc', count: 8 },
      { kind: 'encounter', count: 4 },
      { kind: 'handout', count: 3 },
    ],
  },
  {
    id: 'folder-act-two',
    title: 'Act II - The Glass Harbor',
    actId: 'act-glass-harbor',
    objectIds: [
      'scene-glass-harbor-docks',
      'npc-captain-serin',
      'npc-selka-marr',
      'encounter-dockside-ambush',
      'handout-burned-shipping-ledger',
      'handout-harbormasters-warning',
      'quest-find-ember-key',
      'npc-elian-rook',
      'npc-oren-voss',
      'npc-brother-tamsin',
      'npc-kestrel-ruhn',
      'npc-ysolde-marrow',
      'encounter-warehouse-fire',
      'encounter-flooded-undercroft',
      'encounter-rook-confrontation',
      'handout-tamsin-confession',
      'handout-kael-dismissal-order',
      'lore-synod-ash-script',
      'faction-gilded-concord',
      'faction-crimson-wake',
      'quest-clear-kaels-name',
      'quest-ash-and-ink',
    ],
    children: [
      { kind: 'scene', count: 7 },
      { kind: 'npc', count: 12 },
      { kind: 'encounter', count: 5 },
      { kind: 'handout', count: 6 },
    ],
  },
  {
    id: 'folder-act-three',
    title: 'Act III - The Hollow Crown',
    actId: 'act-hollow-crown',
    objectIds: [],
    children: [
      { kind: 'scene', count: 5 },
      { kind: 'npc', count: 8 },
      { kind: 'encounter', count: 3 },
      { kind: 'handout', count: 5 },
    ],
  },
];
