import type { CampaignMap, MapPin } from './types';

export const MAP_GLASS_HARBOR_ID = 'map-glass-harbor';

export const maps: CampaignMap[] = [
  {
    id: MAP_GLASS_HARBOR_ID,
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Glass Harbor District',
    description:
      'Top-down working map of the Glass Harbor waterfront and adjoining market wards.',
    imagePath: '/demo/ashes-of-veyra/glass-harbor-map.png',
    locationIds: [
      'location-north-docks',
      'location-salty-mast',
      'location-fishmongers-row',
      'location-old-customs-house',
      'location-harbor-warehouse',
      'location-south-pier',
    ],
    layers: [
      {
        id: 'layer-locations',
        label: 'Locations',
        visibleByDefault: true,
        locationIds: [
          'location-north-docks',
          'location-salty-mast',
          'location-fishmongers-row',
          'location-old-customs-house',
          'location-harbor-warehouse',
          'location-south-pier',
        ],
      },
      {
        id: 'layer-encounters',
        label: 'Encounters',
        visibleByDefault: true,
        locationIds: [
          'location-north-docks',
          'location-salty-mast',
          'location-fishmongers-row',
          'location-old-customs-house',
          'location-harbor-warehouse',
          'location-south-pier',
        ],
      },
      {
        id: 'layer-npcs',
        label: 'NPCs',
        visibleByDefault: true,
        locationIds: [
          'location-north-docks',
          'location-salty-mast',
          'location-fishmongers-row',
          'location-old-customs-house',
          'location-harbor-warehouse',
          'location-south-pier',
        ],
      },
      {
        id: 'layer-notes',
        label: 'Notes',
        visibleByDefault: true,
        locationIds: ['location-old-customs-house', 'location-south-pier'],
      },
      {
        id: 'layer-environment',
        label: 'Environment',
        visibleByDefault: true,
        locationIds: ['location-south-pier', 'location-north-docks'],
      },
      {
        id: 'layer-grid',
        label: 'Grid',
        visibleByDefault: false,
        locationIds: [],
      },
      {
        id: 'layer-labels',
        label: 'Labels',
        visibleByDefault: false,
        locationIds: [],
      },
      {
        id: 'layer-fog-of-war',
        label: 'Fog of War',
        visibleByDefault: false,
        locationIds: [],
      },
    ],
  },
];

export const mapPins: MapPin[] = [
  {
    id: 'pin-north-docks',
    mapId: MAP_GLASS_HARBOR_ID,
    locationId: 'location-north-docks',
    label: 'North Docks',
    order: 1,
    x: 0.25,
    y: 0.2,
    layerIds: ['layer-locations', 'layer-encounters', 'layer-npcs'],
    linkedObjectIds: [
      'encounter-dockside-ambush',
      'npc-selka-marr',
      'handout-burned-shipping-ledger',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-salty-mast',
    mapId: MAP_GLASS_HARBOR_ID,
    locationId: 'location-salty-mast',
    label: 'The Salty Mast Tavern',
    order: 2,
    x: 0.36,
    y: 0.53,
    layerIds: ['layer-locations', 'layer-encounters', 'layer-npcs'],
    linkedObjectIds: [
      'npc-mara-venn',
      'encounter-drowned-cellar',
      'lore-bell-rhyme-shoals',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-fishmongers-row',
    mapId: MAP_GLASS_HARBOR_ID,
    locationId: 'location-fishmongers-row',
    label: "Fishmongers' Row",
    order: 3,
    x: 0.51,
    y: 0.39,
    layerIds: ['layer-locations', 'layer-encounters', 'layer-npcs'],
    linkedObjectIds: ['handout-burned-shipping-ledger', 'npc-neris-quill'],
    selectedByDefault: false,
  },
  {
    id: 'pin-old-customs-house',
    mapId: MAP_GLASS_HARBOR_ID,
    locationId: 'location-old-customs-house',
    label: 'Old Customs House',
    order: 4,
    x: 0.66,
    y: 0.42,
    layerIds: [
      'layer-locations',
      'layer-encounters',
      'layer-npcs',
      'layer-notes',
    ],
    linkedObjectIds: [
      'npc-captain-serin',
      'encounter-dockside-ambush',
      'scene-harbor-warehouse-template',
      'handout-harbormasters-warning',
    ],
    selectedByDefault: true,
  },
  {
    id: 'pin-harbor-warehouse',
    mapId: MAP_GLASS_HARBOR_ID,
    locationId: 'location-harbor-warehouse',
    label: 'Harbor Warehouse',
    order: 5,
    x: 0.75,
    y: 0.27,
    layerIds: ['layer-locations', 'layer-encounters', 'layer-npcs'],
    linkedObjectIds: [
      'encounter-dockside-ambush',
      'npc-selka-marr',
      'handout-burned-shipping-ledger',
    ],
    selectedByDefault: false,
  },
  {
    id: 'pin-south-pier',
    mapId: MAP_GLASS_HARBOR_ID,
    locationId: 'location-south-pier',
    label: 'South Pier',
    order: 6,
    x: 0.79,
    y: 0.68,
    layerIds: [
      'layer-locations',
      'layer-encounters',
      'layer-npcs',
      'layer-notes',
      'layer-environment',
    ],
    linkedObjectIds: [
      'encounter-dockside-ambush',
      'encounter-sahuagin-patrol',
      'npc-captain-serin',
    ],
    selectedByDefault: false,
  },
];
