import type { CampaignQuest, QuestObjective } from './types';

export const quests: CampaignQuest[] = [
  {
    id: 'quest-find-ember-key',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Find the Ember Key',
    status: 'active',
    priority: 'high',
    summary:
      'Trace the ember-marked shipment and secure the key before either rival faction can claim it.',
    giverNpcId: 'npc-captain-serin',
    factionIds: [
      'faction-harbor-watch',
      'faction-crimson-wake',
      'faction-ashen-synod',
    ],
    sessionIds: ['session-10', 'session-11', 'session-12', 'session-13'],
    locationIds: [
      'location-fishmongers-row',
      'location-old-customs-house',
      'location-harbor-warehouse',
      'location-south-pier',
    ],
    objectiveIds: [
      'objective-confirm-ship',
      'objective-decode-ledger',
      'objective-enter-tunnel',
      'objective-secure-key',
    ],
  },
  {
    id: 'quest-fractured-spire',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'The Fractured Spire',
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Identify the missing observatory lens and learn why its ward pattern points toward the harbor.',
    factionIds: ['faction-lantern-guild'],
    sessionIds: ['session-4', 'session-8'],
    locationIds: ['location-glass-harbor'],
    objectiveIds: ['objective-find-missing-lens', 'objective-compare-wards'],
  },
  {
    id: 'quest-a-debt-in-blood',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'A Debt in Blood',
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Discover what Mira Vale family promised Selka Marr and choose how the debt will be settled.',
    factionIds: ['faction-crimson-wake'],
    sessionIds: ['session-5', 'session-9', 'session-12'],
    locationIds: ['location-salty-mast', 'location-north-docks'],
    objectiveIds: ['objective-learn-family-promise', 'objective-settle-debt'],
  },
  {
    id: 'quest-whispers-beneath-veyra',
    campaignId: 'campaign-ashes-of-veyra',
    title: 'Whispers Beneath Veyra',
    status: 'not-started',
    priority: 'low',
    summary:
      'Trace the drowned bell song to its source before the Choir Below finishes its awakening.',
    factionIds: ['faction-choir-below', 'faction-lantern-guild'],
    sessionIds: ['session-6', 'session-13'],
    locationIds: ['location-south-pier', 'location-old-customs-house'],
    objectiveIds: [
      'objective-record-bell-sequence',
      'objective-find-voice-survivor',
    ],
  },
];

export const questObjectives: QuestObjective[] = [
  {
    id: 'objective-confirm-ship',
    questId: 'quest-find-ember-key',
    order: 1,
    title: 'Confirm which ship delivered the ember-marked crate',
    status: 'active',
    clueIds: ['clue-strange-symbol', 'clue-sahuagin-activity'],
    locationIds: ['location-north-docks', 'location-harbor-warehouse'],
  },
  {
    id: 'objective-decode-ledger',
    questId: 'quest-find-ember-key',
    order: 2,
    title: 'Decode the Burned Shipping Ledger',
    status: 'active',
    clueIds: ['clue-smuggler-note', 'clue-strange-symbol'],
    locationIds: ['location-fishmongers-row', 'location-south-pier'],
  },
  {
    id: 'objective-enter-tunnel',
    questId: 'quest-find-ember-key',
    order: 3,
    title: 'Enter the tunnel beneath the Old Customs House',
    status: 'pending',
    clueIds: ['clue-sahuagin-activity'],
    locationIds: ['location-old-customs-house'],
  },
  {
    id: 'objective-secure-key',
    questId: 'quest-find-ember-key',
    order: 4,
    title: 'Secure the key before the Synod or Crimson Wake',
    status: 'pending',
    clueIds: ['clue-strange-symbol'],
    locationIds: ['location-harbor-warehouse', 'location-south-pier'],
  },
  {
    id: 'objective-find-missing-lens',
    questId: 'quest-fractured-spire',
    order: 1,
    title: 'Identify the missing lens from the observatory',
    status: 'active',
    clueIds: ['clue-broken-compass'],
    locationIds: ['location-glass-harbor'],
  },
  {
    id: 'objective-compare-wards',
    questId: 'quest-fractured-spire',
    order: 2,
    title: "Compare its runes with Lira's harbor ward sketches",
    status: 'pending',
    clueIds: ['clue-strange-symbol'],
    locationIds: ['location-old-customs-house'],
  },
  {
    id: 'objective-learn-family-promise',
    questId: 'quest-a-debt-in-blood',
    order: 1,
    title: 'Learn what Mira family promised Selka Marr',
    status: 'active',
    clueIds: ['clue-smuggler-note'],
    locationIds: ['location-salty-mast'],
  },
  {
    id: 'objective-settle-debt',
    questId: 'quest-a-debt-in-blood',
    order: 2,
    title: 'Choose whether to honor, repay, or break the debt',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-salty-mast', 'location-north-docks'],
  },
  {
    id: 'objective-record-bell-sequence',
    questId: 'quest-whispers-beneath-veyra',
    order: 1,
    title: 'Record the drowned bell sequence',
    status: 'pending',
    clueIds: ['clue-sahuagin-activity'],
    locationIds: ['location-south-pier'],
  },
  {
    id: 'objective-find-voice-survivor',
    questId: 'quest-whispers-beneath-veyra',
    order: 2,
    title: 'Find a survivor who has heard the same voices',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-salty-mast', 'location-south-pier'],
  },
];
