import type { CampaignQuest, QuestObjective } from './types';

const CAMPAIGN_ID = 'campaign-ashes-of-veyra';

export const quests: CampaignQuest[] = [
  {
    id: 'quest-find-ember-key',
    campaignId: CAMPAIGN_ID,
    title: 'Find the Ember Key',
    status: 'active',
    priority: 'high',
    summary:
      'Trace the ember-marked shipment and secure the key before either rival faction can claim it. The Dawn Petrel carried it in under a kiln-glass manifest, and every faction now believes the party knows where it is.',
    giverNpcId: 'npc-captain-serin',
    factionIds: [
      'faction-harbor-watch',
      'faction-crimson-wake',
      'faction-ashen-synod',
      'faction-gilded-concord',
    ],
    sessionIds: ['session-10', 'session-11', 'session-12', 'session-13'],
    locationIds: [
      'location-fishmongers-row',
      'location-old-customs-house',
      'location-harbor-warehouse',
      'location-south-pier',
      'location-flooded-undercroft',
    ],
    objectiveIds: [
      'objective-confirm-ship',
      'objective-decode-ledger',
      'objective-enter-tunnel',
      'objective-secure-key',
    ],
  },
  {
    id: 'quest-fractured-spire',
    campaignId: CAMPAIGN_ID,
    title: 'The Fractured Spire',
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Identify the missing observatory lens and learn why its ward pattern points toward the harbor. Paused while the Ember Key trail runs hot, but the lens inscription keeps resurfacing.',
    giverNpcId: 'npc-neris-quill',
    factionIds: ['faction-lantern-guild'],
    sessionIds: ['session-4', 'session-8'],
    locationIds: ['location-glass-harbor', 'location-fractured-spire'],
    objectiveIds: [
      'objective-find-missing-lens',
      'objective-compare-wards',
      'objective-trace-ward-line',
    ],
  },
  {
    id: 'quest-a-debt-in-blood',
    campaignId: CAMPAIGN_ID,
    title: 'A Debt in Blood',
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Discover what Mira Vale family promised Selka Marr and choose how the debt will be settled. Selka has offered to sell the terms back for the Ember Key itself.',
    giverNpcId: 'npc-selka-marr',
    factionIds: ['faction-crimson-wake'],
    sessionIds: ['session-5', 'session-9', 'session-12'],
    locationIds: ['location-salty-mast', 'location-north-docks'],
    objectiveIds: [
      'objective-learn-family-promise',
      'objective-settle-debt',
      'objective-weigh-selkas-offer',
    ],
  },
  {
    id: 'quest-whispers-beneath-veyra',
    campaignId: CAMPAIGN_ID,
    title: 'Whispers Beneath Veyra',
    status: 'not-started',
    priority: 'low',
    summary:
      'Trace the drowned bell song to its source before the Choir Below finishes its awakening. The party has heard the bells twice but has not yet chosen to follow them.',
    giverNpcId: 'npc-mara-venn',
    factionIds: ['faction-choir-below', 'faction-lantern-guild'],
    sessionIds: ['session-6', 'session-13'],
    locationIds: [
      'location-south-pier',
      'location-old-customs-house',
      'location-flooded-undercroft',
    ],
    objectiveIds: [
      'objective-record-bell-sequence',
      'objective-find-voice-survivor',
      'objective-trace-bell-to-source',
    ],
  },
  {
    id: 'quest-survive-the-shoals',
    campaignId: CAMPAIGN_ID,
    title: 'Survive the Black Shoals',
    status: 'complete',
    priority: 'high',
    summary:
      'Escape the wreck of the Northstar, recover the ember-marked crate that was never meant to reach shore, and learn who is stalking the survivors through the shallows.',
    factionIds: ['faction-sunken-reach'],
    sessionIds: ['session-1', 'session-3'],
    locationIds: ['location-black-shoals', 'location-veyra-coast'],
    objectiveIds: [
      'objective-recover-first-crate',
      'objective-escape-the-shoals',
      'objective-read-sahuagin-sign',
    ],
    resolution:
      'The party reached shore with the crate and four survivors, found that the Northstar had been scuttled from within, and learned the sahuagin tracks were guarding something rather than hunting them.',
  },
  {
    id: 'quest-lantern-road-escort',
    campaignId: CAMPAIGN_ID,
    title: 'The Lantern Road Escort',
    status: 'complete',
    priority: 'medium',
    summary:
      'Bring the shipwreck refugees along the inland Lantern Road to the Guild waystation without losing anyone to bandits or the cold.',
    giverNpcId: 'npc-neris-quill',
    factionIds: ['faction-lantern-guild'],
    sessionIds: ['session-2'],
    locationIds: ['location-lantern-waystation', 'location-veyra-coast'],
    objectiveIds: ['objective-reach-waystation', 'objective-win-guild-trust'],
    resolution:
      'Every refugee arrived alive. Neris Quill formally recognized the party as friends of the Guild and gave them the first ward sketches.',
  },
  {
    id: 'quest-passage-to-veyra',
    campaignId: CAMPAIGN_ID,
    title: 'Passage to Veyra',
    status: 'complete',
    priority: 'medium',
    summary:
      'Secure legal passage and a harbor berth for the crate-bearing party, past a Concord inspection regime that treats every ember-marked hull as suspect.',
    giverNpcId: 'npc-neris-quill',
    factionIds: ['faction-lantern-guild', 'faction-gilded-concord'],
    sessionIds: ['session-7'],
    locationIds: ['location-veyra-coast', 'location-glass-harbor'],
    objectiveIds: [
      'objective-secure-writ',
      'objective-board-the-packet',
      'objective-clear-harbor-inspection',
    ],
    resolution:
      "The party sailed under a Lantern Guild writ of passage, hid the crate in a ballast barrel, and cleared Glass Harbor inspection thanks to Kael's old password.",
  },
  {
    id: 'quest-clear-kaels-name',
    campaignId: CAMPAIGN_ID,
    title: "Clear Kael's Name",
    status: 'active',
    priority: 'high',
    summary:
      'Prove that the order dismissing Kael Ardyn from the Harbor Watch was forged, and find out who benefited. The paper trail runs through the same customs office that mislabeled the Dawn Petrel cargo.',
    giverNpcId: 'npc-dagan-corr',
    factionIds: ['faction-harbor-watch', 'faction-ashen-synod'],
    sessionIds: ['session-8', 'session-10', 'session-12', 'session-13'],
    locationIds: ['location-old-customs-house', 'location-fishmongers-row'],
    objectiveIds: [
      'objective-find-signing-clerk',
      'objective-prove-forged-order',
      'objective-confront-rook',
    ],
  },
  {
    id: 'quest-ash-and-ink',
    campaignId: CAMPAIGN_ID,
    title: 'Ash and Ink',
    status: 'active',
    priority: 'medium',
    summary:
      'Brother Tamsin confessed to forging customs paper for the Synod. Keep him alive, prove the ink came from the relief house, and decide who should hear his testimony.',
    giverNpcId: 'npc-brother-tamsin',
    factionIds: ['faction-ashen-synod', 'faction-harbor-watch'],
    sessionIds: ['session-10', 'session-11', 'session-12', 'session-13'],
    locationIds: ['location-synod-relief-house', 'location-fishmongers-row'],
    objectiveIds: [
      'objective-trace-ash-ink',
      'objective-shelter-tamsin',
      'objective-choose-witness-forum',
    ],
  },
];

export const questObjectives: QuestObjective[] = [
  {
    id: 'objective-confirm-ship',
    questId: 'quest-find-ember-key',
    order: 1,
    title: 'Confirm which ship delivered the ember-marked crate',
    status: 'active',
    clueIds: [
      'clue-strange-symbol',
      'clue-sahuagin-activity',
      'clue-dawn-petrel-crew-roll',
    ],
    locationIds: ['location-north-docks', 'location-harbor-warehouse'],
  },
  {
    id: 'objective-decode-ledger',
    questId: 'quest-find-ember-key',
    order: 2,
    title: 'Decode the Burned Shipping Ledger',
    status: 'active',
    clueIds: [
      'clue-smuggler-note',
      'clue-strange-symbol',
      'clue-third-bell-tide',
    ],
    locationIds: ['location-fishmongers-row', 'location-south-pier'],
  },
  {
    id: 'objective-enter-tunnel',
    questId: 'quest-find-ember-key',
    order: 3,
    title: 'Enter the tunnel beneath the Old Customs House',
    status: 'pending',
    clueIds: ['clue-sahuagin-activity', 'clue-cellar-grate-tally'],
    locationIds: ['location-old-customs-house', 'location-flooded-undercroft'],
  },
  {
    id: 'objective-secure-key',
    questId: 'quest-find-ember-key',
    order: 4,
    title: 'Secure the key before the Synod or Crimson Wake',
    status: 'pending',
    clueIds: ['clue-strange-symbol'],
    locationIds: ['location-harbor-warehouse', 'location-south-pier'],
  },
  {
    id: 'objective-find-missing-lens',
    questId: 'quest-fractured-spire',
    order: 1,
    title: 'Identify the missing lens from the observatory',
    status: 'active',
    clueIds: ['clue-broken-compass', 'clue-spire-lens-inscription'],
    locationIds: ['location-glass-harbor', 'location-fractured-spire'],
  },
  {
    id: 'objective-compare-wards',
    questId: 'quest-fractured-spire',
    order: 2,
    title: "Compare its runes with Lira's harbor ward sketches",
    status: 'pending',
    clueIds: ['clue-strange-symbol'],
    locationIds: ['location-old-customs-house'],
  },
  {
    id: 'objective-trace-ward-line',
    questId: 'quest-fractured-spire',
    order: 3,
    title: 'Trace the ward line from the spire to the harbor floor',
    status: 'pending',
    clueIds: ['clue-spire-lens-inscription'],
    locationIds: ['location-fractured-spire', 'location-flooded-undercroft'],
  },
  {
    id: 'objective-learn-family-promise',
    questId: 'quest-a-debt-in-blood',
    order: 1,
    title: 'Learn what Mira family promised Selka Marr',
    status: 'active',
    clueIds: ['clue-smuggler-note', 'clue-mira-debt-token'],
    locationIds: ['location-salty-mast'],
  },
  {
    id: 'objective-settle-debt',
    questId: 'quest-a-debt-in-blood',
    order: 2,
    title: 'Choose whether to honor, repay, or break the debt',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-salty-mast', 'location-north-docks'],
  },
  {
    id: 'objective-weigh-selkas-offer',
    questId: 'quest-a-debt-in-blood',
    order: 3,
    title: "Weigh Selka's offer: the debt terms for the Ember Key",
    status: 'pending',
    clueIds: ['clue-mira-debt-token'],
    locationIds: ['location-north-docks'],
  },
  {
    id: 'objective-record-bell-sequence',
    questId: 'quest-whispers-beneath-veyra',
    order: 1,
    title: 'Record the drowned bell sequence',
    status: 'pending',
    clueIds: ['clue-sahuagin-activity', 'clue-third-bell-tide'],
    locationIds: ['location-south-pier'],
  },
  {
    id: 'objective-find-voice-survivor',
    questId: 'quest-whispers-beneath-veyra',
    order: 2,
    title: 'Find a survivor who has heard the same voices',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-salty-mast', 'location-south-pier'],
  },
  {
    id: 'objective-trace-bell-to-source',
    questId: 'quest-whispers-beneath-veyra',
    order: 3,
    title: 'Trace the bell song to its source beneath the harbor',
    status: 'pending',
    clueIds: ['clue-cellar-grate-tally'],
    locationIds: ['location-flooded-undercroft'],
  },
  {
    id: 'objective-recover-first-crate',
    questId: 'quest-survive-the-shoals',
    order: 1,
    title: 'Recover the ember-marked crate from the wreck',
    status: 'complete',
    clueIds: ['clue-northstar-scuttled'],
    locationIds: ['location-black-shoals'],
  },
  {
    id: 'objective-escape-the-shoals',
    questId: 'quest-survive-the-shoals',
    order: 2,
    title: 'Reach the shore with the survivors',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-black-shoals', 'location-veyra-coast'],
  },
  {
    id: 'objective-read-sahuagin-sign',
    questId: 'quest-survive-the-shoals',
    order: 3,
    title: 'Read the sahuagin sign around the shoals',
    status: 'complete',
    clueIds: ['clue-sahuagin-activity'],
    locationIds: ['location-black-shoals'],
  },
  {
    id: 'objective-reach-waystation',
    questId: 'quest-lantern-road-escort',
    order: 1,
    title: 'Reach the Lantern Waystation with every refugee',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-lantern-waystation'],
  },
  {
    id: 'objective-win-guild-trust',
    questId: 'quest-lantern-road-escort',
    order: 2,
    title: 'Earn the Lantern Guild trust and its first ward sketches',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-lantern-waystation'],
  },
  {
    id: 'objective-secure-writ',
    questId: 'quest-passage-to-veyra',
    order: 1,
    title: 'Secure a writ of passage from the Lantern Guild',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-veyra-coast'],
  },
  {
    id: 'objective-board-the-packet',
    questId: 'quest-passage-to-veyra',
    order: 2,
    title: 'Board the harbor packet without exposing the crate',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-veyra-coast'],
  },
  {
    id: 'objective-clear-harbor-inspection',
    questId: 'quest-passage-to-veyra',
    order: 3,
    title: 'Clear the Glass Harbor inspection',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-glass-harbor'],
  },
  {
    id: 'objective-find-signing-clerk',
    questId: 'quest-clear-kaels-name',
    order: 1,
    title: 'Find the clerk who witnessed the dismissal order',
    status: 'active',
    clueIds: ['clue-kaels-dismissal-seal'],
    locationIds: ['location-old-customs-house'],
  },
  {
    id: 'objective-prove-forged-order',
    questId: 'quest-clear-kaels-name',
    order: 2,
    title: 'Prove the order was forged with Synod ash-ink',
    status: 'pending',
    clueIds: ['clue-ash-script-forgery', 'clue-kaels-dismissal-seal'],
    locationIds: ['location-old-customs-house', 'location-fishmongers-row'],
  },
  {
    id: 'objective-confront-rook',
    questId: 'quest-clear-kaels-name',
    order: 3,
    title: 'Confront Warden Rook with evidence the Watch cannot ignore',
    status: 'pending',
    clueIds: ['clue-ash-script-forgery'],
    locationIds: ['location-old-customs-house'],
  },
  {
    id: 'objective-trace-ash-ink',
    questId: 'quest-ash-and-ink',
    order: 1,
    title: 'Trace the forger ink back to the relief house',
    status: 'complete',
    clueIds: ['clue-ash-script-forgery'],
    locationIds: ['location-synod-relief-house'],
  },
  {
    id: 'objective-shelter-tamsin',
    questId: 'quest-ash-and-ink',
    order: 2,
    title: 'Keep Brother Tamsin alive and out of Voss reach',
    status: 'active',
    clueIds: [],
    locationIds: ['location-synod-relief-house', 'location-salty-mast'],
  },
  {
    id: 'objective-choose-witness-forum',
    questId: 'quest-ash-and-ink',
    order: 3,
    title: 'Choose where Tamsin testifies: Watch, Concord, or Guild',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-counting-hall', 'location-old-customs-house'],
  },
];
