import type {
  CharacterRecord,
  MonsterDefinition,
  EncounterTemplate,
  CampaignActor,
  SpellDefinition,
  SpellCollection,
  DomainCommand,
  DomainCommandReceipt,
} from '../src';

export const mockMartialCharacter: CharacterRecord = {
  id: '11111111-1111-4111-8111-111111111111',
  kind: 'character',
  schemaVersion: 1,
  revision: 1,
  ownerId: 'user-fighter-1',
  campaignId: null,
  name: 'Valeros the Fighter',
  tags: ['martial', 'fighter', 'tank'],
  archived: false,
  ruleset: {
    system: 'dnd5e',
    edition: '2024',
    contentPackId: 'srd-5.2.1',
    contentRevision: '1.0',
    rulesRevision: '1.0',
  },
  species: 'Human',
  class: 'Fighter',
  subclass: 'Champion',
  level: 5,
  alignment: 'Neutral Good',
  background: 'Soldier',
  abilities: {
    STR: { score: 18, modifier: 4 },
    DEX: { score: 14, modifier: 2 },
    CON: { score: 16, modifier: 3 },
    INT: { score: 10, modifier: 0 },
    WIS: { score: 12, modifier: 1 },
    CHA: { score: 8, modifier: -1 },
  },
  baseMaxHp: 49,
  speed: 30,
  armorClass: 18,
  proficiencyBonus: 3,
  features: [
    {
      id: 'second-wind',
      name: 'Second Wind',
      source: 'Fighter',
      description: 'Regain 1d10 + level HP as a bonus action',
      uses: {
        total: 2,
        used: 0,
        resetOn: 'short-rest',
      },
    },
  ],
  proficiencies: {
    skills: ['Athletics', 'Intimidation', 'Perception'],
    savingThrows: ['STR', 'CON'],
    armor: ['Light', 'Medium', 'Heavy', 'Shields'],
    weapons: ['Simple', 'Martial'],
    tools: ['Gaming Set'],
    languages: ['Common'],
  },
  createdAt: '2026-09-24T00:00:00Z',
  updatedAt: '2026-09-24T00:00:00Z',
};

export const mockWizardSpell: SpellDefinition = {
  id: '22222222-2222-4222-8222-222222222222',
  kind: 'spell',
  schemaVersion: 1,
  revision: 1,
  ownerId: 'system',
  name: 'Fireball',
  slug: 'fireball',
  tags: ['evocation', 'fire', 'aoe'],
  archived: false,
  ruleset: {
    system: 'dnd5e',
    edition: '2024',
    contentPackId: 'srd-5.2.1',
    contentRevision: '1.0',
    rulesRevision: '1.0',
  },
  level: 3,
  school: 'evocation',
  castingTime: '1 action',
  range: '150 feet',
  duration: 'Instantaneous',
  concentration: false,
  ritual: false,
  components: {
    verbal: true,
    somatic: true,
    material: true,
    materialDescription: 'A tiny ball of bat guano and sulfur',
    materialConsumed: false,
  },
  description: 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.',
  higherLevelsDescription: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
  classes: ['wizard', 'sorcerer'],
  createdAt: '2026-09-24T00:00:00Z',
  updatedAt: '2026-09-24T00:00:00Z',
};

export const mockSpellCollection: SpellCollection = {
  id: '33333333-3333-4333-8333-333333333333',
  kind: 'spell_collection',
  schemaVersion: 1,
  revision: 1,
  ownerId: 'user-wizard-1',
  name: "Gildas's Travel Grimoire",
  tags: ['grimoire', 'wizard'],
  archived: false,
  ruleset: {
    system: 'dnd5e',
    edition: '2024',
    contentPackId: 'srd-5.2.1',
    contentRevision: '1.0',
    rulesRevision: '1.0',
  },
  spells: [
    {
      spellRef: {
        kind: 'spell',
        id: mockWizardSpell.id,
        revision: 1,
      },
      slug: 'fireball',
      order: 1,
      notes: 'Acquired from the ruined tower in the marsh.',
      isFavorite: true,
    },
  ],
  createdAt: '2026-09-24T00:00:00Z',
  updatedAt: '2026-09-24T00:00:00Z',
};

export const mockGoblinMonster: MonsterDefinition = {
  id: '44444444-4444-4444-8444-444444444444',
  kind: 'monster',
  schemaVersion: 1,
  revision: 1,
  ownerId: 'system',
  name: 'Goblin Skirmisher',
  tags: ['goblinoid', 'humanoid', 'low-level'],
  archived: false,
  ruleset: {
    system: 'dnd5e',
    edition: '2024',
    contentPackId: 'srd-5.2.1',
    contentRevision: '1.0',
    rulesRevision: '1.0',
  },
  size: 'Small',
  monsterType: 'humanoid',
  subtype: 'goblinoid',
  alignment: 'Neutral Evil',
  armorClass: [{ value: 15, type: 'armor', description: 'Leather Armor, Shield' }],
  hitPoints: { average: 7, roll: '2d6' },
  speed: { walk: 30 },
  abilities: {
    STR: { score: 8, modifier: -1 },
    DEX: { score: 14, modifier: 2 },
    CON: { score: 10, modifier: 0 },
    INT: { score: 10, modifier: 0 },
    WIS: { score: 8, modifier: -1 },
    CHA: { score: 8, modifier: -1 },
  },
  challengeRating: 0.25,
  experiencePoints: 50,
  proficiencyBonus: 2,
  savingThrows: {},
  skills: { Stealth: 6 },
  damageVulnerabilities: [],
  damageResistances: [],
  damageImmunities: [],
  conditionImmunities: [],
  senses: { darkvision: 60, passivePerception: 9 },
  languages: ['Common', 'Goblin'],
  specialAbilities: [
    {
      id: 'nimble-escape',
      name: 'Nimble Escape',
      description: 'The goblin can take the Disengage or Hide action as a bonus action on each of its turns.',
    },
  ],
  actions: [
    {
      id: 'scimitar',
      name: 'Scimitar',
      description: 'Melee Weapon Attack',
      attackBonus: 4,
      damage: [{ dice: '1d6 + 2', type: 'slashing' }],
    },
  ],
  reactions: [],
  createdAt: '2026-09-24T00:00:00Z',
  updatedAt: '2026-09-24T00:00:00Z',
};

export const mockEncounterTemplate: EncounterTemplate = {
  id: '55555555-5555-4555-8555-555555555555',
  kind: 'encounter',
  schemaVersion: 1,
  revision: 1,
  ownerId: 'dm-1',
  campaignId: '99999999-9999-4999-8999-999999999999',
  name: 'Goblin Ambush at Bridge',
  tags: ['ambush', 'bridge', 'forest'],
  archived: false,
  ruleset: {
    system: 'dnd5e',
    edition: '2024',
    contentPackId: 'srd-5.2.1',
    contentRevision: '1.0',
    rulesRevision: '1.0',
  },
  groups: [
    {
      id: '66666666-6666-4666-8666-666666666666',
      monsterRef: {
        kind: 'monster',
        id: mockGoblinMonster.id,
        revision: 1,
      },
      count: 3,
      faction: 'hostile',
      customName: 'Bridge Goblins',
      waveIndex: 0,
      overrides: {},
    },
  ],
  rewardRefs: [],
  environmentNotes: 'Heavy rain, muddy terrain.',
  createdAt: '2026-09-24T00:00:00Z',
  updatedAt: '2026-09-24T00:00:00Z',
};

export const mockCampaignActor: CampaignActor = {
  campaignActorId: '77777777-7777-4777-8777-777777777777',
  campaignId: '99999999-9999-4999-8999-999999999999',
  name: 'Valeros the Fighter',
  actorKind: 'pc',
  sourceRef: {
    kind: 'character',
    id: mockMartialCharacter.id,
    revision: 1,
  },
  ruleset: mockMartialCharacter.ruleset,
  stateVersion: 1,
  controllerUserIds: ['user-fighter-1'],
  activeSessionId: null,
  hp: {
    current: 49,
    max: 49,
    temp: 0,
  },
  deathSaves: {
    successes: 0,
    failures: 0,
  },
  conditions: [],
  concentration: null,
  resourcePools: {
    'action-surge': {
      id: 'action-surge',
      name: 'Action Surge',
      poolType: 'uses',
      current: 1,
      max: 1,
      resetOn: 'short-rest',
    },
  },
  spellcastingProfiles: [],
  inventory: [],
  pcPayload: {
    species: 'Human',
    class: 'Fighter',
    subclass: 'Champion',
    level: 5,
    hitDice: {
      total: 5,
      current: 5,
      dieType: 'd10',
    },
    experiencePoints: 6500,
    armorClass: 18,
    speed: 30,
    proficiencyBonus: 3,
    abilities: mockMartialCharacter.abilities,
  },
  createdAt: '2026-09-24T00:00:00Z',
  updatedAt: '2026-09-24T00:00:00Z',
};

export const mockApplyDamageCommand: DomainCommand = {
  commandId: '88888888-8888-4888-8888-888888888888',
  protocolVersion: '1.0',
  campaignId: '99999999-9999-4999-8999-999999999999',
  issuerUserId: 'dm-1',
  timestamp: '2026-09-24T00:00:00Z',
  expectedActorVersions: {
    [mockCampaignActor.campaignActorId]: 1,
  },
  expectedRoomVersion: 42,
  payload: {
    type: 'ApplyDamage',
    targetActorId: mockCampaignActor.campaignActorId,
    amount: 12,
    damageType: 'slashing',
    sourceDescription: 'Goblin Scimitar strike',
  },
};

export const mockCommandReceipt: DomainCommandReceipt = {
  commandId: mockApplyDamageCommand.commandId,
  principalId: 'dm-1',
  campaignId: mockApplyDamageCommand.campaignId,
  payloadHash: 'sha256-abcdef1234567890',
  committedAt: '2026-09-24T00:00:01Z',
  result: {
    success: true,
    committedVersions: {
      [mockCampaignActor.campaignActorId]: 2,
    },
    roomStateVersion: 43,
  },
};
