import type { StackDependencyItem } from '@/types/systemInfo';

export const STACK_DEPENDENCIES: StackDependencyItem[] = [
  // Frontend
  {
    name: 'react',
    version: '^19.0.0',
    category: 'frontend',
    license: 'MIT',
    description: 'Component architecture with React 19 hooks and concurrent rendering',
    url: 'https://react.dev',
  },
  {
    name: 'vite',
    version: '^8.0.0',
    category: 'frontend',
    license: 'MIT',
    description: 'High-speed build tool and dev server with Rolldown bundling',
    url: 'https://vitejs.dev',
  },
  {
    name: 'zustand',
    version: '^5.0.0',
    category: 'frontend',
    license: 'MIT',
    description: 'Lightweight, scalable client state management with immer integration',
    url: 'https://github.com/pmndrs/zustand',
  },
  {
    name: 'lucide-react',
    version: '^1.45.0',
    category: 'frontend',
    license: 'ISC',
    description: 'Tree-shaken direct path iconography for UI controls and toolbars',
    url: 'https://lucide.dev',
  },
  {
    name: 'sonner',
    version: '^2.0.0',
    category: 'frontend',
    license: 'MIT',
    description: 'Accessible, non-intrusive toast notifications for game updates and actions',
    url: 'https://sonner.emilkowal.ski',
  },
  {
    name: '@nexus/character-creator',
    version: 'workspace:*',
    category: 'frontend',
    license: 'MIT',
    description: 'Shared 5e rules engine and character creation wizard package',
  },
  // Backend & Realtime
  {
    name: 'express',
    version: '^4.21.0',
    category: 'backend',
    license: 'MIT',
    description: 'Fast, unopinionated HTTP REST API framework for game metadata and sessions',
    url: 'https://expressjs.com',
  },
  {
    name: 'ws',
    version: '^8.18.0',
    category: 'backend',
    license: 'MIT',
    description: 'High-performance real-time WebSocket communication server',
    url: 'https://github.com/websockets/ws',
  },
  {
    name: 'pg',
    version: '^8.13.0',
    category: 'backend',
    license: 'MIT',
    description: 'Authoritative PostgreSQL database client with connection pooling',
    url: 'https://node-postgres.com',
  },
  {
    name: 'ioredis',
    version: '^5.4.0',
    category: 'backend',
    license: 'MIT',
    description: 'Robust Redis client powering pub/sub fanout and dynamic host leases',
    url: 'https://github.com/redis/ioredis',
  },
  {
    name: 'helmet',
    version: '^8.0.0',
    category: 'backend',
    license: 'MIT',
    description: 'Security middleware setting strict HTTP response headers and CSP',
    url: 'https://helmetjs.github.io',
  },
  {
    name: 'connect-pg-simple',
    version: '^10.0.0',
    category: 'backend',
    license: 'MIT',
    description: 'PostgreSQL-backed session storage surviving container and replica restarts',
    url: 'https://github.com/voxpelli/node-connect-pg-simple',
  },
  // Rendering & Engine
  {
    name: 'pixi.js',
    version: '^8.6.0',
    category: 'rendering',
    license: 'MIT',
    description: 'Hardware-accelerated 2D WebGL canvas engine for maps, tokens, and lighting',
    url: 'https://pixijs.com',
  },
  {
    name: '@3d-dice/dice-box-threejs',
    version: '^0.0.12',
    category: 'rendering',
    license: 'MIT',
    description: 'Physics-simulated 3D dice roller (three.js + cannon-es) with server-forced roll results',
    url: 'https://github.com/3d-dice/dice-box-threejs',
  },
  {
    name: 'pdfjs-dist',
    version: '^4.10.0',
    category: 'rendering',
    license: 'Apache-2.0',
    description: 'Off-thread PDF document renderer for adventure modules and rulebooks',
    url: 'https://mozilla.github.io/pdf.js',
  },
  {
    name: 'comlink',
    version: '^4.4.0',
    category: 'rendering',
    license: 'Apache-2.0',
    description: 'RPC abstraction offloading IndexedDB persistence and geometry to Web Workers',
    url: 'https://github.com/GoogleChromeLabs/comlink',
  },
  // Tooling & Quality
  {
    name: 'vitest',
    version: '^4.1.0',
    category: 'tooling',
    license: 'MIT',
    description: 'Next-generation native unit and integration test runner for Vite',
    url: 'https://vitest.dev',
  },
  {
    name: '@testing-library/react',
    version: '^16.1.0',
    category: 'tooling',
    license: 'MIT',
    description: 'User-centric UI component testing utilities ensuring accessible interactions',
    url: 'https://testing-library.com',
  },
  {
    name: 'playwright',
    version: '^1.49.0',
    category: 'tooling',
    license: 'Apache-2.0',
    description: 'End-to-end multi-browser test automation for replica and chaos smoke tests',
    url: 'https://playwright.dev',
  },
  {
    name: 'typescript',
    version: '^5.7.0',
    category: 'tooling',
    license: 'Apache-2.0',
    description: 'Strict static type checking across client, server, and shared contracts',
    url: 'https://www.typescriptlang.org',
  },
  {
    name: 'docker',
    version: 'Compose v2',
    category: 'tooling',
    license: 'Apache-2.0',
    description: 'Containerized deployment orchestration with health probes and NFS storage',
    url: 'https://www.docker.com',
  },
];
