import type { CampaignClue } from '../ashes-of-veyra/types';
import { MOURNINGFEN_CAMPAIGN_ID, mourningfenSessionId as s } from './campaign';

export const clues: CampaignClue[] = [
  {
    id: 'clue-repeating-landmarks',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Three Landmarks That Repeat',
    priority: 'low',
    status: 'resolved',
    meaning:
      'The fen loops travelers until they surrender a memory at the drowned shrine. The party paid; the price is now recorded on each of their sheets.',
    sourceHandoutIds: ['handout-ferrymans-lantern-tag'],
    relatedQuestIds: ['quest-follow-the-blue-lantern'],
    locationIds: ['location-drowned-shrine'],
    sessionIds: [s(1)],
  },
  {
    id: 'clue-extra-births',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Five Extra Births, No Deaths',
    priority: 'high',
    status: 'partially-understood',
    meaning:
      'The register still counts births for a family that no longer exists. The party knows the family was erased; they have not yet realised the count is seven, plus one.',
    sourceHandoutIds: ['handout-births-register-extract', 'lore-fen-fever'],
    relatedQuestIds: ['quest-village-that-forgot'],
    locationIds: ['location-mourningfen-village'],
    sessionIds: [s(1), s(2)],
  },
  {
    id: 'clue-blank-funeral-page',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Page That Cannot Be Marked',
    priority: 'high',
    status: 'unresolved',
    meaning:
      'A page in Ves’s funeral records refuses ink. It matches a torn signature leaf in the Burial Society archive. Bettin Sallow reacted to it.',
    sourceHandoutIds: ['handout-blank-funeral-page'],
    relatedQuestIds: ['quest-village-that-forgot'],
    locationIds: ['location-mourningfen-village'],
    sessionIds: [s(1), s(3)],
  },
  {
    id: 'clue-lamp-oil-tithe',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Oil Bought for Lamps Nobody Lights',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'The Wardens purchase far more lamp oil than the marsh lamps burn. The surplus goes to the well on the night of the tithe.',
    sourceHandoutIds: ['handout-wardens-tithe-tally'],
    relatedQuestIds: ['quest-village-that-forgot', 'quest-the-eighth-voice'],
    locationIds: ['location-wardens-lamp-house'],
    sessionIds: [s(1), s(3)],
  },
  {
    id: 'clue-ferry-toll-coin',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Toll Coin With a Worn Face',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'Odo’s last fare paid with a coin whose face has been rubbed smooth on purpose. The passenger did not want to be remembered.',
    sourceHandoutIds: ['handout-ferrymans-lantern-tag'],
    relatedQuestIds: ['quest-ferrymans-last-fare'],
    locationIds: ['location-crossing-ferry-landing', 'location-drowned-shrine'],
    sessionIds: [s(1), s(3)],
  },
  {
    id: 'clue-mirror-covers',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Rooms Move When Mirrors Are Covered',
    priority: 'medium',
    status: 'partially-understood',
    meaning:
      'Covering a mirror shifts the house to the layout of the person whose portrait belongs to it. The intended solution is to restore every portrait to its proper room.',
    sourceHandoutIds: ['handout-family-portrait-frames'],
    relatedQuestIds: ['quest-what-the-house-remembers'],
    locationIds: ['location-verrow-homestead', 'location-homestead-nursery'],
    sessionIds: [s(2)],
  },
  {
    id: 'clue-eighth-verse',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Verse That Names an Eighth',
    priority: 'high',
    status: 'unresolved',
    meaning:
      'The rhyme counts seven Verrows and then stops. The eighth voice is not a family member. It is the thing the bargain was made with.',
    sourceHandoutIds: ['handout-counting-rhyme', 'lore-forgetting-bargain'],
    relatedQuestIds: [
      'quest-what-the-house-remembers',
      'quest-the-eighth-voice',
    ],
    locationIds: ['location-homestead-nursery', 'location-verrow-well'],
    sessionIds: [s(2), s(4)],
  },
  {
    id: 'clue-sixth-chair',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Every Table Sets One Chair Too Many',
    priority: 'medium',
    status: 'partially-understood',
    meaning:
      'The village still sets places for the erased family, one chair per house per night. The party knows it is a habit; they have not yet worked out that the habit is the bargain’s last unbroken thread.',
    sourceHandoutIds: ['handout-long-table-seating-board'],
    relatedQuestIds: [
      'quest-a-place-at-the-long-table',
      'quest-village-that-forgot',
    ],
    locationIds: ['location-reedcutters-rest', 'location-mourningfen-village'],
    sessionIds: [s(1)],
  },
  {
    id: 'clue-odo-lantern-blue',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Ferryman’s Lantern Burns Blue Underwater',
    priority: 'low',
    status: 'resolved',
    meaning:
      'Odo’s lantern was lit by Ysolde Verrow, not the Wardens. The blue flame is the Reedbound’s signature, and it marked him as a guide, not a victim. Resolved when the party followed it to the shrine.',
    sourceHandoutIds: [
      'handout-ferrymans-lantern-tag',
      'handout-ferry-ledger-pages',
    ],
    relatedQuestIds: ['quest-follow-the-blue-lantern'],
    locationIds: ['location-crossing-ferry-landing', 'location-reedwalk'],
    sessionIds: [s(1)],
  },
  {
    id: 'clue-ferry-ledger-gap',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Crossing 41 Has Two Pages Cut Out',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'Someone cut two pages from the ferry ledger around the night Odo drowned. A strip of the cut page’s margin is found in the Lamp House copy of the ferry book, with the passenger line filled in and then burnt away.',
    sourceHandoutIds: ['handout-ferry-ledger-pages'],
    relatedQuestIds: ['quest-ferrymans-last-fare'],
    locationIds: ['location-crossing-ferry-landing', 'location-wardens-lamp-house'],
    sessionIds: [s(1), s(3)],
  },
  {
    id: 'clue-oil-cart-ruts',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Iron-Shod Ruts Toward the Homestead',
    priority: 'high',
    status: 'partially-understood',
    meaning:
      'The Warden handcart leaves the lamp house on the night of the tithe and rolls along a track that exists on no map, ending at the Verrow well. The party has seen the ruts, not yet followed them.',
    sourceHandoutIds: ['handout-wardens-tithe-tally', 'lore-lamp-lighting-rite'],
    relatedQuestIds: ['quest-the-tithe-night', 'quest-the-eighth-voice'],
    locationIds: ['location-lantern-oil-cellar', 'location-verrow-well'],
    sessionIds: [s(3)],
  },
  {
    id: 'clue-remedy-card',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'A Remedy Card for Lost Days',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'A recipe for reed tea that is said to return one lost day per cup. Unclear whether it restores the real memory or a flattering substitute. Marl Quillon will say only that the cost is paid by the next person to forget.',
    sourceHandoutIds: ['handout-folk-remedy-card', 'lore-marrowbone-circle'],
    relatedQuestIds: ['quest-the-remedy-for-forgetting'],
    locationIds: ['location-verrow-kitchen', 'location-eel-market'],
    sessionIds: [s(2), s(3)],
  },
  {
    id: 'clue-assize-seal',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'A Grey Seal on an Unsent Letter',
    priority: 'medium',
    status: 'unresolved',
    meaning:
      'Ysolde wrote to the Greywater Assize sixty years ago asking for an inquest. The seal is intact and the letter was never posted. The Assize therefore has no record of the Verrows, but it will recognise its own wax.',
    sourceHandoutIds: ['handout-drowned-letter', 'handout-assize-writ'],
    relatedQuestIds: ['quest-the-assize-rides-in'],
    locationIds: ['location-verrow-homestead', 'location-mourningfen-village'],
    sessionIds: [s(2), s(3)],
  },
  {
    id: 'clue-salt-pear-orchard',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Pears That Taste of Brine',
    priority: 'low',
    status: 'partially-understood',
    meaning:
      'The orchard behind the homestead is tended by something that buys small memories with salt fruit. The drovers’ work-song has a verse about it, and Dunmore’s crews have a rule: never eat from a tree you did not plant.',
    sourceHandoutIds: ['handout-drover-work-song'],
    relatedQuestIds: [
      'quest-what-the-house-remembers',
      'quest-the-remedy-for-forgetting',
    ],
    locationIds: ['location-salt-pear-orchard', 'location-eel-market'],
    sessionIds: [s(2)],
  },
];
