import type { CampaignHandout } from '../ashes-of-veyra/types';
import { MOURNINGFEN_CAMPAIGN_ID, mourningfenSessionId as s } from './campaign';

export const handouts: CampaignHandout[] = [
  {
    id: 'handout-ferrymans-lantern-tag',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: "Ferryman's Lantern Tag",
    kind: 'handout',
    summary:
      'A brass tag on Odo Tarn’s lantern, stamped with a crossing number and a scratched-out passenger line.',
    content: [
      'Crossing 41. Landing: Verrow. Passenger: [scratched out]. Fare: one coin, paid.',
      'On the reverse, in a different hand: "Do not carry them back."',
    ],
    visibility: 'shared',
    sessionIds: [s(1)],
    clueIds: ['clue-repeating-landmarks', 'clue-ferry-toll-coin'],
    questIds: ['quest-follow-the-blue-lantern', 'quest-ferrymans-last-fare'],
    locationIds: ['location-crossing-ferry-landing'],
    factionIds: ['faction-reedbound', 'faction-lantern-wardens'],
  },
  {
    id: 'handout-births-register-extract',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Birth Register Extract',
    kind: 'handout',
    summary:
      'A page from the village register with five births recorded under a family name that has been struck from every other book.',
    content: [
      'Five entries share a surname that has been scraped away and rewritten as "—". Each births entry has a matching baptism. None has a death.',
      'A margin note in a tidy hand: "Count again in spring." The count has been done every year since.',
    ],
    visibility: 'shared',
    sessionIds: [s(1)],
    clueIds: ['clue-extra-births'],
    questIds: ['quest-village-that-forgot'],
    locationIds: ['location-mourningfen-village'],
    factionIds: ['faction-burial-society'],
  },
  {
    id: 'handout-blank-funeral-page',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Blank Page',
    kind: 'handout',
    summary:
      'A page in Ves Nymm’s funeral records that no ink will take. Held to a lantern, faint ruled lines show a list of signatures.',
    content: [
      'Every ink slides off the page, and a quill leaves only a damp mark that dries to nothing.',
      'Held to blue light, seven ruled lines appear, and a signature leaf has been torn from the bottom edge.',
    ],
    visibility: 'shared',
    sessionIds: [s(1), s(3)],
    clueIds: ['clue-blank-funeral-page'],
    questIds: ['quest-village-that-forgot'],
    locationIds: ['location-mourningfen-village'],
    factionIds: ['faction-burial-society'],
  },
  {
    id: 'handout-wardens-tithe-tally',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: "Tamsin's Folded Tally",
    kind: 'handout',
    summary:
      'A hurried tally of lamp oil bought against oil burned, with a column of "well nights" beside it.',
    content: [
      'Oil bought this year: 96 flasks. Oil burned in the marsh lamps: 31. Remainder: "the tithe".',
      'The last line is underlined twice: "Reeve says do not ask where it goes."',
    ],
    visibility: 'shared',
    sessionIds: [s(1), s(3)],
    clueIds: ['clue-lamp-oil-tithe'],
    questIds: ['quest-village-that-forgot', 'quest-the-eighth-voice'],
    locationIds: ['location-wardens-lamp-house'],
    factionIds: ['faction-lantern-wardens'],
  },
  {
    id: 'handout-counting-rhyme',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: "Pim's Counting Rhyme",
    kind: 'handout',
    summary:
      'The counting rhyme the youngest Verrow child keeps starting, with the last verse missing.',
    content: [
      'One for the mother who lit the lamp, two for the father who kept the door, three for the sister who sang the reeds, four for the brother who taught the oars.',
      'Five for the grandam, six for the babe, seven for the boy who counts them all. And eight is the voice at the bottom of the well, and eight is the name that nobody calls.',
    ],
    visibility: 'shared',
    sessionIds: [s(2), s(4)],
    clueIds: ['clue-eighth-verse'],
    questIds: ['quest-what-the-house-remembers', 'quest-the-eighth-voice'],
    locationIds: ['location-homestead-nursery', 'location-verrow-well'],
    factionIds: ['faction-reedbound', 'faction-mere-below'],
  },
  {
    id: 'handout-family-portrait-frames',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Seven Empty Portrait Frames',
    kind: 'handout',
    summary:
      'Seven empty frames in the homestead hall; each has a name carved on its back. Not yet illustrated.',
    content: [
      'Seven frames, one per room. Each holds a blank canvas that darkens when someone speaks the name carved on the back.',
      'The eighth frame hangs above the well-room door, and its back has no carving.',
    ],
    visibility: 'shared',
    sessionIds: [s(2)],
    clueIds: ['clue-mirror-covers'],
    questIds: ['quest-what-the-house-remembers'],
    locationIds: ['location-verrow-homestead', 'location-homestead-nursery'],
    factionIds: ['faction-reedbound'],
  },
  {
    id: 'lore-forgetting-bargain',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Forgetting Bargain',
    kind: 'lore',
    summary:
      'What the village promised the well sixty years ago to end the fen fever, and what the well actually took.',
    content: [
      'The founders of the Tidewake Burial Society and the first Lantern Wardens agreed to give the well the Verrow family’s memory, which the well accepted in place of a name of its own.',
      'The bargain must be renewed yearly with a tithe of remembered things. If it lapses, the well takes memories from the living until it is satisfied.',
    ],
    visibility: 'dm-only',
    sessionIds: [s(2), s(4)],
    clueIds: ['clue-eighth-verse'],
    questIds: ['quest-what-the-house-remembers', 'quest-the-eighth-voice'],
    locationIds: ['location-verrow-well', 'location-mourningfen-village'],
    factionIds: [
      'faction-lantern-wardens',
      'faction-burial-society',
      'faction-mere-below',
    ],
  },
  {
    id: 'lore-reedbound-procession',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Reedbound Procession',
    kind: 'lore',
    summary:
      'What the villagers say about the lantern-bearers, and what the Reedbound remember about themselves.',
    content: [
      'Villagers call them the Mourners and avoid the reeds at dusk. They walk from the drowned shrine to the homestead and back, once each night.',
      'They are not hostile unless their names are used against them, and they will follow any voice that speaks all seven correctly.',
    ],
    visibility: 'shared',
    sessionIds: [s(1)],
    clueIds: ['clue-repeating-landmarks'],
    questIds: ['quest-follow-the-blue-lantern'],
    locationIds: ['location-drowned-shrine', 'location-verrow-homestead'],
    factionIds: ['faction-reedbound'],
  },
  {
    id: 'lore-fen-fever',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Fen Fever',
    kind: 'lore',
    summary:
      'The wasting illness that drove the founders to the bargain, and the real reason it stopped.',
    content: [
      'Sixty winters ago a fever emptied a third of the marsh in a season. The old records call it a plague of the water.',
      'The fever ended the night the Verrow homestead was abandoned. Nobody kept a record of why.',
    ],
    visibility: 'dm-only',
    sessionIds: [s(3)],
    clueIds: ['clue-extra-births'],
    questIds: ['quest-village-that-forgot'],
    locationIds: ['location-mourningfen-village'],
    factionIds: ['faction-burial-society', 'faction-lantern-wardens'],
  },
  {
    id: 'handout-ferry-ledger-pages',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Crossing Ferry Ledger',
    kind: 'handout',
    summary:
      'Three surviving pages of the ferry fare book, with the night Odo Tarn drowned cut out of the binding.',
    content: [
      'Crossing 39. Dusk. Landing: Mourningfen. Passengers: two drovers and a crate of eels. Fare: four coppers, paid. Crossing 40. Dusk. Landing: Mourningfen. Passengers: Reeve H. Crane, alone. Fare: waived.',
      'Crossing 41 has been cut out with a thin blade. The stub at the binding bears the smudged imprint of a number, and a margin note in Odo’s hand: "She asked me not to look at her face."',
      'Crossing 42. Dawn. Landing: Verrow. No passenger. No fare. Beneath it, in a different, tidier hand: "Do not carry them back."',
    ],
    visibility: 'shared',
    sessionIds: [s(1), s(3)],
    clueIds: ['clue-ferry-ledger-gap', 'clue-odo-lantern-blue'],
    questIds: ['quest-ferrymans-last-fare', 'quest-follow-the-blue-lantern'],
    locationIds: ['location-crossing-ferry-landing'],
    factionIds: ['faction-lantern-wardens'],
  },
  {
    id: 'handout-drowned-letter',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'A Letter Sealed in a Bottle',
    kind: 'handout',
    summary:
      'A waxed, unposted letter found beneath the nursery floor, written by Ysolde Verrow to the Greywater Assize.',
    content: [
      'To the Clerk of the Greywater Assize, Greetings. We are the Verrow household of the fen, seven souls and one more who is not of us. A sickness has taken a third of the marsh. The village has made a bargain, and we are the price.',
      'I do not ask you to believe in what I cannot prove. I ask you to count: count the births, the baptisms, the empty chairs. Count the signatures on the Burial Society’s oath, if you can find them. Count us, if you cannot count them.',
      'We will not be at the homestead when this reaches you. The lamp is lit and the well is open. If you come, bring a name for the eighth, because we have none to give. Yours in the damp, Ysolde Verrow.',
      'The wax seal bears a grey wheel, its rim chipped at one spoke. Beneath it, in a smaller hand: "Not sent. The reeve took the post."',
    ],
    visibility: 'shared',
    sessionIds: [s(2)],
    clueIds: ['clue-assize-seal', 'clue-eighth-verse'],
    questIds: ['quest-the-assize-rides-in', 'quest-what-the-house-remembers'],
    locationIds: ['location-verrow-homestead', 'location-homestead-nursery'],
    factionIds: ['faction-reedbound', 'faction-greywater-assize'],
  },
  {
    id: 'handout-burial-roll-extract',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Tidewake Burial Roll: Seven Unnamed',
    kind: 'handout',
    summary:
      'A page from the Society’s roll listing seven interments with the name column left empty and a single signature at the foot.',
    content: [
      'Interred, sixty winters ago, in the Tidewake ground: seven. Names withheld by agreement of the Society and the Wardens. Cause: the fever. Place: the upright row, east edge. Officiating: B. Sallow, senior.',
      'Beneath the list, a column of small tick marks. There are sixty-one rows of them, one for every year since, and each row has seven ticks. The final row has eight.',
      'At the foot of the page is a single signature: "Odalys Sallow, Keeper". The ink has the same slick, ink-refusing look as the Blank Page and cannot be photographed by lamp or lantern.',
    ],
    visibility: 'shared',
    sessionIds: [s(3)],
    clueIds: ['clue-blank-funeral-page', 'clue-extra-births'],
    questIds: ['quest-village-that-forgot'],
    locationIds: [
      'location-tidewake-burying-ground',
      'location-tidewake-archive',
    ],
    factionIds: ['faction-burial-society'],
  },
  {
    id: 'handout-folk-remedy-card',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Remedy Card: Pale Reed and Bogbean',
    kind: 'handout',
    summary:
      'A card in a tidy hand listing a tea for lost days, found on the kitchen jar at the Verrow homestead.',
    content: [
      'For the dropping of days, and the thinning of names. Steep three heads of pale reed with a thumb of bogbean in water that has been left to see a full moon. Strain through wool. Drink warm, with the door open.',
      'Do not give to a child. Do not give to the dying. Do not give twice in a season. The first cup returns one clear day. The second returns it with something added.',
      'Written on the back, in a rougher hand: "Cost: paid by the next to forget. We are always the next." Underneath, a small drawing of an upright slate with no name.',
    ],
    visibility: 'shared',
    sessionIds: [s(2), s(3)],
    clueIds: ['clue-remedy-card'],
    questIds: ['quest-the-remedy-for-forgetting'],
    locationIds: ['location-verrow-kitchen', 'location-eel-market'],
    factionIds: ['faction-marrowbone-circle', 'faction-reedbound'],
  },
  {
    id: 'handout-assize-writ',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Writ of Inquiry: Tidewake and Mourningfen',
    kind: 'handout',
    summary:
      'A sealed letter from the Greywater Assize announcing an audit of the village burial rolls and oil purchases.',
    content: [
      'By the authority of the Greywater Assize, the Circuit Clerk S. Vale will attend the villages of Mourningfen and Tidewake within the month to examine the registers of births, deaths, and burials, and the purchases of lamp oil made by the Lantern Wardens in the preceding sixty years.',
      'All persons holding such registers or accounts are required to present them without delay. Failure to do so is an offence of the first degree under the Fen Charter.',
      'The seal is a grey wheel with a chipped spoke. It matches the wax on the unposted letter in the Verrow nursery.',
    ],
    visibility: 'shared',
    sessionIds: [s(3), s(4)],
    clueIds: ['clue-assize-seal'],
    questIds: ['quest-the-assize-rides-in'],
    locationIds: ['location-mourningfen-village', 'location-tidewake-archive'],
    factionIds: ['faction-greywater-assize'],
  },
  {
    id: 'handout-drover-work-song',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Eel-Drovers’ Hauling Song',
    kind: 'handout',
    summary:
      'A rowing chant the drovers sing in rounds, with a verse about an orchard that no one will explain.',
    content: [
      'Pull for the shallows, pull for the weir, pull for the one who is never here. Seven for the boat and one for the oar, eight for the pear tree by the shore.',
      'Never eat salt from a hand that is kind, never sit down where the chairs are lined. If a woman in green offers you sweet, give her your name and keep your feet.',
      'The last verse is only hummed. Dunmore says it used to have words, but his grandmother stopped teaching them the winter the lamps went blue.',
    ],
    visibility: 'shared',
    sessionIds: [s(1), s(2)],
    clueIds: ['clue-salt-pear-orchard'],
    questIds: ['quest-the-remedy-for-forgetting', 'quest-what-the-house-remembers'],
    locationIds: ['location-eel-market', 'location-salt-pear-orchard'],
    factionIds: ['faction-fenfolk-drovers'],
  },
  {
    id: 'handout-long-table-seating-board',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Chalk Seating Board, Reedcutters’ Rest',
    kind: 'handout',
    summary:
      'Goody Ashby’s nightly chalk board for the long table, showing six regulars and a seventh, unlabeled seat.',
    content: [
      'Goody Ashby chalks the board each evening and rubs it out each morning. Tonight: Dunmore, Pell, the two Greaves girls, old Hob, Jun, and a seventh place with no name.',
      'A smudged line, more recent than the rest, reads: "Tell the new folk the chair is for no one." It has been rubbed out and rewritten, rubbed out and rewritten, so many times that the board has a grey groove where the chalk sits.',
    ],
    visibility: 'shared',
    sessionIds: [s(1)],
    clueIds: ['clue-sixth-chair'],
    questIds: ['quest-a-place-at-the-long-table'],
    locationIds: ['location-reedcutters-rest'],
    factionIds: ['faction-fenfolk-drovers'],
  },
  {
    id: 'lore-lamp-lighting-rite',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Wardens’ Lamp-Lighting Rite',
    kind: 'lore',
    summary:
      'The words and measures the Wardens use on the night of the tithe, and what each lamp actually does.',
    content: [
      'Each blue lamp on the boardwalk is one of seven, lit in order from the Lamp House to the shrine. The first lamp holds a day, the second a name, the third a face, the fourth a voice, the fifth a hand, the sixth a hearth, the seventh a death. Together they say: "Remember nothing of us, and be sated."',
      'On the night of the tithe the Wardens carry flasks of lamp oil in a handcart to the Verrow well and pour them over the iron bands. For each flask, one villager is made to forget a specific memory of the Verrows. The village’s collective forgetting is thus renewed, a little at a time, every year.',
      'The rite requires six Wardens to speak, one to carry, and one to be forgotten. That seventh role is always filled by someone who volunteered, and who has since forgotten that they did.',
    ],
    visibility: 'dm-only',
    sessionIds: [s(3), s(4)],
    clueIds: ['clue-oil-cart-ruts', 'clue-lamp-oil-tithe'],
    questIds: ['quest-the-tithe-night', 'quest-the-eighth-voice'],
    locationIds: [
      'location-lantern-oil-cellar',
      'location-wardens-lamp-house',
      'location-verrow-well',
    ],
    factionIds: ['faction-lantern-wardens', 'faction-mere-below'],
  },
  {
    id: 'lore-marrowbone-circle',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Marrowbone Circle',
    kind: 'lore',
    summary:
      'What the herbalist sisterhood of the fen knows, remembers, and refuses to say aloud.',
    content: [
      'The Circle began as seven midwives who noticed that babies born in the fen arrived with the right number of fingers and the wrong number of names. They started keeping tallies on the backs of remedy cards, and have never stopped.',
      'Their records are the only complete account of what the forgetting has taken from the living: a lost wedding, a missing winter, a favourite song. They file these under the herb used to treat them, so a list of remedies is also a list of losses.',
      'Marl Quillon believes the Circle’s tallies could, if read aloud in order, name the Verrows again. She has not tried, because she suspects it would also name something else.',
    ],
    visibility: 'dm-only',
    sessionIds: [s(3)],
    clueIds: ['clue-remedy-card'],
    questIds: ['quest-the-remedy-for-forgetting'],
    locationIds: ['location-eel-market', 'location-verrow-kitchen'],
    factionIds: ['faction-marrowbone-circle'],
  },
];
