import type { FolderRecord, LibraryObject } from '../ashes-of-veyra/types';
import {
  MOURNINGFEN_ACT_1_ID,
  MOURNINGFEN_ACT_2_ID,
  MOURNINGFEN_ACT_3_ID,
} from './campaign';

export const libraryObjects: LibraryObject[] = [
  {
    id: 'scene-mourningfen-lantern-path',
    title: 'The Lantern Path',
    kind: 'scene',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '6 weeks ago',
  },
  {
    id: 'scene-verrow-homestead-loop',
    title: 'Verrow Homestead: Room Loop',
    kind: 'scene',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-hesper-crane',
    title: 'Reeve Hesper Crane',
    kind: 'npc',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '4 weeks ago',
  },
  {
    id: 'npc-pim-verrow',
    title: 'Pim Verrow',
    kind: 'npc',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-shifting-rooms',
    title: 'The Shifting Rooms',
    kind: 'encounter',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-reedbound-procession',
    title: 'The Reedbound Procession',
    kind: 'encounter',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '6 weeks ago',
  },
  {
    id: 'handout-counting-rhyme',
    title: "Pim's Counting Rhyme",
    kind: 'handout',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-wardens-tithe-tally',
    title: "Tamsin's Folded Tally",
    kind: 'handout',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '5 weeks ago',
  },
  {
    id: 'lore-forgetting-bargain',
    title: 'The Forgetting Bargain',
    kind: 'lore',
    folderActId: MOURNINGFEN_ACT_2_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'faction-lantern-wardens',
    title: 'The Lantern Wardens',
    kind: 'faction',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '4 weeks ago',
  },
  {
    id: 'quest-what-the-house-remembers',
    title: 'What the House Remembers',
    kind: 'quest',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'quest-village-that-forgot',
    title: 'The Village That Forgot',
    kind: 'quest',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '5 weeks ago',
  },
  {
    id: 'npc-marl-quillon',
    title: 'Marl Quillon',
    kind: 'npc',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'npc-sabine-vale',
    title: 'Circuit Clerk Sabine Vale',
    kind: 'npc',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'npc-ottoline-verrow',
    title: 'Granny Ottoline Verrow',
    kind: 'npc',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'npc-fenwick-oar',
    title: 'Fenwick Oar',
    kind: 'npc',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'encounter-sixth-chair-supper',
    title: 'Supper at the Sixth Chair',
    kind: 'encounter',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '6 weeks ago',
  },
  {
    id: 'encounter-grandam-kitchen',
    title: 'Tea With the Grandam',
    kind: 'encounter',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'encounter-oil-cellar-sneak',
    title: 'The Oil Cellar After Dark',
    kind: 'encounter',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'encounter-unnamed-dead',
    title: 'The Unnamed Row',
    kind: 'encounter',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'handout-ferry-ledger-pages',
    title: 'The Crossing Ferry Ledger',
    kind: 'handout',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '6 weeks ago',
  },
  {
    id: 'handout-drowned-letter',
    title: 'A Letter Sealed in a Bottle',
    kind: 'handout',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-folk-remedy-card',
    title: 'Remedy Card: Pale Reed and Bogbean',
    kind: 'handout',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'handout-assize-writ',
    title: 'Writ of Inquiry: Tidewake and Mourningfen',
    kind: 'handout',
    folderActId: MOURNINGFEN_ACT_2_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'lore-lamp-lighting-rite',
    title: 'The Wardens’ Lamp-Lighting Rite',
    kind: 'lore',
    folderActId: MOURNINGFEN_ACT_2_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'lore-marrowbone-circle',
    title: 'The Marrowbone Circle',
    kind: 'lore',
    folderActId: MOURNINGFEN_ACT_2_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'faction-marrowbone-circle',
    title: 'The Marrowbone Circle',
    kind: 'faction',
    folderActId: MOURNINGFEN_ACT_2_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'faction-greywater-assize',
    title: 'The Greywater Assize',
    kind: 'faction',
    folderActId: MOURNINGFEN_ACT_2_ID,
    updatedLabel: '3 weeks ago',
  },
  {
    id: 'quest-pims-seven-boats',
    title: 'Pim’s Seven Boats',
    kind: 'quest',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: 'Yesterday',
  },
  {
    id: 'quest-the-tithe-night',
    title: 'The Night of the Tithe',
    kind: 'quest',
    folderActId: MOURNINGFEN_ACT_1_ID,
    updatedLabel: '3 weeks ago',
  },
];

export const folders: FolderRecord[] = [
  {
    id: 'folder-mf-act-one',
    title: 'Act I - What the Fen Kept',
    actId: MOURNINGFEN_ACT_1_ID,
    objectIds: [
      'scene-mourningfen-lantern-path',
      'scene-verrow-homestead-loop',
      'npc-hesper-crane',
      'npc-pim-verrow',
      'encounter-shifting-rooms',
      'encounter-reedbound-procession',
      'handout-counting-rhyme',
      'handout-wardens-tithe-tally',
      'faction-lantern-wardens',
      'quest-what-the-house-remembers',
      'quest-village-that-forgot',
      'npc-marl-quillon',
      'npc-sabine-vale',
      'npc-ottoline-verrow',
      'npc-fenwick-oar',
      'encounter-sixth-chair-supper',
      'encounter-grandam-kitchen',
      'encounter-oil-cellar-sneak',
      'encounter-unnamed-dead',
      'handout-ferry-ledger-pages',
      'handout-drowned-letter',
      'handout-folk-remedy-card',
      'quest-pims-seven-boats',
      'quest-the-tithe-night',
    ],
    children: [
      { kind: 'scene', count: 3 },
      { kind: 'npc', count: 9 },
      { kind: 'encounter', count: 9 },
      { kind: 'handout', count: 7 },
    ],
  },
  {
    id: 'folder-mf-act-two',
    title: 'Act II - The Eighth Voice',
    actId: MOURNINGFEN_ACT_2_ID,
    objectIds: [
      'lore-forgetting-bargain',
      'handout-assize-writ',
      'lore-lamp-lighting-rite',
      'lore-marrowbone-circle',
      'faction-marrowbone-circle',
      'faction-greywater-assize',
    ],
    children: [
      { kind: 'scene', count: 2 },
      { kind: 'npc', count: 5 },
      { kind: 'encounter', count: 4 },
      { kind: 'handout', count: 5 },
    ],
  },
  {
    id: 'folder-mf-act-three',
    title: 'Act III - The Naming',
    actId: MOURNINGFEN_ACT_3_ID,
    objectIds: [],
    children: [
      { kind: 'scene', count: 1 },
      { kind: 'npc', count: 2 },
      { kind: 'encounter', count: 2 },
      { kind: 'handout', count: 1 },
    ],
  },
];
