import type { CampaignLocation } from '../ashes-of-veyra/types';
import { MOURNINGFEN_CAMPAIGN_ID } from './campaign';

export const MAP_MARSH_ID = 'map-mourningfen-marsh';
export const MAP_HOMESTEAD_ID = 'map-verrow-homestead';

export const locations: CampaignLocation[] = [
  {
    id: 'location-mourningfen-village',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Mourningfen Village',
    type: 'district',
    shortDescription:
      'A stilted village of reed roofs and blue lamps, where every house sets one chair too many.',
    description: [
      'Boardwalks connect a few dozen homes above the waterline. Lamps burn blue after dusk and no one will say who lit them.',
      'The Burial Society hall sits at the centre, its registers kept in a room that smells of lamp oil and river mud.',
    ],
    tags: ['Village', 'Boardwalks', 'Registers'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-village',
    npcIds: ['npc-hesper-crane', 'npc-bettin-sallow', 'npc-sabine-vale'],
    factionIds: ['faction-lantern-wardens', 'faction-burial-society'],
    encounterIds: ['encounter-warden-lamp-patrol', 'encounter-assize-bailiffs'],
    questIds: [
      'quest-village-that-forgot',
      'quest-a-place-at-the-long-table',
      'quest-the-assize-rides-in',
    ],
    handoutIds: [
      'handout-assize-writ',
      'handout-births-register-extract',
      'handout-blank-funeral-page',
      'lore-fen-fever',
    ],
    notes:
      'The regional hub. Use district records for specific scenes; the archive door is the blocked thread for Act I. Child locations (burial hall, archive, burying ground, lamp house, Reedcutters’ Rest) carry the detailed scenes.',
  },
  {
    id: 'location-crossing-ferry-landing',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Crossing Ferry Landing',
    type: 'pier',
    shortDescription:
      'The old ferry stage where Odo Tarn’s lantern was last seen before he drowned.',
    description: [
      'A tilted stage and a rope ferry with a brass bell that rings on its own after dark.',
      'The landing board still lists fares for a stop called Verrow that appears on no map.',
    ],
    tags: ['Ferry', 'Landing', 'Ghost'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-ferry-landing',
    npcIds: ['npc-odo-tarn', 'npc-maudlin-tarn'],
    factionIds: ['faction-lantern-wardens', 'faction-reedbound'],
    encounterIds: ['encounter-lantern-loop'],
    questIds: ['quest-follow-the-blue-lantern', 'quest-ferrymans-last-fare'],
    handoutIds: ['handout-ferrymans-lantern-tag', 'handout-ferry-ledger-pages'],
    sceneTemplateId: 'scene-mourningfen-lantern-path',
    notes: 'The party lost the last passenger’s trail here; the quest is on hold.',
  },
  {
    id: 'location-drowned-shrine',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Drowned Shrine',
    type: 'landmark',
    shortDescription:
      'A half-sunk shrine where the fen collects a memory from anyone who wants to pass.',
    description: [
      'Seven stones ring a shallow pool, each carved with a name that has been worn to a groove.',
      'A coin dish sits on the altar. Whatever is placed there is taken; so, quietly, is whatever the giver was thinking about.',
    ],
    tags: ['Shrine', 'Memory toll', 'Reedbound'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-shrine',
    npcIds: ['npc-ysolde-verrow', 'npc-odo-tarn'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-reedbound-procession', 'encounter-lantern-loop'],
    questIds: ['quest-follow-the-blue-lantern', 'quest-ferrymans-last-fare'],
    handoutIds: ['lore-reedbound-procession'],
    notes: 'Every surrendered memory should be written down and can return altered.',
  },
  {
    id: 'location-reedcutters-rest',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: "Reedcutters' Rest",
    type: 'tavern',
    shortDescription:
      'A low taproom that sets a place for a family no one can name.',
    description: [
      'The hearth burns peat and the ale tastes faintly of smoke and river.',
      'Goody Ashby sets a sixth chair at the long table every night and has never been able to say why.',
    ],
    tags: ['Tavern', 'Rumors', 'Empty chair'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-reedcutters',
    parentLocationId: 'location-mourningfen-village',
    npcIds: ['npc-goody-ashby', 'npc-dunmore-fenn'],
    factionIds: ['faction-fenfolk-drovers'],
    encounterIds: ['encounter-drover-standoff', 'encounter-sixth-chair-supper'],
    questIds: ['quest-village-that-forgot', 'quest-a-place-at-the-long-table'],
    handoutIds: ['handout-long-table-seating-board'],
    notes: 'Best place to hear that half the drovers have already lost a year.',
  },
  {
    id: 'location-wardens-lamp-house',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Lamp House',
    type: 'government',
    shortDescription:
      'The Wardens’ stone lamp store, oil cellar, and the reeve’s counting room.',
    description: [
      'Rows of blue lamps hang from the rafters and the cellar holds more oil than the marsh could burn.',
      'The reeve’s table is neat and bare, with a locked chest that Tamsin Reed has clearly been avoiding.',
    ],
    tags: ['Government', 'Wardens', 'Tithe'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-lamp-house',
    parentLocationId: 'location-mourningfen-village',
    npcIds: ['npc-hesper-crane', 'npc-tamsin-reed', 'npc-halloran-wick'],
    factionIds: ['faction-lantern-wardens'],
    encounterIds: ['encounter-warden-lamp-patrol'],
    questIds: [
      'quest-village-that-forgot',
      'quest-ferrymans-last-fare',
      'quest-the-eighth-voice',
    ],
    handoutIds: ['handout-wardens-tithe-tally', 'lore-lamp-lighting-rite'],
    notes: 'The reeve has not yet been confronted; the tension is open.',
  },
  {
    id: 'location-eel-market',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Eel Market',
    type: 'market',
    shortDescription:
      'A floating market where drovers trade eels, rope, and gossip.',
    description: [
      'Barges are lashed together and rocked by any passing wake.',
      'The only stall the Wardens do not visit is Dunmore Fenn’s, and everyone knows why.',
    ],
    tags: ['Market', 'Drovers', 'Crowds'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-eel-market',
    npcIds: ['npc-dunmore-fenn', 'npc-marl-quillon', 'npc-jun-fenn'],
    factionIds: ['faction-fenfolk-drovers', 'faction-marrowbone-circle'],
    encounterIds: ['encounter-drover-standoff'],
    questIds: ['quest-village-that-forgot', 'quest-the-remedy-for-forgetting'],
    handoutIds: ['handout-drover-work-song', 'lore-marrowbone-circle'],
    notes: 'Public proof here will turn the market one way or the other.',
  },
  {
    id: 'location-verrow-homestead',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Verrow Homestead',
    type: 'landmark',
    shortDescription:
      'A farmhouse absent from every map, whose rooms rearrange around the memories the party gave up.',
    description: [
      'Mirrors hang in every room and none of them show the party. Seven empty frames line the hall.',
      'The doors open onto rooms that were there yesterday and are not there now.',
    ],
    tags: ['Haunted house', 'Puzzle', 'Session 2'],
    mapId: MAP_HOMESTEAD_ID,
    pinId: 'pin-mf-homestead',
    npcIds: ['npc-pim-verrow', 'npc-ysolde-verrow', 'npc-ottoline-verrow'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-shifting-rooms'],
    questIds: [
      'quest-follow-the-blue-lantern',
      'quest-what-the-house-remembers',
    ],
    handoutIds: ['handout-family-portrait-frames', 'handout-drowned-letter'],
    sceneTemplateId: 'scene-verrow-homestead-loop',
    notes: 'The room loop diagram is complete; the portraits are not.',
  },
  {
    id: 'location-homestead-nursery',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Homestead Nursery',
    type: 'landmark',
    shortDescription:
      'The smallest room, where Pim’s counting rhyme is painted on the wall and never finishes.',
    description: [
      'A child’s bed, a row of wooden boats, and a wall painted with seven verses and a blank space.',
      'It is the only room that never moves.',
    ],
    tags: ['Nursery', 'Counting rhyme', 'Safe room'],
    mapId: MAP_HOMESTEAD_ID,
    pinId: 'pin-mf-nursery',
    parentLocationId: 'location-verrow-homestead',
    npcIds: ['npc-pim-verrow'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-shifting-rooms'],
    questIds: ['quest-what-the-house-remembers'],
    handoutIds: [
      'handout-counting-rhyme',
      'handout-family-portrait-frames',
      'handout-drowned-letter',
    ],
    notes: 'Treat as the party’s fixed point and rest spot during the loop.',
  },
  {
    id: 'location-verrow-well',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Verrow Well',
    type: 'landmark',
    shortDescription:
      'A dry well at the back of the homestead that the village sealed and never forgot.',
    description: [
      'Iron bands run around the stones and the cover is warm to the touch.',
      'At night the well speaks the last word of the counting rhyme.',
    ],
    tags: ['Well', 'Entity', 'Choice'],
    mapId: MAP_HOMESTEAD_ID,
    pinId: 'pin-mf-well',
    parentLocationId: 'location-verrow-homestead',
    npcIds: ['npc-the-eighth-voice'],
    factionIds: ['faction-mere-below'],
    encounterIds: ['encounter-well-whisperer'],
    questIds: ['quest-what-the-house-remembers', 'quest-the-eighth-voice'],
    handoutIds: ['lore-forgetting-bargain', 'handout-counting-rhyme'],
    notes: 'The unresolved choice: restore the family or seal the well.',
  },
  {
    id: 'location-tidewake-burial-hall',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Tidewake Burial Hall',
    type: 'building',
    shortDescription:
      'A tarred-timber hall at the village centre where the Society keeps its rolls, its bier, and its tea.',
    description: [
      'The hall squats on the only stretch of boardwalk built on pilings of black oak rather than reed-bundle. The ground floor is a meeting room with a long table, a hundred mismatched mourning cups, and a bier on wheels that has not been oiled in a year and still never squeaks.',
      'Everything smells of lamp oil and wet wool. Members of the Society serve weak tea at every meeting, and a visitor who watches long enough notices that nobody ever pours the seventh cup, yet someone always empties it.',
      'A narrow stair behind the bier leads to the archive. The door at the top has a lock of dwarven make, and the key hangs, in full view, on a hook beside Bettin Sallow’s coat.',
    ],
    tags: ['Building', 'Society', 'Tea'],
    parentLocationId: 'location-mourningfen-village',
    npcIds: ['npc-bettin-sallow', 'npc-fenwick-oar'],
    factionIds: ['faction-burial-society'],
    encounterIds: [],
    questIds: ['quest-village-that-forgot'],
    handoutIds: ['handout-burial-roll-extract', 'handout-blank-funeral-page'],
    notes:
      'Social ground. Nothing here should be a fight: the Society wins by hospitality and silence. The unpoured seventh cup is a free clue for any character who thinks to ask who drinks it.',
  },
  {
    id: 'location-tidewake-archive',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Tidewake Archive',
    type: 'room',
    shortDescription:
      'A locked upstairs room of funeral rolls, signature leaves, and one drawer that is always cold.',
    description: [
      'Shelves of oilcloth-wrapped rolls rise to the rafters, indexed by a system of coloured thread that only three living people understand. Damp has not touched a single page; the room is somehow drier than the air outside.',
      'The bottom drawer of the signatory cabinet is lined with lead and has no handle. If the drawer is opened, seven ruled lines appear on the underside of its lid in blue light, matching the Blank Page, and a torn corner shows where a signature leaf once sat.',
      'The room remembers visitors. Anyone who enters gains a single clear memory of the hall below that they did not have before, and must still decide whether that is a gift or a leash.',
    ],
    tags: ['Archive', 'Locked', 'Act I blocker'],
    parentLocationId: 'location-tidewake-burial-hall',
    npcIds: ['npc-bettin-sallow'],
    factionIds: ['faction-burial-society'],
    encounterIds: [],
    questIds: ['quest-village-that-forgot'],
    handoutIds: ['handout-blank-funeral-page', 'handout-burial-roll-extract'],
    notes:
      'The blocked objective. Ways in: Bettin’s consent (needs her guilt), the key (needs a distraction), or the Assize writ (needs Sabine Vale). Do not let a lockpick check alone solve it.',
  },
  {
    id: 'location-lantern-oil-cellar',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Lamp House Oil Cellar',
    type: 'room',
    shortDescription:
      'A stone cellar holding sixty-five flasks of oil too many, stacked in sevens.',
    description: [
      'Rows of sealed clay flasks sit in racks cut for the purpose, each rack seven wide. The floor is stained a deep blue where oil has been spilled and never fully cleaned.',
      'A trapdoor in the back wall opens onto a flat-bottomed barge channel, and a handcart with iron-shod wheels stands beside it, tarred and ready. The wheels are caked with a grey clay found nowhere near the village.',
      'Anyone standing still in the cellar for a minute hears a faint count in a child’s voice, always stopping at seven.',
    ],
    tags: ['Cellar', 'Tithe', 'Stealth'],
    parentLocationId: 'location-wardens-lamp-house',
    npcIds: ['npc-tamsin-reed', 'npc-halloran-wick'],
    factionIds: ['faction-lantern-wardens'],
    encounterIds: ['encounter-oil-cellar-sneak'],
    questIds: ['quest-the-tithe-night', 'quest-the-eighth-voice'],
    handoutIds: ['handout-wardens-tithe-tally', 'lore-lamp-lighting-rite'],
    notes:
      'Tamsin will let the party in if she is frightened enough and no one else is watching. The ruts from the handcart lead, three nights out of seven, to the Verrow well.',
  },
  {
    id: 'location-reedwalk',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Reedwalk',
    type: 'wilderness',
    shortDescription:
      'A mile of waist-high reeds and quicksilt that loops back on itself unless a memory is paid.',
    description: [
      'Three landmarks mark the Reedwalk: a leaning post with a rusted bell, a split willow, and a flat stone with a ferryman’s cut-mark. They come again, and again, in the same order, until the party gives something to the shrine.',
      'Between the landmarks the ground is treacherous. Quicksilt pools shine like polished pewter and pull at boots with a patience that feels intentional. Giant frogs wait in the reed shadows, and the will-o’-wisps that lead travellers astray wear the shape of a ferryman’s lantern.',
    ],
    tags: ['Wilderness', 'Hazard', 'Memory loop'],
    npcIds: ['npc-odo-tarn'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-reedwalk-sinkholes', 'encounter-lantern-loop'],
    questIds: ['quest-follow-the-blue-lantern'],
    handoutIds: ['lore-reedbound-procession'],
    sceneTemplateId: 'scene-mourningfen-lantern-path',
    notes:
      'Session 1 played this as the lantern path. Re-use it for any future trip between village and homestead; the loop only shortens once a name has been spoken at the shrine.',
  },
  {
    id: 'location-tidewake-burying-ground',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Tidewake Burying Ground',
    type: 'landmark',
    shortDescription:
      'The only consecrated ground in the fen, a raised island of graves with a row of unnamed markers.',
    description: [
      'The dead are buried upright in clay and marked with a slate each, carved by Fenwick Oar. At the far edge is a row of seven slates with nothing cut into them, set a hand-width deeper than the rest.',
      'The ground sinks a little every spring and the Society refills it. They have never found a body beneath the unnamed row. Fenwick insists he still hears digging.',
      'On the night of the tithe, mist fills the island to head height and the unnamed slates drip with cold water.',
    ],
    tags: ['Graveyard', 'Consecrated', 'Unnamed dead'],
    parentLocationId: 'location-mourningfen-village',
    npcIds: ['npc-fenwick-oar', 'npc-maudlin-tarn'],
    factionIds: ['faction-burial-society'],
    encounterIds: ['encounter-unnamed-dead'],
    questIds: ['quest-ferrymans-last-fare', 'quest-village-that-forgot'],
    handoutIds: ['handout-burial-roll-extract'],
    notes:
      'Odo Tarn’s grave is here, and his widow, Maudlin, lights a candle at it each dusk. The unnamed row is the physical proof the Verrows were once buried and then unburied.',
  },
  {
    id: 'location-verrow-hall',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Verrow Hall',
    type: 'room',
    shortDescription:
      'The homestead’s long entry hall with seven empty frames and a mirror that shows only the dark.',
    description: [
      'The hall is the hub of the loop. Every room opens from it and every room can, if a mirror is covered, become the hall again. Seven frames hang along the walls, each holding a canvas the colour of old milk.',
      'A tall mirror at the far end reflects the room correctly but nothing in it that is alive. Characters see the frames, the stairs, and the lamplight, and no one standing in front of it.',
      'Above the door to the well-room hangs an eighth frame, larger than the rest, and its canvas is already beginning to darken.',
    ],
    tags: ['Hub', 'Mirrors', 'Portraits'],
    parentLocationId: 'location-verrow-homestead',
    npcIds: ['npc-pim-verrow', 'npc-ottoline-verrow'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-shifting-rooms'],
    questIds: ['quest-what-the-house-remembers', 'quest-pims-seven-boats'],
    handoutIds: ['handout-family-portrait-frames'],
    sceneTemplateId: 'scene-verrow-homestead-loop',
    notes:
      'Treat the hall as the reset point of the loop. The portraits, once restored, should fix the floor plan permanently, one room at a time.',
  },
  {
    id: 'location-verrow-kitchen',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Verrow Kitchen',
    type: 'room',
    shortDescription:
      'A warm, lived-in kitchen where a kettle never boils and a grandmother never turns around.',
    description: [
      'The hearth is lit and the room is the warmest in the house. A black kettle hangs over the fire, steam curling from the spout without ever quite becoming a sound.',
      'Ottoline Verrow sits at the table with her back to the door, shelling peas into a bowl that stays empty. She does not turn until someone says her name correctly.',
      'On the sill sits a row of jars. Each holds a different dried herb, and a card in neat script tells what it was for, what it cost, and who had it last.',
    ],
    tags: ['Kitchen', 'Grandam', 'Warm room'],
    parentLocationId: 'location-verrow-homestead',
    npcIds: ['npc-ottoline-verrow'],
    factionIds: ['faction-reedbound', 'faction-marrowbone-circle'],
    encounterIds: ['encounter-grandam-kitchen'],
    questIds: [
      'quest-what-the-house-remembers',
      'quest-the-remedy-for-forgetting',
    ],
    handoutIds: ['handout-folk-remedy-card'],
    notes:
      'A second safe room of a kind: the grandam will not attack a guest who accepts tea. The jar labels are the source of the folk remedy handout.',
  },
  {
    id: 'location-salt-pear-orchard',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Salt Pear Orchard',
    type: 'wilderness',
    shortDescription:
      'A walled orchard behind the homestead where the pears are salty and something sweet-voiced trades for memories.',
    description: [
      'Seven twisted pear trees stand in a ring inside a low stone wall. The fruit hangs pale as candle wax. It tastes of brine, and the bite sharpens whatever the eater was thinking about.',
      'A woman in a green shawl sits on the wall most evenings, humming, and offers a pear for one small memory. She will accept an apology, a warning, or a name, and she keeps all of them.',
    ],
    tags: ['Orchard', 'Hag', 'Bargain'],
    parentLocationId: 'location-verrow-homestead',
    npcIds: [],
    factionIds: ['faction-mere-below'],
    encounterIds: ['encounter-pear-wife'],
    questIds: ['quest-what-the-house-remembers'],
    handoutIds: [],
    notes:
      'Optional detour. The Pear-Wife is no friend of the Eighth Voice; she is a scavenger who feeds on what the well spills.',
  },
];
