import type { CampaignLocation } from '../ashes-of-veyra/types';
import { MOURNINGFEN_CAMPAIGN_ID } from './campaign';

export const MAP_MARSH_ID = 'map-mourningfen-marsh';
export const MAP_HOMESTEAD_ID = 'map-verrow-homestead';

export const locations: CampaignLocation[] = [
  {
    id: 'location-mourningfen-village',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Mourningfen Village',
    type: 'district',
    shortDescription:
      'A stilted village of reed roofs and blue lamps, where every house sets one chair too many.',
    description: [
      'Boardwalks connect a few dozen homes above the waterline. Lamps burn blue after dusk and no one will say who lit them.',
      'The Burial Society hall sits at the centre, its registers kept in a room that smells of lamp oil and river mud.',
    ],
    tags: ['Village', 'Boardwalks', 'Registers'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-village',
    npcIds: ['npc-hesper-crane', 'npc-bettin-sallow'],
    factionIds: ['faction-lantern-wardens', 'faction-burial-society'],
    encounterIds: ['encounter-warden-lamp-patrol'],
    questIds: ['quest-village-that-forgot'],
    handoutIds: [
      'handout-births-register-extract',
      'handout-blank-funeral-page',
      'lore-fen-fever',
    ],
    notes:
      'The regional hub. Use district records for specific scenes; the archive door is the blocked thread for Act I.',
  },
  {
    id: 'location-crossing-ferry-landing',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Crossing Ferry Landing',
    type: 'pier',
    shortDescription:
      'The old ferry stage where Odo Tarn’s lantern was last seen before he drowned.',
    description: [
      'A tilted stage and a rope ferry with a brass bell that rings on its own after dark.',
      'The landing board still lists fares for a stop called Verrow that appears on no map.',
    ],
    tags: ['Ferry', 'Landing', 'Ghost'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-ferry-landing',
    npcIds: ['npc-odo-tarn'],
    factionIds: ['faction-lantern-wardens', 'faction-reedbound'],
    encounterIds: ['encounter-lantern-loop'],
    questIds: ['quest-follow-the-blue-lantern', 'quest-ferrymans-last-fare'],
    handoutIds: ['handout-ferrymans-lantern-tag'],
    sceneTemplateId: 'scene-mourningfen-lantern-path',
    notes: 'The party lost the last passenger’s trail here; the quest is on hold.',
  },
  {
    id: 'location-drowned-shrine',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Drowned Shrine',
    type: 'landmark',
    shortDescription:
      'A half-sunk shrine where the fen collects a memory from anyone who wants to pass.',
    description: [
      'Seven stones ring a shallow pool, each carved with a name that has been worn to a groove.',
      'A coin dish sits on the altar. Whatever is placed there is taken; so, quietly, is whatever the giver was thinking about.',
    ],
    tags: ['Shrine', 'Memory toll', 'Reedbound'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-shrine',
    npcIds: ['npc-ysolde-verrow', 'npc-odo-tarn'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-reedbound-procession', 'encounter-lantern-loop'],
    questIds: ['quest-follow-the-blue-lantern', 'quest-ferrymans-last-fare'],
    handoutIds: ['lore-reedbound-procession'],
    notes: 'Every surrendered memory should be written down and can return altered.',
  },
  {
    id: 'location-reedcutters-rest',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: "Reedcutters' Rest",
    type: 'tavern',
    shortDescription:
      'A low taproom that sets a place for a family no one can name.',
    description: [
      'The hearth burns peat and the ale tastes faintly of smoke and river.',
      'Goody Ashby sets a sixth chair at the long table every night and has never been able to say why.',
    ],
    tags: ['Tavern', 'Rumors', 'Empty chair'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-reedcutters',
    npcIds: ['npc-goody-ashby', 'npc-dunmore-fenn'],
    factionIds: ['faction-fenfolk-drovers'],
    encounterIds: ['encounter-drover-standoff'],
    questIds: ['quest-village-that-forgot'],
    handoutIds: [],
    notes: 'Best place to hear that half the drovers have already lost a year.',
  },
  {
    id: 'location-wardens-lamp-house',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Lamp House',
    type: 'government',
    shortDescription:
      'The Wardens’ stone lamp store, oil cellar, and the reeve’s counting room.',
    description: [
      'Rows of blue lamps hang from the rafters and the cellar holds more oil than the marsh could burn.',
      'The reeve’s table is neat and bare, with a locked chest that Tamsin Reed has clearly been avoiding.',
    ],
    tags: ['Government', 'Wardens', 'Tithe'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-lamp-house',
    npcIds: ['npc-hesper-crane', 'npc-tamsin-reed'],
    factionIds: ['faction-lantern-wardens'],
    encounterIds: ['encounter-warden-lamp-patrol'],
    questIds: [
      'quest-village-that-forgot',
      'quest-ferrymans-last-fare',
      'quest-the-eighth-voice',
    ],
    handoutIds: ['handout-wardens-tithe-tally'],
    notes: 'The reeve has not yet been confronted; the tension is open.',
  },
  {
    id: 'location-eel-market',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Eel Market',
    type: 'market',
    shortDescription:
      'A floating market where drovers trade eels, rope, and gossip.',
    description: [
      'Barges are lashed together and rocked by any passing wake.',
      'The only stall the Wardens do not visit is Dunmore Fenn’s, and everyone knows why.',
    ],
    tags: ['Market', 'Drovers', 'Crowds'],
    mapId: MAP_MARSH_ID,
    pinId: 'pin-mf-eel-market',
    npcIds: ['npc-dunmore-fenn'],
    factionIds: ['faction-fenfolk-drovers'],
    encounterIds: ['encounter-drover-standoff'],
    questIds: ['quest-village-that-forgot'],
    handoutIds: [],
    notes: 'Public proof here will turn the market one way or the other.',
  },
  {
    id: 'location-verrow-homestead',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Verrow Homestead',
    type: 'landmark',
    shortDescription:
      'A farmhouse absent from every map, whose rooms rearrange around the memories the party gave up.',
    description: [
      'Mirrors hang in every room and none of them show the party. Seven empty frames line the hall.',
      'The doors open onto rooms that were there yesterday and are not there now.',
    ],
    tags: ['Haunted house', 'Puzzle', 'Session 2'],
    mapId: MAP_HOMESTEAD_ID,
    pinId: 'pin-mf-homestead',
    npcIds: ['npc-pim-verrow', 'npc-ysolde-verrow'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-shifting-rooms'],
    questIds: [
      'quest-follow-the-blue-lantern',
      'quest-what-the-house-remembers',
    ],
    handoutIds: ['handout-family-portrait-frames'],
    sceneTemplateId: 'scene-verrow-homestead-loop',
    notes: 'The room loop diagram is complete; the portraits are not.',
  },
  {
    id: 'location-homestead-nursery',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'Homestead Nursery',
    type: 'landmark',
    shortDescription:
      'The smallest room, where Pim’s counting rhyme is painted on the wall and never finishes.',
    description: [
      'A child’s bed, a row of wooden boats, and a wall painted with seven verses and a blank space.',
      'It is the only room that never moves.',
    ],
    tags: ['Nursery', 'Counting rhyme', 'Safe room'],
    mapId: MAP_HOMESTEAD_ID,
    pinId: 'pin-mf-nursery',
    npcIds: ['npc-pim-verrow'],
    factionIds: ['faction-reedbound'],
    encounterIds: ['encounter-shifting-rooms'],
    questIds: ['quest-what-the-house-remembers'],
    handoutIds: ['handout-counting-rhyme', 'handout-family-portrait-frames'],
    notes: 'Treat as the party’s fixed point and rest spot during the loop.',
  },
  {
    id: 'location-verrow-well',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    name: 'The Verrow Well',
    type: 'landmark',
    shortDescription:
      'A dry well at the back of the homestead that the village sealed and never forgot.',
    description: [
      'Iron bands run around the stones and the cover is warm to the touch.',
      'At night the well speaks the last word of the counting rhyme.',
    ],
    tags: ['Well', 'Entity', 'Choice'],
    mapId: MAP_HOMESTEAD_ID,
    pinId: 'pin-mf-well',
    npcIds: ['npc-the-eighth-voice'],
    factionIds: ['faction-mere-below'],
    encounterIds: ['encounter-well-whisperer'],
    questIds: ['quest-what-the-house-remembers', 'quest-the-eighth-voice'],
    handoutIds: ['lore-forgetting-bargain', 'handout-counting-rhyme'],
    notes: 'The unresolved choice: restore the family or seal the well.',
  },
];
