import type { CampaignQuest, QuestObjective } from '../ashes-of-veyra/types';
import { MOURNINGFEN_CAMPAIGN_ID, mourningfenSessionId as s } from './campaign';

export const quests: CampaignQuest[] = [
  {
    id: 'quest-follow-the-blue-lantern',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Follow the Blue Lantern',
    status: 'complete',
    priority: 'medium',
    summary:
      'Follow the dead ferryman’s lantern through the fen to whatever it has been trying to reach.',
    giverNpcId: 'npc-odo-tarn',
    factionIds: ['faction-reedbound'],
    sessionIds: [s(1)],
    locationIds: [
      'location-crossing-ferry-landing',
      'location-drowned-shrine',
      'location-verrow-homestead',
    ],
    objectiveIds: [
      'objective-follow-lantern',
      'objective-name-the-procession',
      'objective-reach-homestead',
    ],
  },
  {
    id: 'quest-what-the-house-remembers',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'What the House Remembers',
    status: 'active',
    priority: 'high',
    summary:
      'Restore the homestead’s true floor plan, hear the whole counting rhyme, and decide what to do about the well before anyone else does it for them.',
    giverNpcId: 'npc-ysolde-verrow',
    factionIds: ['faction-reedbound', 'faction-mere-below'],
    sessionIds: [s(2), s(4)],
    locationIds: [
      'location-verrow-homestead',
      'location-homestead-nursery',
      'location-verrow-well',
    ],
    objectiveIds: [
      'objective-recover-portraits',
      'objective-solve-room-loop',
      'objective-hear-final-verse',
      'objective-decide-the-well',
    ],
  },
  {
    id: 'quest-village-that-forgot',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Village That Forgot',
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Learn who signed away the Verrows’ memory and why the village records still hold room for them. Stalled at the burial archive door.',
    giverNpcId: 'npc-dunmore-fenn',
    factionIds: [
      'faction-lantern-wardens',
      'faction-burial-society',
      'faction-fenfolk-drovers',
    ],
    sessionIds: [s(1), s(2), s(3)],
    locationIds: [
      'location-mourningfen-village',
      'location-wardens-lamp-house',
      'location-eel-market',
    ],
    objectiveIds: [
      'objective-audit-birth-register',
      'objective-open-burial-archive',
      'objective-question-the-reeve',
    ],
  },
  {
    id: 'quest-ferrymans-last-fare',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: "The Ferryman's Last Fare",
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Discover who Odo Tarn was carrying when he drowned. No progress since the party lost the trail at the ferry landing.',
    giverNpcId: 'npc-odo-tarn',
    factionIds: ['faction-lantern-wardens', 'faction-reedbound'],
    sessionIds: [s(1), s(3)],
    locationIds: [
      'location-crossing-ferry-landing',
      'location-wardens-lamp-house',
    ],
    objectiveIds: [
      'objective-identify-last-passenger',
      'objective-recover-toll-coin',
    ],
  },
  {
    id: 'quest-the-eighth-voice',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Eighth Voice',
    status: 'not-started',
    priority: 'low',
    summary:
      'Give the thing beneath the well a name or take away its reason to ask for one, and end the yearly tithe.',
    factionIds: ['faction-mere-below', 'faction-lantern-wardens'],
    sessionIds: [s(4)],
    locationIds: ['location-verrow-well', 'location-wardens-lamp-house'],
    objectiveIds: ['objective-name-the-eighth', 'objective-close-the-tithe'],
  },
  {
    id: 'quest-a-place-at-the-long-table',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'A Place at the Long Table',
    status: 'complete',
    priority: 'low',
    summary:
      'Find out why Goody Ashby sets a sixth chair every night and why the whole village does the same. A small mystery that opened the larger one.',
    giverNpcId: 'npc-goody-ashby',
    factionIds: ['faction-fenfolk-drovers'],
    sessionIds: [s(1)],
    locationIds: ['location-reedcutters-rest', 'location-mourningfen-village'],
    objectiveIds: [
      'objective-count-the-chairs',
      'objective-ask-the-innkeeper',
    ],
    resolution:
      'The party established that every household in the village sets exactly the number of chairs that the erased family once needed, and that no one can say who sits in them. The answer fed the Verrow thread rather than closing on its own.',
  },
  {
    id: 'quest-pims-seven-boats',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Pim’s Seven Boats',
    status: 'active',
    priority: 'medium',
    summary:
      'Pim Verrow has seven little wooden boats in the nursery and has lost six. Each is hidden in a room that only exists while its portrait is in place. Returning them is how the house learns to stay still.',
    giverNpcId: 'npc-pim-verrow',
    factionIds: ['faction-reedbound'],
    sessionIds: [s(2)],
    locationIds: ['location-homestead-nursery', 'location-verrow-hall'],
    objectiveIds: [
      'objective-find-the-boats',
      'objective-return-the-boats',
      'objective-the-eighth-boat',
    ],
  },
  {
    id: 'quest-the-tithe-night',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Night of the Tithe',
    status: 'not-started',
    priority: 'high',
    summary:
      'The Wardens pay the well once a year, in oil and in remembered things. Tamsin Reed knows the night is soon. The party can watch it happen, join it, or break it.',
    giverNpcId: 'npc-tamsin-reed',
    factionIds: ['faction-lantern-wardens', 'faction-mere-below'],
    sessionIds: [s(3), s(4)],
    locationIds: [
      'location-lantern-oil-cellar',
      'location-wardens-lamp-house',
      'location-verrow-well',
    ],
    objectiveIds: [
      'objective-learn-the-tithe-date',
      'objective-follow-the-oil-cart',
      'objective-decide-to-interfere',
    ],
  },
  {
    id: 'quest-the-remedy-for-forgetting',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'A Remedy for Forgetting',
    status: 'not-started',
    priority: 'medium',
    summary:
      'Marl Quillon believes a folk remedy of pale reed and bogbean can return a handful of lost days to a drover. She needs a missing ingredient from the Verrow kitchen and a witness who can say whether it works.',
    giverNpcId: 'npc-marl-quillon',
    factionIds: ['faction-marrowbone-circle', 'faction-fenfolk-drovers'],
    sessionIds: [s(3)],
    locationIds: ['location-eel-market', 'location-verrow-kitchen'],
    objectiveIds: [
      'objective-meet-the-herbalist',
      'objective-gather-the-herbs',
      'objective-test-the-remedy',
    ],
  },
  {
    id: 'quest-the-assize-rides-in',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Assize Rides In',
    status: 'not-started',
    priority: 'low',
    summary:
      'A circuit clerk with a sealed writ will arrive in the village within the month. The party can feed her the truth, hide it, or hand the archive to the one person with legal power to force it open.',
    giverNpcId: 'npc-sabine-vale',
    factionIds: [
      'faction-greywater-assize',
      'faction-burial-society',
      'faction-lantern-wardens',
    ],
    sessionIds: [s(3), s(4)],
    locationIds: ['location-mourningfen-village', 'location-tidewake-archive'],
    objectiveIds: [
      'objective-meet-the-clerk',
      'objective-share-or-hide-the-register',
    ],
  },
];

export const questObjectives: QuestObjective[] = [
  {
    id: 'objective-follow-lantern',
    questId: 'quest-follow-the-blue-lantern',
    order: 1,
    title: 'Follow the lantern past the three repeating landmarks',
    status: 'complete',
    clueIds: ['clue-repeating-landmarks'],
    locationIds: ['location-crossing-ferry-landing', 'location-drowned-shrine'],
  },
  {
    id: 'objective-name-the-procession',
    questId: 'quest-follow-the-blue-lantern',
    order: 2,
    title: 'Survive or appease the reedbound procession',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-drowned-shrine'],
  },
  {
    id: 'objective-reach-homestead',
    questId: 'quest-follow-the-blue-lantern',
    order: 3,
    title: 'Reach the homestead that is on no map',
    status: 'complete',
    clueIds: ['clue-repeating-landmarks'],
    locationIds: ['location-verrow-homestead'],
  },
  {
    id: 'objective-recover-portraits',
    questId: 'quest-what-the-house-remembers',
    order: 1,
    title: 'Find the seven family portraits',
    status: 'active',
    clueIds: ['clue-mirror-covers'],
    locationIds: ['location-verrow-homestead', 'location-homestead-nursery'],
  },
  {
    id: 'objective-solve-room-loop',
    questId: 'quest-what-the-house-remembers',
    order: 2,
    title: 'Solve the shifting room loop',
    status: 'active',
    clueIds: ['clue-mirror-covers'],
    locationIds: ['location-verrow-homestead'],
  },
  {
    id: 'objective-hear-final-verse',
    questId: 'quest-what-the-house-remembers',
    order: 3,
    title: 'Hear the final verse of the counting rhyme',
    status: 'pending',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-homestead-nursery', 'location-verrow-well'],
  },
  {
    id: 'objective-decide-the-well',
    questId: 'quest-what-the-house-remembers',
    order: 4,
    title: 'Decide whether to restore the family or seal the well',
    status: 'blocked',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-verrow-well'],
  },
  {
    id: 'objective-audit-birth-register',
    questId: 'quest-village-that-forgot',
    order: 1,
    title: 'Audit the village birth and death registers',
    status: 'complete',
    clueIds: ['clue-extra-births'],
    locationIds: ['location-mourningfen-village'],
  },
  {
    id: 'objective-open-burial-archive',
    questId: 'quest-village-that-forgot',
    order: 2,
    title: 'Open the Tidewake Burial Society archive',
    status: 'blocked',
    clueIds: ['clue-blank-funeral-page'],
    locationIds: ['location-mourningfen-village'],
  },
  {
    id: 'objective-question-the-reeve',
    questId: 'quest-village-that-forgot',
    order: 3,
    title: 'Put the lamp oil tally to Reeve Crane',
    status: 'pending',
    clueIds: ['clue-lamp-oil-tithe'],
    locationIds: ['location-wardens-lamp-house'],
  },
  {
    id: 'objective-identify-last-passenger',
    questId: 'quest-ferrymans-last-fare',
    order: 1,
    title: 'Identify Odo Tarn’s last passenger',
    status: 'blocked',
    clueIds: ['clue-ferry-toll-coin'],
    locationIds: ['location-crossing-ferry-landing'],
  },
  {
    id: 'objective-recover-toll-coin',
    questId: 'quest-ferrymans-last-fare',
    order: 2,
    title: 'Recover the toll coin from the drowned shrine',
    status: 'pending',
    clueIds: ['clue-ferry-toll-coin'],
    locationIds: ['location-drowned-shrine'],
  },
  {
    id: 'objective-name-the-eighth',
    questId: 'quest-the-eighth-voice',
    order: 1,
    title: 'Learn what name the Eighth Voice is missing',
    status: 'pending',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-verrow-well'],
  },
  {
    id: 'objective-close-the-tithe',
    questId: 'quest-the-eighth-voice',
    order: 2,
    title: 'End the yearly tithe of remembered things',
    status: 'pending',
    clueIds: ['clue-lamp-oil-tithe'],
    locationIds: ['location-wardens-lamp-house'],
  },
  {
    id: 'objective-count-the-chairs',
    questId: 'quest-a-place-at-the-long-table',
    order: 1,
    title: 'Count the chairs at three different tables',
    status: 'complete',
    clueIds: ['clue-sixth-chair'],
    locationIds: ['location-reedcutters-rest', 'location-mourningfen-village'],
  },
  {
    id: 'objective-ask-the-innkeeper',
    questId: 'quest-a-place-at-the-long-table',
    order: 2,
    title: 'Ask Goody Ashby who the sixth chair is for',
    status: 'complete',
    clueIds: ['clue-sixth-chair'],
    locationIds: ['location-reedcutters-rest'],
  },
  {
    id: 'objective-find-the-boats',
    questId: 'quest-pims-seven-boats',
    order: 1,
    title: 'Find the six missing boats in their rooms',
    status: 'active',
    clueIds: ['clue-mirror-covers'],
    locationIds: ['location-verrow-hall', 'location-verrow-kitchen'],
  },
  {
    id: 'objective-return-the-boats',
    questId: 'quest-pims-seven-boats',
    order: 2,
    title: 'Set each boat on its shelf in the nursery',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-homestead-nursery'],
  },
  {
    id: 'objective-the-eighth-boat',
    questId: 'quest-pims-seven-boats',
    order: 3,
    title: 'Decide what to do about the eighth boat, which no one has carved',
    status: 'blocked',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-homestead-nursery', 'location-verrow-well'],
  },
  {
    id: 'objective-learn-the-tithe-date',
    questId: 'quest-the-tithe-night',
    order: 1,
    title: 'Learn the night of the tithe from Tamsin or the tally',
    status: 'pending',
    clueIds: ['clue-lamp-oil-tithe'],
    locationIds: ['location-wardens-lamp-house'],
  },
  {
    id: 'objective-follow-the-oil-cart',
    questId: 'quest-the-tithe-night',
    order: 2,
    title: 'Follow the oil cart from the cellar to the well',
    status: 'pending',
    clueIds: ['clue-oil-cart-ruts'],
    locationIds: ['location-lantern-oil-cellar', 'location-verrow-well'],
  },
  {
    id: 'objective-decide-to-interfere',
    questId: 'quest-the-tithe-night',
    order: 3,
    title: 'Decide whether to stop, join, or witness the tithe',
    status: 'pending',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-verrow-well'],
  },
  {
    id: 'objective-meet-the-herbalist',
    questId: 'quest-the-remedy-for-forgetting',
    order: 1,
    title: 'Meet Marl Quillon at the edge of the eel market',
    status: 'pending',
    clueIds: [],
    locationIds: ['location-eel-market'],
  },
  {
    id: 'objective-gather-the-herbs',
    questId: 'quest-the-remedy-for-forgetting',
    order: 2,
    title: 'Gather pale reed, bogbean and one dried leaf from the Verrow kitchen',
    status: 'pending',
    clueIds: ['clue-remedy-card', 'clue-salt-pear-orchard'],
    locationIds: ['location-verrow-kitchen', 'location-salt-pear-orchard'],
  },
  {
    id: 'objective-test-the-remedy',
    questId: 'quest-the-remedy-for-forgetting',
    order: 3,
    title: 'Give the remedy to a drover and record what returns',
    status: 'pending',
    clueIds: ['clue-remedy-card'],
    locationIds: ['location-eel-market'],
  },
  {
    id: 'objective-meet-the-clerk',
    questId: 'quest-the-assize-rides-in',
    order: 1,
    title: 'Meet Sabine Vale before the Wardens do',
    status: 'pending',
    clueIds: ['clue-assize-seal'],
    locationIds: ['location-mourningfen-village'],
  },
  {
    id: 'objective-share-or-hide-the-register',
    questId: 'quest-the-assize-rides-in',
    order: 2,
    title: 'Decide whether to show the Assize the birth register',
    status: 'pending',
    clueIds: ['clue-extra-births', 'clue-assize-seal'],
    locationIds: ['location-tidewake-archive'],
  },
];
