import type { CampaignQuest, QuestObjective } from '../ashes-of-veyra/types';
import { MOURNINGFEN_CAMPAIGN_ID, mourningfenSessionId as s } from './campaign';

export const quests: CampaignQuest[] = [
  {
    id: 'quest-follow-the-blue-lantern',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'Follow the Blue Lantern',
    status: 'complete',
    priority: 'medium',
    summary:
      'Follow the dead ferryman’s lantern through the fen to whatever it has been trying to reach.',
    giverNpcId: 'npc-odo-tarn',
    factionIds: ['faction-reedbound'],
    sessionIds: [s(1)],
    locationIds: [
      'location-crossing-ferry-landing',
      'location-drowned-shrine',
      'location-verrow-homestead',
    ],
    objectiveIds: [
      'objective-follow-lantern',
      'objective-name-the-procession',
      'objective-reach-homestead',
    ],
  },
  {
    id: 'quest-what-the-house-remembers',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'What the House Remembers',
    status: 'active',
    priority: 'high',
    summary:
      'Restore the homestead’s true floor plan, hear the whole counting rhyme, and decide what to do about the well before anyone else does it for them.',
    giverNpcId: 'npc-ysolde-verrow',
    factionIds: ['faction-reedbound', 'faction-mere-below'],
    sessionIds: [s(2), s(4)],
    locationIds: [
      'location-verrow-homestead',
      'location-homestead-nursery',
      'location-verrow-well',
    ],
    objectiveIds: [
      'objective-recover-portraits',
      'objective-solve-room-loop',
      'objective-hear-final-verse',
      'objective-decide-the-well',
    ],
  },
  {
    id: 'quest-village-that-forgot',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Village That Forgot',
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Learn who signed away the Verrows’ memory and why the village records still hold room for them. Stalled at the burial archive door.',
    giverNpcId: 'npc-dunmore-fenn',
    factionIds: [
      'faction-lantern-wardens',
      'faction-burial-society',
      'faction-fenfolk-drovers',
    ],
    sessionIds: [s(1), s(2), s(3)],
    locationIds: [
      'location-mourningfen-village',
      'location-wardens-lamp-house',
      'location-eel-market',
    ],
    objectiveIds: [
      'objective-audit-birth-register',
      'objective-open-burial-archive',
      'objective-question-the-reeve',
    ],
  },
  {
    id: 'quest-ferrymans-last-fare',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: "The Ferryman's Last Fare",
    status: 'on-hold',
    priority: 'medium',
    summary:
      'Discover who Odo Tarn was carrying when he drowned. No progress since the party lost the trail at the ferry landing.',
    giverNpcId: 'npc-odo-tarn',
    factionIds: ['faction-lantern-wardens', 'faction-reedbound'],
    sessionIds: [s(1), s(3)],
    locationIds: [
      'location-crossing-ferry-landing',
      'location-wardens-lamp-house',
    ],
    objectiveIds: [
      'objective-identify-last-passenger',
      'objective-recover-toll-coin',
    ],
  },
  {
    id: 'quest-the-eighth-voice',
    campaignId: MOURNINGFEN_CAMPAIGN_ID,
    title: 'The Eighth Voice',
    status: 'not-started',
    priority: 'low',
    summary:
      'Give the thing beneath the well a name or take away its reason to ask for one, and end the yearly tithe.',
    factionIds: ['faction-mere-below', 'faction-lantern-wardens'],
    sessionIds: [s(4)],
    locationIds: ['location-verrow-well', 'location-wardens-lamp-house'],
    objectiveIds: ['objective-name-the-eighth', 'objective-close-the-tithe'],
  },
];

export const questObjectives: QuestObjective[] = [
  {
    id: 'objective-follow-lantern',
    questId: 'quest-follow-the-blue-lantern',
    order: 1,
    title: 'Follow the lantern past the three repeating landmarks',
    status: 'complete',
    clueIds: ['clue-repeating-landmarks'],
    locationIds: ['location-crossing-ferry-landing', 'location-drowned-shrine'],
  },
  {
    id: 'objective-name-the-procession',
    questId: 'quest-follow-the-blue-lantern',
    order: 2,
    title: 'Survive or appease the reedbound procession',
    status: 'complete',
    clueIds: [],
    locationIds: ['location-drowned-shrine'],
  },
  {
    id: 'objective-reach-homestead',
    questId: 'quest-follow-the-blue-lantern',
    order: 3,
    title: 'Reach the homestead that is on no map',
    status: 'complete',
    clueIds: ['clue-repeating-landmarks'],
    locationIds: ['location-verrow-homestead'],
  },
  {
    id: 'objective-recover-portraits',
    questId: 'quest-what-the-house-remembers',
    order: 1,
    title: 'Find the seven family portraits',
    status: 'active',
    clueIds: ['clue-mirror-covers'],
    locationIds: ['location-verrow-homestead', 'location-homestead-nursery'],
  },
  {
    id: 'objective-solve-room-loop',
    questId: 'quest-what-the-house-remembers',
    order: 2,
    title: 'Solve the shifting room loop',
    status: 'active',
    clueIds: ['clue-mirror-covers'],
    locationIds: ['location-verrow-homestead'],
  },
  {
    id: 'objective-hear-final-verse',
    questId: 'quest-what-the-house-remembers',
    order: 3,
    title: 'Hear the final verse of the counting rhyme',
    status: 'pending',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-homestead-nursery', 'location-verrow-well'],
  },
  {
    id: 'objective-decide-the-well',
    questId: 'quest-what-the-house-remembers',
    order: 4,
    title: 'Decide whether to restore the family or seal the well',
    status: 'blocked',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-verrow-well'],
  },
  {
    id: 'objective-audit-birth-register',
    questId: 'quest-village-that-forgot',
    order: 1,
    title: 'Audit the village birth and death registers',
    status: 'complete',
    clueIds: ['clue-extra-births'],
    locationIds: ['location-mourningfen-village'],
  },
  {
    id: 'objective-open-burial-archive',
    questId: 'quest-village-that-forgot',
    order: 2,
    title: 'Open the Tidewake Burial Society archive',
    status: 'blocked',
    clueIds: ['clue-blank-funeral-page'],
    locationIds: ['location-mourningfen-village'],
  },
  {
    id: 'objective-question-the-reeve',
    questId: 'quest-village-that-forgot',
    order: 3,
    title: 'Put the lamp oil tally to Reeve Crane',
    status: 'pending',
    clueIds: ['clue-lamp-oil-tithe'],
    locationIds: ['location-wardens-lamp-house'],
  },
  {
    id: 'objective-identify-last-passenger',
    questId: 'quest-ferrymans-last-fare',
    order: 1,
    title: 'Identify Odo Tarn’s last passenger',
    status: 'blocked',
    clueIds: ['clue-ferry-toll-coin'],
    locationIds: ['location-crossing-ferry-landing'],
  },
  {
    id: 'objective-recover-toll-coin',
    questId: 'quest-ferrymans-last-fare',
    order: 2,
    title: 'Recover the toll coin from the drowned shrine',
    status: 'pending',
    clueIds: ['clue-ferry-toll-coin'],
    locationIds: ['location-drowned-shrine'],
  },
  {
    id: 'objective-name-the-eighth',
    questId: 'quest-the-eighth-voice',
    order: 1,
    title: 'Learn what name the Eighth Voice is missing',
    status: 'pending',
    clueIds: ['clue-eighth-verse'],
    locationIds: ['location-verrow-well'],
  },
  {
    id: 'objective-close-the-tithe',
    questId: 'quest-the-eighth-voice',
    order: 2,
    title: 'End the yearly tithe of remembered things',
    status: 'pending',
    clueIds: ['clue-lamp-oil-tithe'],
    locationIds: ['location-wardens-lamp-house'],
  },
];
